### ISSUE TITLE
Boostrap the Project

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#1]
We're starting a new project.  We want to create a good base to start from.

# Tasks

- [x] Gradle Java project.
- [x] Basic "Hello World" ReST endpoint.
- [x] Check existing markdown files to ensure they're correct.
- [x] Renovate to keep dependencies up-to-date.
- [x] Give access to this repository to to Renovatebot
- [x] Create CI GitHub Action pipeline.
  - [x] Unit tests.
  - [x] Code format verification.
- [x] Set-up Snyk to do SCA stuff
- [x] Set-up CodeQL security scanning.
- [x] Precommit hooks
- [x] Github templates - @halprin
  - [x] story
  - [x] devex/opex
  - [x] design/research
  - [x] bug report
