### ISSUE TITLE
DB Staging Connection Pooling Issue

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1001]
# Backlog Task

Staging is timing out when saving metadata. We suspect this is caused by an issue with connection pooling via Hikari Connection Pool.

## Completion Criteria

- [x] We're able to save metadata in staging.

## Tasks
- [x] Check authentication and network settings
  - [x]  Azure managed identity service lifetime is 24 hours.
- [x] ~~Verify Azure Postgres flexible server settings (does that match PG's configuration and what we need?)~~
- [x] Implement new configuration in Hikari
  - [x] Set hikariCP `maxLifetime' to 23 hours and 57 minutes @saquino0827 
- [x] Verify Hikari settings
  - [x] ~~Test in the dev environment (before moving to staging)~~
    - [x]  N/A. Issue is not occurring in the Dev environment.
- [x]  Add logging for HikariCP token retrieval
- [x] Add Azure Log check monitoring for HikariCP invalid tokens
- [x] Rotate database password as new ones become available. - @halprin 
- [x] Verify Alert settings in staging
  - [x] Follow up tickets for any issue that arise.

**Comment by jorg3lopez** [comment]
Do we have any logs for this?

**Comment by saquino0827** [comment]
Since ticket #1001 got merged, I have not seen any alerts in Staging for the db connection issue. I feel we can close this task.

**Comment by saquino0827** [comment]
Spoke with @halprin and we agreed to close this task.
