### ISSUE TITLE
Update HCO Current State Flow for AL

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1003]
# Design or Research

Update the current state & clinical working lab flow for Baptist.

## Tasks

- [x] Synthesize notes
- [x] Update our diagram/flows based on our notes
- [x] Share the notes & Miro board with the rest of our team for their review
- [x] Send back to CDC for their review (EOD Monday)

## Additional Context

Add any other context or screenshots about the work here.

**Comment by JohnNKing** [comment]
To discuss during our next Office Hours (Wed)

**Comment by scleary1cs** [comment]
"Current State: end-to-end" reviewed with Manjula during Office Hours 04/24/2024.
