### ISSUE TITLE
CA: UCSD Results Production Connectivity

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1032]
# Story
As an ETOR-TI engineer, so that I can send messages to UCSD's production environment I need to create a production cert and set up the UCSD receiver in ReportStream's Prod environment

## Acceptance Criteria
- [x] Prod cert has been registered in fhir.epic.com
- [x] Transmission uses TLS 1.2 or greater and a strong cipher
- [x] prod key has been stored in ReportStream production key vault
- [x] Ticket for testing in prod created

## Tasks
- [x] Create production cert following instructions at: https://www.notion.so/flexion-cdc-ti/Epic-EHR-Onboarding-Steps-9a4cd71b2e4b49558013eda9df87427a#ab21d25b2f5248ef8d038780a5343ff0
- [x] Register production certificate with fhir.epic.com
- [x] Configure production private key in ReportStream
- [x] Receive transport details (e.g. API endpoint URLs)
- [x] Confirm headers will be similar to staging
- [x] Add production organization settings in ReportStream production (via request to RS, or via the admins on our team)

## Definition of Done
N/A

**Comment by basiliskus** [comment]
John's comment from slack: "Will need Jeffery & Dean to clarify prod API and remaining steps for production configuration in advance of go-live. More on this next week…"

**Comment by JohnNKing** [comment]
It looks like we also need a new cert added to fhir.epic.com. I suspect the staging cert was also used as a placeholder for prod -- as the hashes appear to match.

**Comment by JohnNKing** [comment]
More updates regarding getting the API endpoint in https://www.slack.com/archives/C044P2CBEKS/p1730926076942009?thread_ts=1730923984.569689&cid=C044P2CBEKS

**Comment by JohnNKing** [comment]
UCSD/Epic prod endpoints received and shared with the team.

**Comment by GilmoreA6** [comment]
update: added UCSD org and receiver into ReportStream Prod as "inactive" replaced authTokenUrl and reportUrl with prod values from Keybase UCSD-prod-endpoints.txt document. Replaced jwtParams: aud with autTokenUrl from Keybase UCSD-prod-endpoints.txt document. Replaced jwtParams: iss with Client ID for application Name ReportStream-UCSD in Keybase epic-client-ids.txt document

**Comment by JohnNKing** [comment]
@GilmoreA6 It will need to be generated on our side, and then registered with Epic via fhir.epic.com. I'm happy to assist. @jorg3lopez also has experience with their certificate registration process.

There are also instructions based on prior setup efforts at https://www.notion.so/flexion-cdc-ti/Epic-EHR-Onboarding-Steps-9a4cd71b2e4b49558013eda9df87427a?pvs=4#ab21d25b2f5248ef8d038780a5343ff0

^ Specifically, we're at the very last step for the **ReportStream-UCSD** app (Result => 9. Configure the Epic Production Connection)

Currently, there is a certificate registered for production -- but it appears to be the staging cert.

Lastly, to manage the app and certificates requires you be added to our organization in Epic. Anyone who needs access get have it granted by @halprin , @sfradkin , or myself.

**Comment by GilmoreA6** [comment]
certificate and keypair has been created and uploaded into keybase. Certificate is ready to upload to fhir.epic.com. Need to pair with @JohnNKing to get some historical context as the steps we followed to generate the cert are different than the documentation at https://fhir.epic.com/Documentation?docId=OAuth2
