### ISSUE TITLE
CA Results Service Blueprint

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1054]
# Story
Create a Service Blueprint for CA that is scoped to the results data flow.

## Completion Criteria

- [x] The CA service blueprint includes results handling and accurately represents what CA PHL, UCSD, & Epic requires.

## Tasks

- [x] Initial service blueprint created (based on AL)
- [x] Updated based on last week's SME meeting
- [x] Export diagram and add to Confluence
- [x] Notify CDC of diagram availability
- [x] Walked through the blueprint with the PHL and HCO
