### ISSUE TITLE
RS metadata fast follows

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1058]
# Design or Research

Fast follow up from story #690.

## Tasks
- [x] Schedule follow up meeting with Kalish to work on integration test - scheduling for 6/5/24
- [x] Add a gradle task that sets the ETOR_TI_baseurl - https://github.com/CDCgov/prime-reportstream/pull/14608
- [x] Add some info about how to add URL to .env.local (needed for docker-compose) - added to the [TI readme](https://github.com/CDCgov/trusted-intermediary?tab=readme-ov-file#reportstream-setup:~:text=If%20attempting%20to%20access%20the%20metadata%20endpoint%20in%20ReportStream%20add%20the%20variable%20ETOR_TI_baseurl%3D%22http%3A//host.docker.internal%3A8080%22%20to%20.prime%2Drouter/.vault/env/.env.local%20file%20before%20building%20the%20container)
- [x] Make database integration test

## Additional Context

Add any other context or screenshots about the work here.

Notes from Sylvie
1. add gradle task (possibly as a fast follow) that sets the environment variable - we need this for our own purposes ASAP
2. maybe add some info about how to add URL to .env.local (needed for docker-compose)
3. schedule follow up meeting with Kalish to work on integration test

**Comment by scleary1cs** [comment]
Error definitions needed.

**Comment by jcrichlake** [comment]
We are running into an issue that we believe resides in part of the RS testing code.  We have reached out to one of their engineers to ask if they can take a look at the issue since we believe it's something specific to their framework that is causing an issue.
