### ISSUE TITLE
AL Gap Analysis - Test Orders

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1090]
# Story
As AL HCO, to ensure we'll receive all needed results data to an EHR, we need to relate the ReportStream results information to what will be received by the EHR.

## Pre-conditions
- [x] *Assumptions of prior or future work that's out of scope for this story*

## Acceptance Criteria
- [x] Message profiles are now finalized
- [x] Publish list of transformation requirements for Intermediary
- [x] Get approvals
- [x] Create explicit stories for Intermediary transformation requirements

## Tasks
- [x] Draft side-by-side comparison of sender & receiver profiles
- [ ] Finalize side-by-side comparison of sender & receiver profiles
- [ ] Identify/highlight differences (gaps)
- [ ] Confirm gap solutions (3 possible actions)
  - [ ] 1. Sender will update configurations/message mappings to align with receiver profile
  - [ ] 2. Receiver will update message processing to align with sender profile
  - [ ] 3. Intermediary will transform/translate messages mid-stream to alleviate burden on sender & receiver
- [ ] Update message profiles (if sender or receiver are making changes to accommodate)
  
## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- Profile stories:
  - #992  
  - #618

**Comment by JohnNKing** [comment]
Also pending verification of order profile by Cerner
