### ISSUE TITLE
LA Gap Analysis - Test Orders

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1091]
# Story
As LA PHL, to ensure we'll receive all needed order data from an EHR, we need to understand how specimen card and LIMS fields relate to the data elements of an electronic order.

## Pre-conditions
- [ ] *Assumptions of prior or future work that's out of scope for this story*

## Acceptance Criteria
- [x] Message profiles are now finalized
- [x] Publish list of transformation requirements for Intermediary
- [x] Get approvals
- [x] Create explicit stories for Intermediary transformation requirements

## Tasks
- [x] Document side-by-side comparison of sender & receiver profiles
- [x] Identify/highlight differences (gaps)
- [x] Confirm gap solutions (3 possible actions)
  - [ ] 1. Sender will update configurations/message mappings to align with receiver profile
  - [ ] 2. Receiver will update message processing to align with sender profile
  - [ ] 3. Intermediary will transform/translate messages mid-stream to alleviate burden on sender & receiver
- [x] Update message profiles (if sender or receiver are making changes to accommodate)

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- Profile stories:
  - #991 
  - #585

**Comment by JScott-JMC** [comment]
@JohnNKing @brick-green 

All tasks for this story are complete. I think we can move this to Done.

**Comment by basiliskus** [comment]
Need to check with @JohnNKing that we're tracking and planning for pending work before closing this story
