### ISSUE TITLE
CA HCO Results Profile

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#1097]
# Story
As CA HCO, to ensure we'll receive all needed results data to an EHR, we need to relate the ReportStream results information to what will be received by the EHR.

## Pre-conditions
- none

## Acceptance Criteria
- [ ]  Approved message profile

## Tasks
- [x] Obtain publish message profile (if available)
- [x] Obtain sample messages
- [x] Document data elements of interest
  - [x] Optionality
  - [x] Cardinality
  - [x] Vocabulary requirements
- [x] Requested HCO feedback on our analysis
- [x] Confirm baseline profile requirements with Sender

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
Waiting on confirmation from the HCO regarding if what they've configured can be used for testing the full vocabulary range.
