### ISSUE TITLE
CA PHL Results Profile

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#1098]
# Story
CA PHL, to ensure we'll sending all needed results data to an EHR, we need to relate the LIMS results information to what will be sent out to ReportStream.

## Pre-conditions
- none

## Acceptance Criteria
- [x]  Approved message profile

## Tasks
- [x] Obtain publish message profile (if available)
- [x] Obtain sample messages
- [x] Document data elements of interest
  - [x] Optionality
  - [x] Cardinality
  - [x] Vocabulary requirements
- [x] Requested PHL feedback on our analysis
- [x] Confirm baseline profile requirements with Sender

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
Waiting on confirmation on the subpanels to clarify result codes for vocabulary.

**Comment by JohnNKing** [comment]
Awaiting partner feedback (e.g. unsat questions to CDPH)

**Comment by JohnNKing** [comment]
Tracking newly identified vocab items instead under #1110
