### ISSUE TITLE
CA Round-Trip Testing

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1110]
# Story
As a PHL or HCO, so that we're confident the various branches of our workflows will work under ETOR, we need to test various scenarios of NBS results between partner systems (e.g. EHR, LIMS).

## Pre-conditions
- Test planning has been completed
- Data gap analysis efforts have been completed and the test scenarios have been defined
- PHL and HCO can send and receive results messages to each other via ReportStream
- Connectivity and integration testing have been completed for both HCO and PHL

## Acceptance Criteria
- [ ] PHL has released test results based on the scenarios
- [ ] The HCO successfully processed those test results

## Tasks
- [x] Confirm with partners that no PII/PHI will be used during testing and that test messages can be later published in our public repo
- [ ] PHL executes the results tests in the test/staging environment
- [ ] Ensure hospital and lab have agreed upon a means to validate data integrity (e.g. shared screenshots of results report as displayed to clinician in EHR)
- [x] We've saved the HL7 messages used for testing to later create automated end-to-end testing
- [ ] Draft subsequent stories for automated testing to avoid regressions in the future (e.g. how to we ensure UCSD-specific transformations continue to work as code changes occur)
- [ ] We've revised internal test messages based on test results that were actually submitted by the partner (i.e. our collection of samples messages have been updated)
- [x] Track down cause of 3 undelivered sample messages on 10/16
  - [x] 2 were related to ORC-21-10
  - [x] We need to track down the cause of the third -  @basiliskus , @GilmoreA6 
- [x] Determine if ORC-21-10 data issue was an artifact of testing, or if modification of the filters will be required
- [x] Update vocab in the results profile based on the recently identified issue with unsats

## Test Case Scenarios ([link to master test scenarios sheet](https://docs.google.com/spreadsheets/d/1Y3vUVBPxOpIyIoMzVQL138y5nBRuZ2GI/edit?gid=1528161945#gid=1528161945))
- [x] 0. All in Range (Normal) Results - No Action Required
- [x] 1. Overall Normal Results with One Analyte Out of Range - No Action Required
- [ ] 1-Corrected. Overall Normal Results with One Analyte Out of Range - No Action Required
- [x] 2. a. Out of Range Results (GALT, BIO, SCID, Hypothyroidism, CAH, GAA, MPS-I, SMA, MPS-II, GAMT)
- [x] 2. b. Out of Range Results (CF, Hemoglobinopathies)
- [ ] ~~2. c. MS/MS Amino Acid & MS/MS Acylcarnitine - Positive Examples (Something Out of Range)~~
- [ ] 3. a. Incomplete Results (SMA, GAA, MPS-I, MPS-II)
- [ ] 3. b. Indeterminate Results (Blood Transfusion)
- [ ] 3. c. Indeterminate Results (CF Incomplete) + SCID Indeterminate
- [x] 4. Mixed Results - In Range, Indeterminate, Out of Range, Unsatisfactory
- [ ] 5. Additional Sequencing Performed for CF, MPS I, MPS II, Pompe, and ALD
- [ ] 6. Second Tier/Additional Initial Screen Testing Performed for CAH
- [x] 7. a. Out of Range Results for SCID - Initial Screen
- [x] 7. b. SCID Confirmatory Results - Unsolicited Message in Follow Up
- [ ] 8. Unsatisfactory Specimen

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by GilmoreA6** [comment]
For Task "Track down cause of 3 undelivered sample messages on 10/16" -
-We've confirmed that two of the 3 messages that didn't route due to absence of ORC-21-10 that is used for filtering reports on the RS side and for identifying messages for applying the USCD transform in ETOR-TI.
-The third message did not route due to an exception when attempting to parse the fhir bundle in RS for element Bundle.entry.resource.ofType(Observation).ValueQuantity.value of "065.88" where exception " ca.uhn.fhir.parser.DataFormatException: HAPI-1861: Failed to parse JSON encoded FHIR content: Invalid numeric value: Leading zeroes not allowed at [line: 1, column: 137695]" was thrown. The problematic value was converted from the OBX-5 value from the OBX segment: 
OBX|1|NM|38473-5^17-Hydroxyprogesterone^LN|1|### 0065.88|nmol/L|<85|N|||F|||20241015055726

**Comment by scleary1cs** [comment]
"Determine if ORC-21-10 data issue was an artifact of testing, or if modification of the filters will be required" 

We received a verbal and email confirmation that this data issue will not effect Prod. 

"Two of the test messages are missing ORC-21.10. This value is critical for routing - can CDPH confirm it will always be populated in production? Sumitha, can you please answer this question? – Yes it will be always populated in PROD." 
Subject = "Vocabulary Clarifications for ETOR Intermediary"

**Comment by kwright-bio** [comment]
Confirmed in SME call that 2b was ingested into the system. Can mark as complete once receiving a PDF from UCSD.
TCs 1, 7A, and 4 have had successful ingestion into UCSD but prior to the mu fix being implemented. These messages can likely be redropped and resent to UCSD and get confirmation the mu character looks good in final PDF exports for these (confirm this plan with team / HCO)

**Comment by kwright-bio** [comment]
Also a note that the CDPH generated results being used in testing are from a custom-built test result generator and not their SpecimenGate system.

**Comment by scleary1cs** [comment]
@kwright-bio and @dbgolson happy to circle back here and update the test cases based on what was just shared at Sprint Review.

**Comment by kwright-bio** [comment]
Added the newly created Indeterminate test cases. 
Note that 2b's comparison uncovered an issue where likely they have not mapped a code correctly.

**Comment by kwright-bio** [comment]
Added modified test cases based on CLIA documentation discussion and further descriptive refinement of 3 Indeterminate / Incomplete results testing.

Marking 3 cases as complete as final comparison between the UCSD generated PDF and the original CDPH results message are aligned for values, reference ranges, and units of measure - 1. Overall Normal Results with One Analyte Out of Range - No Action Required, 2. b. Out of Range Results (CF, Hemoglobinopathies), and 4. Mixed Results - In Range, Indeterminate, Out of Range, Unsatisfactory.

**Comment by kwright-bio** [comment]
Updated to include an additional test case to better align with desired CLIA validation. Marked off one more test case.

**Comment by scleary1cs** [comment]
@kwright-bio awesome job keeping the test cases up to date.

**Comment by kwright-bio** [comment]
Based on the clarification around the Reason for Test being an artifact of CDPH's testing system, we are marking 2A as complete. (We received "Subsequent screen - for clarification of initial results (not by law or protocol" in the message but were expecting "Initial screen.") CDPH has stated there was no original HL7 message for this test case and that in production it should be "Initial screen"

2C cannot be completed with CDPH's testing application as the application cannot correctly generate results that match a production message. In particular, "Newborn conditions with positive markers [Identifier] in Dried blood spot = “None"” when we would expect there would be an overall observation for "Newborn conditions with positive markers [Identifier] in Dried blood spot="CIT-II" (which is what CDPH says will be in production)".

**Comment by dbgolson** [comment]
Marking 2 cases as complete as final comparison between the UCSD generated PDF and the original CDPH results message are aligned for values, reference ranges, and units of measure - 7A. Out of Range Results for SCID - Initial Screen and 7B. SCID Confirmatory Results - Unsolicited Message in Follow Up.

**Comment by kwright-bio** [comment]
@dbgolson did the reconciliation and confirmed 1-Corrected and 6 are marked as complete.
