### ISSUE TITLE
NAK Alignment with ReportStream 

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1120]
# Backlog Task

Get alignment with the RS team on the importance and approach for supporting NAKs.

## Completion Criteria

- [x] We've reached a consensus with ReportStream regarding how to support NAKs.

## Tasks
- [x] Provide documentation to RS
  - [x] Draft user needs and product requirements - @JohnNKing 
    - [x] Added to https://app.zenhub.com/workspaces/cdc-ti-633de70d939f6c00155f3722/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTY2NTY3
  - [x] Document changes needs to RS to support NAKs
    - [x] Add to https://docs.google.com/document/d/1nm0LKq5DacykF0sBw40NHisAlRRifEn2j66hLirkd2Q/ (W.I.P.)
 - [ ] AQS retry mechanism: timeout expectations from partners vs RS timeouts
 - [x] Is the Simple solution viable?

## Other Notes

- Any other notes to help clarify this task for the team
- RS Question: Can the TI team be integrated into the RS poison queue PagerDuty alerts?
- Simple TI Error Notifications: Add TI Team pagerduty alerts on Azure failures with Order/Result handling/transport.

**Comment by JohnNKing** [comment]
RS can give us Azure search logs to identify RS failures. Also we may need access to Metabase. Also monitoring TI logs.

See https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BC4E8A17B-2AC4-44FF-8193-E9763021B11C%7D&file=RS_TI%20Product%20Sync%20Meeting%20Notes.docx&action=default&mobileredirect=true
