### ISSUE TITLE
Research: Automated TI <> RS tests

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1131]
# DevEx/OpEx

Create an automated end to end test(s) that includes specific callouts to/from TI/RS while making sure SFTP ingestion functionality is accounted for. 

## Tasks

- [x] Research and consider pact testing
- [x] Consider alternative options: [proposed solutions here](https://lucid.app/lucidchart/99226c79-94de-4beb-ad59-c991cafb6874/edit?beaconFlowId=1231B6134643FE5D&invitationId=inv_c49420a6-95f5-434a-8e88-049ae0477ba9&page=0_0#)

## Research Tasks

- [x] Talk to RS engineering team to evaluate possibility to:
  - [x] Include integration tests to CI/CD pipeline and have the tests be required for a PR to merge
    - [x] If not possible, we may want to add the tests to TI instead 
  - [x] Pull files from Azure blob storage (from tests in RS)
    - [x] If not possible, could the RS test download the file from an external SFTP service? 
- [x] Decide on a vertical slice to start implementation
  - [x] Start with creating integration tests in TI that will download the final HL7 message after it has gone through the entire flow (maybe from RS Azure Storage?), and create general assertions for it (i.e. it has MSH-6 to be able to route)
- [x] Decide on where the tests will be added (RS or TI) -> **TI**

After evaluating all the options, we have decided to implement [Solution 5.1](https://lucid.app/lucidchart/99226c79-94de-4beb-ad59-c991cafb6874/edit?beaconFlowId=1231B6134643FE5D&invitationId=inv_c49420a6-95f5-434a-8e88-049ae0477ba9&page=0_0#)

### Pact Testing Tasks

[Moved to Notion page](https://www.notion.so/flexion-cdc-ti/Contract-Testing-684a0c3070894028965c66d6a43d1936?pvs=4)

## Additional Context
- Months ago the ORM mapping broke and existing integration tests were rewritten to pass. However, key data was now being lost during message transformation.
- To detect scenarios like this in the future, we want an automated way to detect issues that utilize the full flow of data from RS, to TI, and back to RS.

Capture new story (from backlog refinement on 06/04/2024):
“End to end tests including flow with RS” #????
-Include HL7 
-Include SFTP Ingestion

**Comment by scleary1cs** [comment]
@jorg3lopez @basiliskus and @halprin  want to be part of this story's refinement.

**Comment by basiliskus** [comment]
Documentation on [JVM tools for pact testing](https://docs.pact.io/implementation_guides/jvm)
