### ISSUE TITLE
Migrate to Azure Entra IAM to Authenticate with Azure Container Registry.

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#1149]
# DevEx/OpEx

This affects both TI and the RS SFTP Ingestion service.

[Snyk has found](https://app.snyk.io/org/halprin/project/3e019b05-a89f-416c-b721-2958a06076ff#issue-SNYK-CC-AZURE-594_resource.azurerm_container_registry[registry].admin_enabled) that enabling the admin user of the Docker container registry is bad.  Indeed, that isn't the best.  We should pivot to using Azure Entra identities to authenticate and authorize ourselves.

## Tasks

- [ ] Figure out the correct Azure role is for pushing and pulling from an container registry.
- [ ] Give permissions to some managed identities.
  - [ ] Give the GitHub deployer the role for pushing images on the container registry.
  - [ ] Give the app service the role for pulling images from the container registry.
  - [ ] The above two tasks are tricky because the GitHub deployer is only allowed to give specific roles to other identities in the CDC Entra domain.  We will need to check whether the push and pull roles are allowed to be assigned.  If not, we need to request these roles be added to the allow list through the CDC Service Desk.
- [ ] Update `.github/workflows/deploy_reusable.yml` to use the new registry login paradigm.
- [ ] Update the app services' app settings in `operations/template/app.tf` to use the new registry login paradigm.

## Additional Context

Add any other context or screenshots about the work here.
