### ISSUE TITLE
External facing demo prep

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1151]
# Backlog Task

Planning and scheduling external facing demo.

## Completion Criteria

- [ ] The demo has taken place?

## Tasks

- [ ] Plan format?
- [ ] Scheduling 
- [ ] Attendee list
- [ ] Coordinating presenter list 
- [ ] Update projected "ready to go live" dates for states.

## Other Notes

- Any other notes to help clarify this task for the team
