### ISSUE TITLE
AL Service Blueprint: Error Handling

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1157]
# Backlog Task

Clarify elements of the AL service blueprint that pertain to error handling.

## Completion Criteria
- [x] Service blueprint updated where we had questions for the hospital

## Tasks

- [x] Clean up questions on the existing version of the service blueprint
- [x] Discuss open questions during SME call
- [x] Update and export blueprint based on partner feedback
- [x] Draft potential error/failure scenarios
- [x] Get team feedback on error/failure scenarios
- [x] Discuss error/failure scenarios with partners
- [x] Draft message templates for different error/failures
