### ISSUE TITLE
CA Service Blueprint: Error Handling

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1159]
# Backlog Task

Clarify elements of the CA service blueprint that pertain to error handling.

## Completion Criteria
- [x] Service blueprint updated where we had questions for the hospital

## Tasks

- [x] Clean up questions on the existing version of the service blueprint
- [x] Discuss open questions during SME call
- [x] Update and export blueprint
