### ISSUE TITLE
ORU Processing: Copy ORC-4 to OBR-2

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1194]
# Backlog Task

So that the ORU result can be filed, UCSD also needs the original value of ORC-4.1 & ORC-4.2 to be copied to outgoing OBR-2.1 & OBR-2.2.

Context: We're already copying ORC-4 to ORC-2, but not to OBR-2.

## Completion Criteria

- [x] For ORU results sent through through ReportStream for CA:
  - [x] Update OBR-2 with content from ORC-4 in the ORU result message:
    - [x] Replace OBR-2.1 with original content of ORC-4.1.
    - [x] Replace OBR-2.2 with original content of ORC-4.2

## Tasks

- [ ] What tasks need to be done to fulfill the completion criteria?

## Other Notes

- Any other notes to help clarify this task for the team
