### ISSUE TITLE
CA Round-Trip Test Plan

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1205]
# Story
As a PHL or HCO, so that we're confident the various branches of our workflows will work under ETOR, we need to plan out various test scenarios for NBS orders and results that will flow between our partner systems (e.g. EHR, LIMS).

## Pre-conditions
- Data gap analysis efforts have been completed
- PHL and HCO can send and receive results messages to each other via ReportStream
- Connectivity and integration testing have been completed for both HCO and PHL

## Acceptance Criteria
- [x] We've received approvals of the test scenarios from our HCO and PHL partners

## Tasks
- [x] Test scenarios refined based on data gap work
- [x] Request feedback on scenarios from the PHL
- [x] Request feedback on scenarios from the HCO
- [x] Update test scenarios based on partner feedback

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
Awaiting partner feedback (e.g. unsat questions to CDPH)

**Comment by JohnNKing** [comment]
Looks for AC completion confirmation before we can close this out
