### ISSUE TITLE
Dockerfiles using default root user

### ISSUE THREAD

**Issue by jcrichlake** [CDCgov/trusted-intermediary#1211]
# DevEx/OpEx

Priority: High

Need to specify a user for the dockerfiles in TI, the TI implementation guide, and the SFTP service

## Tasks

- [x] Play around with SFTP Ingestion Docker image. - @halprin 
- [x] Fix TI Docker image.
- [x] Fix RS SFTP Ingestion Service Docker image.

## Additional Context

Add any other context or screenshots about the work here.
