### ISSUE TITLE
Fortify: Use Customer Managed Keys

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#1214]
# DevEx/OpEx

Fortify is warning about us not using a customer managed key for our storage accounts and container registry.  We should look into what it takes to create and manage a customer managed key.  If it is like AWS KMS, I'm all for it.  If it takes additional work and management, I don't think it is worth the price of admission.

## Tasks

- [x] Figure out what it takes to make and create a customer managed key.
- [x] Do this for TI.
  - [x] Storage accounts.
  - [x] Container registries.
- [x] Do this for RS SFTP Ingestion.
  - [x] Storage accounts.
  - [x] Container registries.

## Additional Context

Category: Azure Terraform Misconfiguration: Storage Account Missing Infrastructure Encryption
Primary Location: storage.tf: 1, app.tf: 2

- https://learn.microsoft.com/en-us/azure/storage/common/customer-managed-keys-overview
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_key

**Comment by rajeev-flexion** [comment]
We can use azure key vault for this
1) creating a key vault and key
2) Associating the key with storage account

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account_customer_managed_key
