### ISSUE TITLE
Improve Notification Email Templates

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1215]
# Backlog Task

Update the error/failure email notification templates based on CDC feedback. 

## Completion Criteria

- [x] The email templates have been improved based on feedback.
- [x] The email templates have been shared with AL.

## Tasks

- [x] Review CDC provided feedback
- [x] Update draft to incorporate feedback
- [x] Request those be shared with AL
- [x] Get feedback from AL

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by JohnNKing** [comment]
Some updates made via Sharepoint; other updates are pending based upon our most recent collab session.

**Comment by JohnNKing** [comment]
Shared with AL last week. Awaiting any feedback.
