### ISSUE TITLE
Copy of LA Round-Trip Testing

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1232]
# Story
As a PHL or HCO, so that we're confident the various branches of our workflows will work under ETOR, test various scenarios that use test orders and corresponding results from  partner systems (e.g. EHR, LIMS).

## Pre-conditions
- HCO and PHL can send an receive orders and results messages to each other via ReportStream
- Connectivity and integration testing have been completed for both HCO and PHL

## Acceptance Criteria
- [ ] We've received feedback from HCOs and PHLs on test scenarios
- [ ] HCOs have submitted test orders based on the scenarios
- [ ] PHLs have returned test results based on the orders submitted
- [ ] We've revised internal test messages based on test orders and results that were actually submitted by the partner (i.e. our collection of samples messages have been updated)

## Tasks
- [x] Refine the mnemonics list 
- [x] Test plan refined based on data gap work
- [x] Request feedback on plan from LA PHL
- [ ] Request feedback on plan from the HCO
- [ ] Test scenarios refined based on data gap work
- [ ] Request feedback on scenarios from LA PHL
- [ ] Request feedback on scenarios from the HCO
- [ ] Update test scenarios based on partner feedback
- [ ] Confirm with partners that no PII/PHI will be used during testing and that test messages can be later published in our public repo
- [ ] HCO executes the order tests in their test/staging environment
- [ ] PHL executes the results tests in the test/staging environment
- [ ] Ensure hospital and lab have agreed upon a means to validate data integrity (e.g. shared screenshots of results report as displayed to clinician in EHR)
- [ ] We've saved the HL7 messages used for testing to later create automated end-to-end testing
- [ ] Draft subsequent stories for automated testing to avoid regressions in the future (e.g. how to we ensure birthweight conversion continues to work as code changes occur)

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
@JohnNKing to follow-up with @JScott-JMC if we're in a good place to consider this refined.

**Comment by JohnNKing** [comment]
> @JohnNKing to follow-up with @JScott-JMC if we're in a good place to consider this refined.

Discussed at end Refinement -- we're all good with this being refined.

**Comment by brick-green** [comment]
blocked on [LA Round-Trip Test Plan](https://github.com/orgs/CDCgov/projects/45/views/2?filterQuery=label:+LA+Integration&pane=issue&itemId=82926001&issue=CDCgov%7Ctrusted-intermediary%7C1111)

**Comment by brick-green** [comment]
@kwright-bio to add checklist of test cases
