### ISSUE TITLE
Document Epic Onboarding Process

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1235]
# Backlog Task

Document the process of how to connect to an Epic hospital via OAuth2 and deliver HL7 results.

## Completion Criteria

- [x] The onboarding document covers the steps to:
  - [x] Create a new Epic app registration
  - [x] Use and existing Epic app registration for a new hospital partner
- [x] The onboarding document is available to our team

## Tasks

- [x] Draft steps in Notion
- [x] Ask team for feedback
- [x] Make revisions based on feedback
- [x] Add certificate signing instructions
- [x] Finalize document 

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by scleary1cs** [comment]
https://www.notion.so/flexion-cdc-ti/Epic-EHR-Onboarding-Steps-9a4cd71b2e4b49558013eda9df87427a
