### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#124]
# Story
As a public health lab, to ensure only trusted hospitals are permitted to send newborn demographic data, I need the TI service to authenticate users attempting to submit data.

## Pre-conditions
- A single hospital test account is supported.
- The test account is able to authenticate via a username and password.

## Acceptance Criteria
- If the hospital user provides valid login information, they are allowed to submit newborn demographic data.
- If the hospital user does not provide valid login information, any attempt to submit newborn demographic data results in an access denied error.

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the story here.

### Engineering
- [ ] Threat model updated
- [ ] Code refactored for clarity and no design/technical debt
- [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies.
- [ ] Source code is merged to the main branch.
- [ ] Unit test coverage of our code >= 90%
- [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer.
- [ ] Build process updated
- [ ] Feature toggles created and/or deleted.  Document the feature toggle.
- [ ] Source code documentation created when the code is not self-documenting.
- [ ] API documentation generated
- [ ] Code quality checks passed
- [ ] Security & privacy gates passed
- [ ] Load tests passed
- [ ] Documentation and diagrams created or updated
- [ ] API(s) are versioned
- [ ] Debug logging

**Comment by JohnNKing** [comment]
Closing -- authentication should be implicit to the other stories that make up this epic.
