### ISSUE TITLE
Complete Impact section for ADRs

### ISSUE THREAD

**Issue by tjohnson7021** [CDCgov/trusted-intermediary#1247]
# DevEx/OpEx

Fill "Impact" sections for previously completed ADRs to allow for adequate revision in the future, and to help developers who are new to the project understand the thought context when the decision was made. 

**Note:**  Please keep in mind - We have chosen to PR a few (like 5 max) ADRs at a time for cleaner review.

## Tasks

- [x] Complete **Impact** section for previously completed ADRs .
  - [x] (new)[PR created for 001-006](https://github.com/CDCgov/trusted-intermediary/pull/1446) ........... [(Old closed PR with edits)](https://github.com/CDCgov/trusted-intermediary/pull/1416)
    - [x] **PR has been reviewed & merged**
    - [x] 002 - @tjohnson7021 
    - [x] 003 - @tjohnson7021 
    - [x] 004 - @tjohnson7021 
    - [x] 005 - @tjohnson7021 
    - [x] 006 - @tjohnson7021 
  - [x] [PR created for 007-011 ](https://github.com/CDCgov/trusted-intermediary/pull/1456)
    - [x] **PR has been reviewed & merged**
    - [x] branch: [devex/1247-add_impact_sections_to_adrs_007-011](https://github.com/CDCgov/trusted-intermediary/tree/devex/1247-add_impact_sections_to_adrs_007-011)
      - [x] 007 - @tjohnson7021 
      - [x] 008 - @tjohnson7021 
      - [x] 009 - @tjohnson7021 
      - [x] 010 - @tjohnson7021 
      - [x] 011 - @tjohnson7021 
  - [x]  [PR created for 012-016](https://github.com/CDCgov/trusted-intermediary/pull/1627)
    - [x] **PR has been reviewed & merged**
    - [x] branch: [devex/1247-add_impact_sections_to_adrs_012-016](https://github.com/CDCgov/trusted-intermediary/tree/devex/1247-add_impact_sections_to_adrs_012-016)
      - [x] 012 - @tjohnson7021 
      - [x] 013 - @tjohnson7021 
      - [x] 014 - [`014-keys.md`](https://github.com/CDCgov/trusted-intermediary/blob/main/adr/014-keys.md) 
      - [x] 015 - [`015-project-structure.md`](https://github.com/CDCgov/trusted-intermediary/blob/main/adr/015-project-structure.md) - Not sure of the Impacts of the specified project structure...
      - [x] 016
  - [x] [PR created for 017-019](https://github.com/CDCgov/trusted-intermediary/pull/1628)
    - [x] **PR has been reviewed & merged**
    - [x] branch: [devex/1247-add_impact_sections_to_adrs_017-019](https://github.com/CDCgov/trusted-intermediary/tree/devex/1247-add_impact_sections_to_adrs_017-019)
      - [x] 017
      - [x] 018
      - [x] 019
  

## Additional Context

The updated ADR template can be found here: https://github.com/CDCgov/trusted-intermediary/blob/main/adr/001-architecture-decision-records.md

**Comment by tjohnson7021** [comment]
Not sure if or how to structure an _Impact_ section for [`014-keys.md`](https://github.com/CDCgov/trusted-intermediary/blob/main/adr/014-keys.md)

**Comment by tjohnson7021** [comment]
[`015-project-structure.md`](https://github.com/CDCgov/trusted-intermediary/blob/main/adr/015-project-structure.md) - Not sure of the Impacts of the specified project structure...

**Comment by brick-green** [comment]
@tjohnson7021 Is this actively in progress? If not, can we move it to the sprint backlog?

**Comment by tjohnson7021** [comment]
> @tjohnson7021 Is this actively in progress? If not, can we move it to the sprint backlog?

I had moved it back on the wrong board (zenhub). Thanks!
