### ISSUE TITLE
ReportStream HL7 HTTP Response

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1249]
# Backlog Task

As Epic, so that I know orders were received successfully by ReportStream, I need an HL7 MSA returned in the HTTP response body.

## Completion Criteria

- [x] Ochsner has confirmed orders can be submitted to ReportStream without error (due to the lack of an ACK being returned via the HTTP body)

## Tasks

- [x] Work with ReportStream to ensure shared understanding of customer needs (https://cdc.sharepoint.com/:w:/r/teams/OLSS_ETOR_ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BE5A9FAE6-8CD2-4C99-A757-F027562C1737%7D&file=ReportStream%20ETOR%20ACK%20Requirements.docx&action=default&mobileredirect=true)
- [x] Await and/or support ReportStream's implementation of this new capability
- [x] Enable this capability in Staging for Ochsner
- [x] Confirm with Ochsner that they can now submit orders without error

## Other Notes

- https://github.com/CDCgov/prime-reportstream/issues/16394
- https://github.com/CDCgov/prime-reportstream/issues/15731

**Comment by JohnNKing** [comment]
Likely to be replaced by https://github.com/CDCgov/prime-reportstream/issues/15731

**Comment by JohnNKing** [comment]
@JohnNKing Updates needed to make ready for refinement. We probably still want this for tracking of ReportStream's work and testing.

**Comment by JohnNKing** [comment]
I'm told this should be working in staging. Next step is to verify with Ochsner that this is behaving as expected.

**Comment by JohnNKing** [comment]
Closing out. Ochsner confirmed this is working as expected.

**Comment by JohnNKing** [comment]
Completed by https://github.com/CDCgov/prime-reportstream/issues/16394
