### ISSUE TITLE
Add functionality to SFTP service to place file into correct destination directory based on outcome

### ISSUE THREAD

**Issue by jcrichlake** [CDCgov/trusted-intermediary#1254]
# DevEx/OpEx

Currently the zip file stays in the `unzip` folder regardless of success, failure, or partial failure. We need to move the file to one of the various destination folders (Name of these is TBD I believe)

## Tasks

- [x] Add code
  - [x] Failure (decided against have to failure subfolders as it may lead to confusion)
  - [x] Success
- [x] Add comments to constants
- [x] Rename variables and method 
- [x] Add unit test
- [x] Test locally

## Additional Context

Add any other context or screenshots about the work here.
