### ISSUE TITLE
Implementation: Automated TI <> RS tests

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1255]
# Story
As a Intermediary Developer, so that I can prevent potential errors in the message flow, I need to identify potential problems in RS before they go into Production.

## Pre-conditions
- [x] We can use RS staging environment 

## Acceptance Criteria
- [x] Sample messages are scheduled to be submitted to RS staging daily
- [x] Tests are scheduled to run daily
- [x] All tests pass on the sample messages 

## Tasks

We have decided to implement [Solution 5.1](https://lucid.app/lucidchart/99226c79-94de-4beb-ad59-c991cafb6874/edit?beaconFlowId=1231B6134643FE5D&invitationId=inv_c49420a6-95f5-434a-8e88-049ae0477ba9&page=0_0#)

- [x] Document expectations for final HL7 in order to create test assertions: [documented here](https://www.notion.so/flexion-cdc-ti/ETOR-Flow-Output-Data-Requirements-1467b8b22cd7406e8ef27cc677d4a79b?pvs=4)
- [x] Set up senders and receives in RS staging for the full test flow (we can reuse the existing sender and receiver for the `RS => TI => RS` part of the flow)
  - [x] Sender (Github Action) for first leg of the flow
    - [x] Create org settings for sender: `automated-staging-test-sender`
    - [x] Create public/private key pair for sender (use RSA 2048)
      - [x] Ask Peter to add the private key to a Github Secret 
  - [x] Receiver (Azure Blob Storage) for second leg of the flow 
    - [x] Create org settings for receiver: `automated-staging-test-receiver`
    - [x] Define `jurisdictionalFilter`: use receiver routing filter. Choose a unique ID for this
    - [x] Load Azure Blob Storage credentials in RS
  - [x] Create and merge PR in RS [[PR](https://github.com/CDCgov/prime-reportstream/pull/15725)]
- [x] Create Azure Blob Storage account and a bucket to store final HL7 files [[PR](https://github.com/CDCgov/trusted-intermediary/pull/1280)]
- [x] Create Github Workflow, to be run daily, that will submit a request to RS. It will send all HL7 files downloaded from an Azure storage account container [[PR](https://github.com/CDCgov/trusted-intermediary/pull/1274)]
- [x] Integration test framework in TI
  - [x] Retrieve final HL7 files from Azure container 
  - [x] Retrieve initial HL7 files from repository
  - [x] Determine a reliable way to pair initial and final HL7 files
  - [x] Implement Assertion Rule Engine
    - [x] Create a definitions file with all the assertions documented
    - [x] Implement rules engine that will load the definitions file and apply assertions to an output message (and its input message) 
    - [x] Design and implement an HL7 statement parser and evaluator that will validate the rules in the definitions file
    - [x] Add unit tests
  - [x] Create test that will loop through all the input/output HL7 message pairs and run the assertions using the rules engine
  - [x] Add workflow to schedule test runs
- [x] Add sample HL7 files to test in specified folder above. Update receiver (MSH-6.2) to match filter in RS org settings
- [x] Add documentation in readme on how to set-up a test file in examples/Test/Automated/ and how to set-up assertions
- [ ] Add assertions for remaining transformations
  - ~[ ] `convertToOmlOrder`: when `input.MSH-9.2 = 'O01'`, then `output.MSH-9.2 = 'O21'`~ (we don't have the capability to have conditions on input files yet. Leaving for future improvement)
  - [x] `ucsdOruUpdateReceivingFacilityWithOrderingFacilityIdentifier`: `ORC-21.10 = MSH-6`
  - [x] `ucsdOruRemoveObservationRequests`: `OBR-4.1 = '54089-8'`
  - [ ] `ucsdOruMapLocalObservationCodes`: ?
  - ~[ ] `ucsdOruRemoveAccessionNumberObservation`: UCSD ORU and `OBX-3.4 = '99717-5'` and `OBX-3.6 = 'L'`. then remove OBX~ (we need an assertion like `OBX-3.4 != '99717-5' or OBX-3.6 != 'L'`, but we don't have the capability at the moment)

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- Create an automated end to end test(s) that includes specific callouts to/from TI/RS while making sure SFTP ingestion functionality is accounted for.
