### ISSUE TITLE
CA Transform: Observation local code to LOINC or PLT

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1277]
# Story
As UCSD, so that I can ingest an NBS result message, I need observations provided by CDPH to use codes that I support.

## Pre-conditions
- We've identified a list of observation codes used by the lab (CDPH) that the hospital (UCSD) cannot support.

## Acceptance Criteria
- [x] Observations containing codes not supported by UCSD are transformed to include appropriate LOINC or PLT codes.
- [x] The appropriate LOINC or PLT codes are added to OBX-3.1/2/3. 
- [x] If there is no LOINC/PLT code mapped, the transformation should not happen (OBX-3 should be left as-is) 
- [x] A failed mapping lookup should be logged
- [x] The values of OBX-3.4/5/6 are retained

## Key Notes
- We need some flexibility regarding the specific codes to be used. We're waiting on feedback regarding a proposed set codes. However, we likely can't afford to delay starting on the implementation.
- Draft mappings: https://docs.google.com/spreadsheets/d/1YwWB5Q7A68z1BTPEkcADq2Z_ZxA6xHcY/edit?usp=drive_link&ouid=112818441652199013680&rtpof=true&sd=true
- SDAT Lucid https://lucid.app/lucidchart/b8b498f3-b665-450c-bf3b-867051fe2a7f/edit?invitationId=inv_f91745cd-513b-404a-969a-a97a4ffbaa92&page=0_0#

## Outcomes ( Demoable behaviors/End to end Test scenarios )
- A CDPH HL7 with local codes has all local codes mapped to LOINC/PLT codes for the UCSD HL7 
- A CDPH HL7 with an unmapped local code should log the failed mapping and still send the message 

### Research questions to be answered
- [x] Are any of our translated codes PLT? [Yes, updated spreadsheet has which are LOINC vs PLT]
- [x] If so, what does OBX-3.3 need to look like? "LN", "PLT", something else? ["LN" and "PLT"]
- [x] Will there only be one LOINC or PLT code that a local code maps to? (i.e. always a 1:1 mapping) [Yes]
- [x] What is the expectation if we don't have a mapping for a local code?  Should we fail the message in TI or still send on?
  - [x] Discussed in 9/13 Standup: Let's have the message go through for now in this scenario; it seems to be the least-bad option 
- [x] We are planning that if we receive a message with local code in OBX-3.4 through .6 and there is content in any of OBX-3.1 through .3, we will not do anything with OBX-3. Does that logic sound appropriate to you? [Yes]
- [x] Need to know if the values of OBX-3.4/5/6 should be removed (from the ACs above) [No, we will retain 4/5/6]
- [x] Need the final mappings for all codes (still waiting on 5 from the mapping tab of the spreadsheet)

###  Phase 0 (Boundaries)
- [x] Create transformation class skeleton
- [x] Define structure of the mapping definition classes

###  Phase 1 (Expand system capabilities)
- [x] Create mappings for all local codes
- [x] Implement the transformation class
- [x] Tests
  - [x] One local observation code mappable to LOINC @jbiskie 
  - [x] One local observation code mappable to PLT @jbiskie 
  - [x] One local observation code not found in the mapping @jbiskie 
  - [x] One LOINC observation code, no mappings needed. Test when in 1/2/3 or 4/5/6 @jbiskie 
  - [x] Message with multiple observation codes of all types @jbiskie 
  - [x] Resource not available @jbiskie 
  - [x] When mappable code and .1, .2, or .3 is filled in on the initial message -> no mapping needed @jbiskie 
- [x] Configure the transformation in `transformation_definitions.json`
- [x] Logging

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by luis-pabon-tf** [comment]
Do we have example data with all the drafted local codes? I am only able to find examples for 3 of the OBX messages we're translating.

**Comment by jbiskie** [comment]
@dbgolson 

Are we to assume that the local codes from CDPH will always be in OBX-3.4 through 6? 
`OBX|1|CE|^^^99717-32^Adrenoleukodystrophy deficiency newborn screening interpretation^L|`

Or is it possible they may appear in OBX-3.1 through 3?
`OBX|1|CE|99717-32^Adrenoleukodystrophy deficiency newborn screening interpretation^L|`

**Comment by dbgolson** [comment]
@jbiskie - CDPH will always send their local codes in OBX-3.4 through OBX-3.6

**Comment by jorg3lopez** [comment]
Update:
- Started SDAT procedure to breakdown tasks

**Comment by jbiskie** [comment]
@dbgolson - We generated a few questions that we need to have answered. Could you take a look at the "Research questions" section at the top?

**Comment by dbgolson** [comment]
- Are any of our translated codes PLT?

**All CDPH local codes will either be mapped to PLT codes or LOINC codes in OBX-3.1, associated PLT or LOINC code descriptions in OBX-3.2, and associated code system IDs of either 'PLT' or 'LN' in OBX-3.3 **

- If so, what does OBX-3.3 need to look like? "LN", "PLT", something else?

**The lookup table with codes and descriptions will need to be updated to also include the appropriate code system in OBX-3.3 (i.e., either 'LN' or 'PLT') **

- Will there only be one LOINC or PLT code that a local code maps to? (i.e. always a 1:1 mapping)

**Yes, always a 1:1 mapping**

-  What is the expectation if we don't have a mapping for a local code?  Should we fail the message in TI or still send on?

****@JohnNKing** will need to weigh in on this. **

- We are planning that if we receive a message with local code in OBX-3.4 through .6 and there is content in any of OBX-3.1 through .3, we will not do anything with OBX-3. Does that logic sound appropriate to you?

**Yes, that seems the best approach. **

- Need to know if the values of OBX-3.4/5/6 should be removed (from the ACs above)

**No, we should retain the original values found in OBX-3.4/5/6 **

- Need the final mappings for all codes (still waiting on 3 according to the draft spreadsheet)

**The PLT or LOINC codes and their descriptions are not finalized.  CDPH is reviewing the codes and descriptions we have suggested to them AND once confirmed, we will need to seek establishment of a couple of them as NEW PLT codes. That said, the "offending" local codes which will be mapped to the agreed upon PLT or LOINC codes are known and listed in the spreadsheet. Are we able to have "placeholder" values what to map to? **

**Comment by jbiskie** [comment]
Update - we've started on the happy path implementation. Some code is written for the transform to get the ideas down. Still needs work though. Open to contributions from anyone.

**Comment by jorg3lopez** [comment]
Find out if PLT has a coding system.
<img width="1122" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXpWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7c38327fa357936ad006709a5eb2f374434ac5c/image.png" alt="image.png" />

**Comment by jbiskie** [comment]
Seems GitHub didn't like the link above. Here's another screenshot of a PLT code in fhir. Note it does not have a "system" node like LOINC and local codes do.

![image](https://github.com/user-attachments/assets/225adf6f-fb20-4aac-b186-93dfba61369b)

**Comment by jbiskie** [comment]
Update:

First 2 unit tests are written along with initial implementation of the transform. If you're working over the weekend, the transform needs some additional work to pass the unit tests and the mapping hashtable needs the remainder of the entries.

**Comment by jbiskie** [comment]
@dbgolson - The mapping for 99717-50 to PLT3275 has the following suggested description (OBX-3.2):

> "Mucopolysaccharidosis type II [Interpretation] in DBS by Sequencing
>
>This name should be updated to IDS gene mutations found [Identifier] in Dried Bloodspot by Molecular genetics method Nominal"

Confirming we should use the latter description, "IDS gene mutations found [Identifier] in Dried Bloodspot by Molecular genetics method Nominal"?

**Comment by jbiskie** [comment]
Update:

Tests are all written. We have one final issue to address in the transform, which is discussed in the PR. After that, we just have the transformation definition to add, and then I think we can get the PR ready for review.

Note there are still outstanding questions with some of the PLT code mappings. They are mapped to "REQUEST PLT" for now. If those are going to take a while, we can complete the transformation work here and then circle back and do a small PR to update the final mappings.

**Comment by JohnNKing** [comment]
The new PLT codes are available in https://docs.google.com/spreadsheets/d/1YwWB5Q7A68z1BTPEkcADq2Z_ZxA6xHcY/edit?gid=1378330894#gid=1378330894
