### ISSUE TITLE
Submit Generic Order data for an individual order

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#13]
# Story

## Sentence

As a Hospital,
In order to process newborn screening lab tests,
I need to be able to submit an individual order.

## Preconditions
- One fake healthcare provider supported

## Acceptance Criteria

- [ ] Healthcare providers can request/transmit an order (a REST API is sufficient; no UI required)
- [ ] The order must include: patient identifier & test type
- [ ] The order data and the current system date must be stored for near-term use (e.g. minutes, not days)
- [ ] The submitter should receive an appropriate acknowledgment if the order was stored successfully (e.g. HTTP 200)
- [ ] Orders must be transmitted securely (e.g. via TLS), except in local development environments

## Tasks

- [x] ADRs.
  - [x] Java
  - [x] Gradle - @halprin 
  - [x] Groovy and Spock for testing - @halprin 
  - [x] OeSA - @halprin 
- [ ] Linting (Sonar?).
- [ ] DAST scanning
- [x] End-to-end tests - @halprin
- [ ] CD to at least a Flexion Azure environment
  - [ ] Terraform
  - [ ] Blue/green strategy
- [ ] API documentation (OpenAPI)
- [x] OeSA application context - @halprin @jorg3lopez 
- [ ] OeSA dependency injection - @halprin @jorg3lopez @tjohnson7021 
- [x] Code coverage check for at least 90%. - @halprin 
- [x] Add domain plugin architecture - @halprin
- [x] Add domain endpoint
- [ ] SBOM generation
- [x] Learn more about FHIR - @halprin
- [ ] Logging framework - @jorg3lopez 

## Additional Context

Add any other context or screenshots about the story here.

### Engineering
- [ ] Threat model updated
- [ ] Code refactored for clarity and no design/technical debt
- [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies.
- [ ] Source code is merged to the main branch.
- [ ] Unit test coverage of our code >= 90%
- [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer.
- [ ] Build process updated
- [ ] Feature toggles created and/or deleted.  Document the feature toggle.
- [ ] Source code documentation created when the code is not self-documenting.
- [ ] API documentation generated
- [ ] Code quality checks passed
- [ ] Security & privacy gates passed
- [ ] Load tests passed
- [ ] Documentation and diagrams created or updated
- [ ] API(s) are versioned
- [ ] Debug logging

**Comment by halprin** [comment]
Overall I like this.

There's a decent number of technical requirements in here.  I like most of them, but do they belong in the acceptance criteria?  To be clear, I think they are mostly good and I want to keep them, but should they reside in the acceptance criteria section?  🤷🏻‍♂️

Notice I said "most" and "mostly" above.  I have questions about two of them.

> The system provides a way to allow for debugging

I don't like that one.  It seems too much of a bare minimum that we get no value by listing it out.

> Orders must be transmitted securely (e.g. via TLS)

This one will be environment specific.  When the application runs locally, it won't support HTTPS.  When deployed, then yes, it should be HTTPS.  So, is this something we should keep even if it is context specific?  Or do we assume all the acceptance criteria are applied when in a deployed environment?  I'm used to A/C being applicable regardless of environment, hence me asking.

**Comment by JohnNKing** [comment]
Thanks for the feedback @halprin !

I think for many of the AC, they could instead be rolled into our Definition of Done.

I'll also clarify the TLS one -- my intent is this wouldn't need to apply to local dev environments.

**Comment by JohnNKing** [comment]
Closing in favor of https://github.com/CDCgov/trusted-intermediary/issues/76
