### ISSUE TITLE
Documentation: Update incident severity level documentation to take scope/impact into consideration.

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1313]
# DevEx/OpEx

Documentation: Update incident severity level documentation to take scope/impact into consideration.

## Tasks

- [x] Draft initial section [section](https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0?pvs=4#2ebd9908485e403496ce35abd03ed782) to include considerations.
- [x] Brainstorm grid sections based on impact and scope to determine severity.
- [x] Create [grid](https://lucid.app/lucidchart/a4fe5145-dc92-4e18-bba4-672b2cfe9616/edit?viewport_loc=-2376%2C-1051%2C4208%2C2121%2C0_0&invitationId=inv_1a685b6d-1b05-40ac-9800-a0b12d5b6bc8).
- [x] Get feedback (possibly during engineering block). 
- [x] Ask ISSO for security incident related documentation
  - [x] Email sent
  - [x] Response received
- [x] Implement response into grid and possibly update communication section.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by pluckyswan** [comment]
Jeff and Sam reviewed and approved.

**Comment by pluckyswan** [comment]
Scheduled discussion during engineering block with Sylvie.

**Comment by pluckyswan** [comment]
Decided to create a grid based on scope and impact to determine severity. A small group will create grid then get feedback.

**Comment by pluckyswan** [comment]
Gained feedback on adding privacy and security to impact column. Will brainstorm with John King for ideas.

**Comment by saquino0827** [comment]
I have re-reviewed both documents since the updates. Looks good to me.

**Comment by pluckyswan** [comment]
Further review needed based on this [thread](https://flexion.slack.com/archives/C06CP7E3NAF/p1727121625917829)

**Comment by pluckyswan** [comment]
Still awaiting response from ISSO.

**Comment by pluckyswan** [comment]
Sam reviewed and approved.

**Comment by sfradkin** [comment]
This looks good @pluckyswan

**Comment by pluckyswan** [comment]
Peter reviewed and approved
