### ISSUE TITLE
Documentation: Update incident log template to indicate that the severity level can be figured out later.

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1314]
# DevEx/OpEx

Update process documentation that the time log is the most important thing to fill out and the other fields can be figured out later.

## Tasks

- [x] Update beginning of document to have a note for 
- [x] Include a second note for the severity level 
- [x] Get changes reviewed 

## Additional Context

Add any other context or screenshots about the work here.

**Comment by csweet92** [comment]
I'm happy to take this one

**Comment by jcrichlake** [comment]
There's some confusion on which of the 2 templates we as a team want to use.  I've added this as an item for our engineering block on Wednesday.
