### ISSUE TITLE
Update hurl scripts. 

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1322]
# DevEx/OpEx

Update hurl scripts to automatically update the MSH headers to be a value such that we wouldn't really direct messages to a real partner.

## Tasks

- [x] Update hurl script.
  - [x] Figure out how to scramble correct fields.
  - [x] Figure out how to not commit scrambles.
  - [x] Scramble.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by pluckyswan** [comment]
Asked Jorge for info. on handling file path separators in TI.

**Comment by pluckyswan** [comment]
PR is out for approval.

**Comment by pluckyswan** [comment]
Based on feedback, we don't want to scramble it but want to make it a Flexion receiver.

**Comment by pluckyswan** [comment]
Will work Basillo on Mon to continue working on issue.
