### ISSUE TITLE
Ensure we have the flexion.simulated-hospital and flexion.simulated-lab senders/receivers in RS production.

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1323]
# DevEx/OpEx

Ensure we have the flexion.simulated-hospital and flexion.simulated-lab senders/receivers in RS production.

## Tasks

- [x] Check with Ott if flexion.simulated-hospital and flexion.simulated-lab are both senders and receivers in RS prod.
   - [x] Get them added if not.
- [x] Check if we have a private and public key are generated. 
   - [x] Senders: we generate, give public key to Ott
   - [x] Receivers: Ott generate, give public key to us
- [x] Add keys to KeyBase
- [x] Update secrets in KeyVault
- [x] Test
## Additional Context

Add any other context or screenshots about the work here.

**Comment by pluckyswan** [comment]
Asked Ott to add them to RS prod. Awaiting reply.

**Comment by pluckyswan** [comment]
Ott has added them to prod and is generating a key pair for the receivers.

**Comment by pluckyswan** [comment]
Successfully tracked message from RS to TI to RS to receiver.
