### ISSUE TITLE
Final Security Approval Before Go-Live

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#1341]
# Backlog Task

Check if there are any last, remaining, security approvals before we go live with our initial partners.

## Completion Criteria

- [x] We've requested final approval from our ISSO.
- [x] Either we've gotten final approval or an additional backlog task is created to track the work we need to do to get final approval.

## Tasks

- [x] Ensure our TI threat model is up-to-date. - @halprin 
- [x] Ensure our SFTP Ingestion threat model is up-to-date. - @halprin 
- [x] Create (or update) an architecture diagram.
- [x] Send an e-mail to our ISSO with the threat models, architecture diagram, mention the scanning we're doing, mention that we're operating under the ReportStream ATO, and mention we want to work in production with a state/hospital partner at the end of October.  Ask if there is any additional security approvals we need before going live with the state/hospital partner.

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by halprin** [comment]
E-mail has been sent.  Waiting to hear back.

**Comment by halprin** [comment]
Heard back.  No additional security approvals are required before going live in production with our first partner.

As an aside, our ISSO mentioned that they are thinking of splitting the ATO into one ATO per component of PRIME _in the future_.
