### ISSUE TITLE
What data is considered sensitive and how can it be shared 

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1350]
# DevEx/OpEx

What data is considered sensitive?  E.g. is the report ID sensitive?  No, but there are other things that could be clarified.  Document this.

Combining with:
Documentation: how can we share PII and PHI?  Where is it allowed?  It is not allowed in Slack, Google Drive.  It is allowed in Keybase, but should be deleted after use.  What about our computers, Teams, Citgo/Citrix?  This is a tricky conversation with our ISSO and others.  The last thing we need is for Keybase to be removed and RS is still able to use it.  This is a political conversation.  Perhaps only select folks should pick-up this issue.

10/02/2024 Planning: Scope story down to communication with ReportStream to TI communication. We may not be allowed to use keybase for anything PII/PHI related. We likely need a conversation with our ISSO to sort this out.

## Tasks

- [x] Is "sensitive" and "PII/PHI" interchangeable? (what about secrets / passwords / private keys?)
- [x] Identify which transport mechanisms can be used? (e.g. keybase, encrypted emails)
- [x] What does ReportStream's PIA (privacy impact assessment) allow for? (also for reference: https://www.cdc.gov/grants/additional-requirements/ar-25.html)
- [x] Identify which fields in an HL7 message are considered PII/PHI

## Additional Context

Add any other context or screenshots about the work here.

**Comment by jcrichlake** [comment]
I think this would require clarity from someone on the product team

**Comment by basiliskus** [comment]
This document may have relevant information (page 23): https://drive.google.com/file/d/1XonNNujHxnhKVBhnM3ra15xW3R5E0mXd/view

**Comment by brick-green** [comment]
HHS guidance for PHI https://www.hhs.gov/hipaa/for-professionals/special-topics/de-identification/index.html#safeharborguidance

**Comment by brick-green** [comment]
Started [this documen](https://cdc.sharepoint.com/teams/OLSS_ETOR_ReportStream/_layouts/15/doc.aspx?sourcedoc=%7B44505c39-71cd-42f4-b636-4fe06dd38a1c%7D&action=edit)t to list out the safe harbor rules.

Also contact Chris at ReportStream via slack asking if they have any information on the use of Keybase

**Comment by brick-green** [comment]
Still waiting on response from Jason, pinged again today. 

Continuing to work on the doc. Got good reviews from Daniel and James. Started working on OML

**Comment by brick-green** [comment]
Completed OML lists in safe harbor doc. Still waiting on a response from Jason.

**Comment by scleary1cs** [comment]
Jeffery Stordahl asked about status on the CA SME call on 12/04/2024.

**Comment by brick-green** [comment]
Blocking and adding to backlog

Waiting for guidance from Manjula. He is currently trying to understand if Jason Blackburn is the correct contact for the question about approved tools for PHI sharing.

**Comment by brick-green** [comment]
Manjula is till asking the CDC for official guidance. But in the meantime he said that TI can align with RS in using keybase to exchange PHI.
