### ISSUE TITLE
Reorganize the documentation to maximize ease of use

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1352]
# DevEx/OpEx

Reorganize the documentation to maximize ease of use; one-page guide to use during the incident?.

## Tasks

- [x] Review the existing incident response documentation in Notion (https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0)
- [x] Decide what should be included in the abbreviated incident response guide
- [x] Where will the guide exist in Notion? How will people find it? (e.g. reference from other incident docs; Slack; etc)
- [x] Create a summary or one-page guide for incident commander use

## Additional Context

Add any other context or screenshots about the work here.

**Comment by csweet92** [comment]
Currently just waiting to hear back from RS on how to transfer an incident

**Comment by jbiskie** [comment]
Added a summary/one-page guide task following our Gameday 3 exercise

**Comment by csweet92** [comment]
One-pager work in progress: https://www.notion.so/flexion-cdc-ti/One-Pager-Process-WIP-1275955365f5807f864af7788c1f57f8

**Comment by pluckyswan** [comment]
I like it.

**Comment by jbiskie** [comment]
The changes look great, and it's a lot easier to find things from a glance. Making it collapsed drop downs helps so much.
