### ISSUE TITLE
Adding AI to our PR review process

### ISSUE THREAD

**Issue by saquino0827** [CDCgov/trusted-intermediary#1357]
# DevEx/OpEx

- Using software similar to AWS CodeGuru or a Github Action script with 3rd party libraries prompting Azure OpenAI or whatever LLM, we can us AI to review and leave comments as a Senior Developer.

## Tasks

- [x] Look into options available for AI PR reviews. (We decided on [PR-Agent](https://qodo-merge-docs.qodo.ai/) 
- [x] Implement an option of your choice
   - [x] Add GitHub action
   - [x] Add secrets
- [x]  Fix Github Manual PR Agent Triggers on PR Comments
  - [x]  Remove Auto-Labelling from the PR Agent (The settings don't seem to turn this off but we're okay with that)
  - [x]  Check out the PR Agent settings and see what we may need/want to give a try. See docs [here](https://qodo-merge-docs.qodo.ai/tools/) and also the [configuration file](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml)
  - [x] Remove this trigger: pull_request_review_comment
  - [x]  Set up a time in engineering block to review this, sometime next week. Maybe next Friday (10/18)
- [x] Test PR Agent with example PR in TI and SFTP Ingestion Service
  - [x] Example PR for TI (should include comments on code changes, etc.) - ran against https://github.com/CDCgov/trusted-intermediary/pull/1333
- [x] Create new Cards for the following:
  - [x] Migration of Azure LLM hosting to the new Flexion Repository [here](https://github.com/flexion/pr-assistant)
  - [x] SFTP Ingestion Service Setup with PR Agent.
    - [x] Add this task to this Card: Example PR for SFTP Ingestion Service (should include bad code changes, etc.)

## Additional Context

Add any other context or screenshots about the work here.

**Comment by saquino0827** [comment]
PR-Agent could be a good choice for this: https://qodo-merge-docs.qodo.ai/

**Comment by saquino0827** [comment]
We were able successfully get the [PR-Agent](https://qodo-merge-docs.qodo.ai/) to review our [PR](https://app.zenhub.com/workspaces/cdc-ti-633de70d939f6c00155f3722/issues/gh/cdcgov/trusted-intermediary/1405). 
We will present this at engineering block tomorrow to get feedback. 
Two suggestions from @halprin were:
1. Instead of Terraforming Azure OpenAI in our TI Repo, get a new flexion repo created that can have the terraform for Azure OpenAI and all it's required Azure Resources. Then, have the PR-Agent in the TI Repository call the Flexion Azure OpenAI instead.
2. Configuration changes to remove auto labelling.

**Comment by saquino0827** [comment]
1) Review all the settings for PR Agent. For example, the PR Agent is set to `Auto-Describe` where the Agent adds it's own description. We discussed that we may not want this to be built automatically because we want our engineers to provide their own description. We want to encourage our engineers to think for themselves rather than rely on AI.
2) We're planning on moving the LLM specific hosting to a flexion wide repo, instead of only within the TI Azure Account.

**Comment by saquino0827** [comment]
Created Issue [#1431](https://app.zenhub.com/workspaces/cdc-ti-633de70d939f6c00155f3722/issues/gh/cdcgov/trusted-intermediary/1431) from the set of tasks.

**Comment by saquino0827** [comment]
New Issue created here #1433
