### ISSUE TITLE
Verify that we have postgresSQL backups turned on

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1358]
# DevEx/OpEx

Verify that we have postgresSQL backups turned on

## Tasks

- [ ] Send message through Report stream.
- [ ] Verify id makes it into the TI metadata database
- [ ] Roll back database
- [ ] Verify message doesn't return from metadata api endpoint
- [ ] Roll Forward
- [ ] Verify message shows up again

## Additional Context

https://flexion.slack.com/archives/C055XTF22B0/p1726510976587729
