### ISSUE TITLE
Feature: Complex Map for args For Transformation Engine

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/trusted-intermediary#1366]
# DevEx/OpEx

Currently, the transformation_definitions.json file is capable of passing a Map<String,String> as a parameter to the translations objects. Because of this constraint, we are unable to pass more complex types of maps and this forces us to add the complex map/data as part of the transformation class.

## Propose Solution
Add the feature of passing a complex map (Map<String,Object>) from the transformation_definitions.json file. This feature will make it possible to inject the data via the transformation_definitions.json, adding flexibility, reusability, and generalizing our transformations.

## Tasks

- [x] Add Map<String,Object> args to Interfaces
  - [x] CustomFhirTransformation
  - [x] HappyPathCustomTransformationMockClass
- [x] Add Map<String,Object> to TransformationRuleMethod
- [x] Add Map<String,Object> to TransformationRule
- [x] Add Map<String,Object> args to all available transformations
- [x] Refactor
  - [x] failing tests cases
  - [x] null check transformations that use args
 - [x] Test coverage of new code

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Additional e2e tests created
  - [x] Additional RS e2e assertions created in the `rs-e2e` project for any new transformations.  Includes improvements to the assertion code required to make the new assertions
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

**Comment by jorg3lopez** [comment]
[PR ](https://github.com/CDCgov/trusted-intermediary/pull/1362)has been merged!
