### ISSUE TITLE
Azure Alerts for Errors

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1379]
# Story
As a _, so that _, I need _.

High Severity: 
As a developer, I need CDC-TI (TI & SFTP) 5xx status codes alerted on, so that we can begin an incident. 
Created [Azure Alerts for Errors - 5xx status codes#1394](https://github.com/CDCgov/trusted-intermediary/issues/1394) added to Production Stage 3 Epic.

As a developer, I need CDC-TI (TI & SFTP) Log Errors alerted on (threshold?),  so that we can begin an incident. 
Created [Azure Alerts for Errors - Log Errors alerted on (threshold?)#1395](https://github.com/CDCgov/trusted-intermediary/issues/1395) added to Production Stage 3 Epic.

As a developer, I need CDC-TI 4xx status codes to be alerted on after a threshold,  so that we can begin an incident. 
Created [Azure Alerts for Errors - 4xx status codes#1396](https://github.com/CDCgov/trusted-intermediary/issues/1396) added to Production Stage 3 Epic.

As a developer, I need to know if Azure is down, so that we can begin an incident. 
Created [Azure Alerts for Errors - Azure is down#1397](https://github.com/CDCgov/trusted-intermediary/issues/1397) added to Production Stage 3 Epic.

As a developer, I need to know if our services are down/offline, so that we can begin an incident. 
Created [Azure Alerts for Errors - services are down/offline#1398](https://github.com/CDCgov/trusted-intermediary/issues/1398) added to Production Stage 3 Epic.

Medium/low severity: 
As a developer, I need to be alerted on high CPU usage (CDC TI, SFTP, & database), so that we can begin investigation. 
Created [Azure Alerts for Errors - high CPU usage (CDC TI, SFTP, & database)#1399](https://github.com/CDCgov/trusted-intermediary/issues/1399) added to Production Stage 4 Epic.

As a developer, I need to be alerted on high API response times, so that we can begin investigation. 
Created [Azure Alerts for Errors - high API response times#1400](https://github.com/CDCgov/trusted-intermediary/issues/1400) added to Production Stage 4 Epic.

As a developer, I need to be alerted on high memory usage (CDC TI, SFTP, & database), so that we can begin investigation. 
Created [Azure Alerts for Errors - high memory usage#1401
](https://github.com/CDCgov/trusted-intermediary/issues/1401) added to Production Stage 4 Epic.

Note: Consider severity levels - "world is on fire" 

## Pre-conditions
- [ ] *Assumptions of prior or future work that's out of scope for this story*

## Acceptance Criteria
- [ ] *Required outcomes of the story*

## Tasks
- [ ] Alerting for errors for Queue Startup Failure in the Ingestion Service due to missing configuration (I forget which  configurations caused this silent failure so some initial triage will be necessary). If this is no longer an issue, this alert can be ignored. **Alerting on errors may be good enough to cover this scenario**

### Research

- [ ] *Research work needed to complete the story*
- [ ] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [ ] *Engineering work needed to complete the story*
- [ ] Foundational: *Technical runway work to support this and future efforts*

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- Azure Alerts for Errors
- Example Error for Ingestion Service Function App Errors:
  - `FunctionAppLogs
| where TimeGenerated > ago(1d)
| where Message contains "error" or Message contains "exception"
| project TimeGenerated , AppName , Message , _ResourceId`
   - The Function App log scope needs to be updated to include the function app

**Comment by scleary1cs** [comment]
Azure Alerts for Errors.

**Comment by scleary1cs** [comment]
This was part of #1372 (but pulled out)

**Comment by saquino0827** [comment]
We categorized scenarios in the card's description. This can be our baseline and we can add/edit/remove scenarios as we discover them.
