### ISSUE TITLE
Use `MSH-11` to identify test messages in staging and production environments

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#1387]
# DevEx/OpEx

After an internal discussion, we decided `MSH-11` (ProcessingId) is the right candidate to identify two types of test messages: automated/scheduled and manually triggered. Following to the [HL7 specs](http://terminology.hl7.org/CodeSystem/v2-0103), we decided to use `T` (Training) for manual tests and `N` (Non-Production Testing) for automated tests.

## Tasks

- [x] Update TI test files to use either `T`, `D` or `N` in `MSH-11`
  - `T`: test files to be sent to partners and sent manually
  - `D`: test files not to be sent to partners and sent manually
  - `N`: test files not to be sent to partners and sent by scheduled task
- [x] Update RS org settings to route test messages
- [x] Make sure RS accepts the values we plan to use for MSH-11
- [x] Remove workaround to rewrite MSH in hurl script
- [x] Add documentation in readme
- [x] Add documentation in ADR
- [x] Update routing settings in staging
- [x] Ask Ott to update routing settings in prod

## Additional Context

Add any other context or screenshots about the work here.

**Comment by basiliskus** [comment]
I'm waiting for feedback from SMEs to decide on the routing filters for `MSH-11` to use in production

**Comment by basiliskus** [comment]
We'll discuss the `MSH-11` value for internal testing tomorrow in engineering block and I'm expecting to make a final decision there. After that, we'll ask RS to update the org settings in prod

**Comment by basiliskus** [comment]
We've made a decision to use `D` for internal testing and `T` for partner testing. We have [this PR in RS](https://github.com/CDCgov/prime-reportstream/pull/16064) with the latest changes that is up for review. I've also asked Ott to update the settings in production

**Comment by basiliskus** [comment]
The `flexion` org settings have been applied to production
