### ISSUE TITLE
Azure Alerts for Errors - Log Errors

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1395]
# Story
As a developer, I need CDC-TI (TI & SFTP) Log Errors alerted on (threshold?), so that we can begin an incident.

## Pre-conditions
- [ ] *Assumptions of prior or future work that's out of scope for this story*

## Acceptance Criteria
- [x] TI: Log Alerts for errors are set up and tested in a non production environment
- [x] SFTP: Log Alerts for errors are set up and tested in a non production environment

## Tasks
- [x] Create alert in TI
- [x] Create alert in SFTP

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Additional e2e tests created
  - [x] Additional RS e2e assertions created in the `rs-e2e` project for any new transformations.  Includes improvements to the assertion code required to make the new assertions
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- This story came out of #1379, and #1380.

**Comment by jherrflexion** [comment]
Created branch: implement-and-configure-detailed-azure-log-alerts-with-comprehensive-monitoring-and-notifications-for-optimizing-azure-log-alerts-management-and-tracking-in-some-environments

**Comment by jherrflexion** [comment]
Merged for TI. Waiting to see a successful alert somewhere.

**Comment by halprin** [comment]
I think we needed to add one more additional check to the SFTP Ingestion Service log query to not alert for logs that come in from the pre-live slot.  I think Sylvie has the details on this.

Also, it looks like the DoD wasn't completed.  We need to work through the DoD before we move this to the done column.

Moving this back into in-progress.
