### ISSUE TITLE
Azure Alerts for Errors - 4xx status codes

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1396]
# Story
As a developer, I need CDC-TI 4xx status codes to be alerted on after a threshold, so that we can begin an incident.

## Pre-conditions
- [ ] *Assumptions of prior or future work that's out of scope for this story*

## Acceptance Criteria
- [x] 4XX alerts are configured for all non-pr environments and have been tested in the TI application in a deployed environment
- [x] 4XX alerts are configured for all non-pr environments and have been tested in the RS SFTP ingestion service in a deployed environment

## Tasks
- [x] Set up 4xx Azure Alerts in the TI Application in all non PR environments
  - [x] Test 4xx azure alert in TI.
- [x] Set up 4xx Azure Alerts in the RS SFTP Ingestion Service in all non PR environments
  - [x] Test 4xx azure alert in TI.
  - [x] Make sure to remove **test400** endpoint from the **RS SFTP Ingestion Service**

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Additional e2e tests created
  - [x] Additional RS e2e assertions created in the `rs-e2e` project for any new transformations.  Includes improvements to the assertion code required to make the new assertions
  - [x] Tested alert triggers and resolutions in non production environments.
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- This story came out of #1379, and #1380.

**Comment by saquino0827** [comment]
For this alert I believe we need the following:
- A metric alert (Azure monitor has metrics that monitor http status codes)
- The alert is stateful (See: https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-overview#types-of-alerts)
- For the interval and lookback period I'm not 100% sure yet.

**Comment by saquino0827** [comment]
We attempted creating a list of variables for the `lifecycle ignore changes` block. 
```
cdc_tags = 
set(
    "business_steward",
    "center",
    "environment",
    "escid",
    "funding_source",
    "pii_data",
    "security_compliance",
    "security_steward",
    "support_group",
    "system",
    "technical_steward",
    "zone"
 )
  ignore_tags = [for tag in cdc_tags : "tags[\"${tag}\"]"]
```
With 

```
lifecycle {
    ignore_changes = local.ignore_tags
  }
```

And we get the following error
```
 Error: Invalid expression
│
│   on ../../template/alert.tf line 111, in resource "azurerm_monitor_metric_alert" "azure_4XX_alert":
│  111:     ignore_changes = local.ignore_tags
│
│ A static list expression is required.
```

We'll revert back to the old lifecycle ignore changes list as there doesn't seem to be a better way to do this.
We **could** add it to the provider of azurerm but that would ignore all the tags in every azure resource and I think we use those tags in **some** resources.

**Comment by saquino0827** [comment]
The PR was merged and the alert was tested in the internal environment. The alert successfully fired and resolved itself correctly as well.

**Comment by halprin** [comment]
The DoD isn't done.  Moving back into Review column.

**Comment by saquino0827** [comment]
Created a new ticket to triage 4xx alerts popping up and going through DoD now to make sure this card is completed.
