### ISSUE TITLE
Rename sentSubmissionId  and receivedSubmissionId  to inboundMessageId  and outboundMessageId

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#1404]
# DevEx/OpEx

High level description of what what needs to be improved.

## Tasks

- [x] Rename sentSubmissionId to outboundReportId
  - [x] Rename tests
  - [x] Rename variables
  - [x] Rename functions
- [x] Rename receivedSubmissionId to inboundReportId
  - [x] Rename tests
  - [x] Rename variables
  - [x] Rename functions
- [x] Add comment clarifying `recordId` is actual a reportId
- [x] Possibly add an ADR or clarifying comments on first instance of variables
- [x] Confirm cleanup

## Additional Context

https://flexion.slack.com/archives/C055XTF22B0/p1704911117020269
