### ISSUE TITLE
ETOR Issue Coordination

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1412]
## Spike Goal
While an external facing SLA is currently blocked, our team should share a mutual understanding with ReportStream on what constitutes an urgent/catastrophic failure versus ongoing operational service requests.

## Notes
- Would partners use the RS Help Desk to notify us of issues?
- How would we notify RS and/or the Help Desk regarding incidents we identify?
- What training or docs would we need to provide to the Help Desk?

## Timebox
2 weeks

## Tasks

- [x] Find out how we ask for help from RS when we're in the middle of an incident. - @halprin
  - [x] Document this in the incident process.
- [x] Find out how we formally send RS an incident that should be owned by them. - @halprin
  - [x] Document this in the incident process.

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
We consider this body of work complete, and follow on work will be complete in #1580 , #1577 , #1448 , #1447.
