### ISSUE TITLE
Integration Tests for NTE Segment Mapping

### ISSUE THREAD

**Issue by tjohnson7021** [CDCgov/trusted-intermediary#1424]
# DevEx/OpEx

Add an integration test in RS and RS-E2E to make sure the NTE segment is mapped correctly. The test has to be FHIR to HL7. 

## Tasks

- [x] ~Add a test for RS~ Integration test for OML already exists. 
- [x] Add a test for RS-E2E
  - [x] Add an assertion definition
    - [x] ~Possibly need to reconfig how assertion works to allow multiple segments~ We only need to test that the first segment exists. 

## Additional Context
- https://flexion.slack.com/archives/C055XTF22B0/p1710274890926099
- See bug report for more context on what to test: https://github.com/CDCgov/prime-reportstream/issues/13626

Add any other context or screenshots about the work here.

**Comment by pluckyswan** [comment]
After some research with Gilmore and Sylvie, it was discovered that there is an existing integration test for OMLs within RS already. Therefore, only the TI RS-E2E was needed.
