### ISSUE TITLE
New LA Card ID Format

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1428]
# Backlog Task

Test ReportStream and ETOR Intermediary order processing using specimen IDs that match the new, temporary card ID format (e.g. APHL00000001; instead of just an 6 or 7 digit number)

## Completion Criteria

- [x] Confirm whether a 12-14 character alpha-numeric card ID via OBX-5 will be parsed and transformed successfully by ReportStream
- [x] If this value isn't accepted for the card ID currently, then we've captured a follow-up story to add this capability.

## Tasks

- [x] If possible, clarify what the OBX data type is that conveys the card ID and if this would ever change based upon the card in question. (Note: NM would be a problem)
- [x] Test order submission with a datatype of "ST" and value of 'APHL00000001'

## Other Notes

- @JohnNKing Confirm with @JScott-JMC that this would be provided via OBX-5

**Comment by JohnNKing** [comment]
Currently blocked awaiting a sample ORM message from the hospital.

**Comment by JohnNKing** [comment]
@JohnNKing Confirm with @JScott-JMC that this would be provided via OBX-5

**Comment by JScott-JMC** [comment]
This will come in an OBX as an ST data type.

@JohnNKing @basiliskus

**Comment by JohnNKing** [comment]
> This will come in an OBX as an ST data type.

Thanks @JScott-JMC !

**Comment by GilmoreA6** [comment]
ReportStream doesn't automatically apply the HL7 V2 character limits so the length isn't a concern from the conversion standpoint. Regardless, the length limit is 199 characters. When testing with the de-identified ORM messages using an OBX with a ST data type and OBX-5 value of APHL00000001 the value is correctly carried.

**Comment by GilmoreA6** [comment]
MSH|^~\&|13^1.2.840.114350.1.13.286.2.7.2.695071^ISO|4169|Natus.LA.STAG^2.16.840.1.114222.4.3.26.3.2|Louisiana Office of Public Health Laboratory^2.16.840.1.114222.4.3.22.17.1.1|20241115111935|739|OML^O21^OML_O21|31|T|2.5.1|||AL|NE
PID|1||123456^^^MRN^MRN||TEST^B BOY BEAKER||20241108110000|M||2054-5^Black or African-American^CDCREC|123 MAIN ST.^^LAFAYETTE^LA^70503^US^P^^LAFAYETTE||(555)555-5555^P^PH||ENGLISH|Single|||||TEST^BEAKER^MOM|HISPANIC||Y|2|||||N
NK1|1|TEST^BEAKER^MOM|Mother|1202 Coolidge St.^^LAFAYETTE^LA^70503^US|(557)559-5559^^PH
PV1|1||^1234^4567||||||||||||||1184608010^DREWITZ^TROY^U.^^^^^NPI^^^^NPI
ORC|NW|APHL00000001^EPC||APHL00000001|||||20241113125406|739^BEAKER^PHLEBOTOMIST||1184608010^DREWITZ^TROY^U.^^^^^NPI^^^^NPI|^^^^^^^^OLGH LABOR AND DELIVERY|(504)391-8896||||OCH155315^OCH155315|||OCHSNER LAFAYETTE GENERAL MEDICAL HOSPITAL^D^^^^OCHSNER HEALTH SYSTEM^XX^^^30100|1214 COOLIDGE BLVD^^LAFAYETTE^LA^70503-2621^US^B^^LAFAYETTE|(337)289-7991^^PH|120 OCHSNER BLVD^SUITE 360^GRETNA^LA^70056^^C|||||I|VERBAL WITH
OBR|1|APHL00000001^EPC|APHL00000001^Beaker|54089-8^Newborn screening panel American Health Information Community (AHIC)^LN^^^^2.72||20241113125400|20241113131841|||739^BEAKER^PHLEBOTOMIST|Lab Collect|||||1184608010^DREWITZ^TROY^U.^^^^^NPI^^^^NPI|(504)391-8896|||193988||||Lab||||||||||||20241113125400
OBX|1|ST|57714-8^Gestational Age (Weeks + Days)||382||||||F|||20241113125402|||||||||||||||QST
OBX|2|ST|82312-0^Infant Blood Transfusion?||Yes||||||F|||20241113125402|||||||||||||||QST
OBX|3|DT|62317-3^Date of Transfusion||20241108||||||F|||20241113125402|||||||||||||||QST
OBX|4|ST|67704-7^All Feeding Since Birth||Human Milk \T\ Formula||||||F|||20241113125402|||||||||||||||QST
OBX|5|ST|PLT3280^Name of Formula(s)||Enfomil||||||F|||20241113125402|||||||||||||||QST
OBX|6|ST|12345^Unique Bar Code||APHL00000001||||||F|||20241113125402|||||||||||||||QST
SPM|1|^APHL00000001&Beaker||BLOOD^Blood||||BLOOD^Blood|||||||||20241113131841|20241113131842||Y

**Comment by GilmoreA6** [comment]
Using example test message above with the currently unmerged ReportStream OML updates results in the value being carried in all possible applicable fields: ORC-2, ORC-4, OBR-2, OBR-3, OBX-5, SPM-2
