### ISSUE TITLE
 SFTP Ingestion Service Setup with PR Agent

### ISSUE THREAD

**Issue by saquino0827** [CDCgov/trusted-intermediary#1431]
# DevEx/OpEx

TI has been setup with the [codium](https://qodo-merge-docs.qodo.ai/) AI PR Agent. Using similar configurations, we need to add the PR Agent to our SFTP Ingestion Service. The main adds were these two files: [.pr-agent.toml](https://github.com/CDCgov/trusted-intermediary/blob/main/.pr_agent.toml) and this github [workflow](https://github.com/CDCgov/trusted-intermediary/blob/main/.github/workflows/pr_agent.yml). 

## Tasks

- [x] SFTP Ingestion Service Setup with PR Agent.
   - [x] Add .pr-agent.toml to the main branch of this repo and merge it in first. 
   - [x] Add github workflow
   - [x] Example PR for SFTP Ingestion Service (should include code change review, etc. See this example [PR](https://github.com/CDCgov/trusted-intermediary/pull/1333))
   - [x] Tested on this closed [PR](https://github.com/CDCgov/reportstream-sftp-ingestion/pull/176)

## Additional Context

Add any other context or screenshots about the work here.

**Comment by saquino0827** [comment]
Added the same settings for the PR Agent from the TI Repo and tested it in the PR listed under Tasks
