### ISSUE TITLE
Migration of Azure LLM hosting to the new Flexion Repository

### ISSUE THREAD

**Issue by saquino0827** [CDCgov/trusted-intermediary#1433]
# DevEx/OpEx

Migration of Azure LLM hosting to the new Flexion Repository [here](https://github.com/flexion/pr-assistant)

## Tasks

- [ ] Set up the new [repo](https://github.com/flexion/pr-assistant). 
  - [ ] @halprin what are the details that we need for setting up a new repo?
- [ ] Azure Account Setup
  - [ ] Flexion Azure Account.
    - [ ] Add a PR Assistant Azure Open AI resource.
    - [ ] Deploy an Open AI LLM.
  - [ ] Set up terraform with the new Azure Account, resource groups, Open AI and AI Deployment LLM, etc.
    - [ ] Add Open AI resource for the TI Team.
    - [ ] Get Keys and URL to TI Team as Secrets.

## Additional Context

Add any other context or screenshots about the work here.
