### ISSUE TITLE
Upgrade Javalin to Latest Version

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/trusted-intermediary#1441]
# DevEx/OpEx

We are currently using Javalin version `6.3.0`. This version uses versions of jetty-server and jetty-http that were flagged by Snyk of having sucurity vulnerabilities. In order to keep using javalin and by pass the vulnerabilities, we pulled the jetty dependencies directly.

## Tasks

- [ ] Update to latest version of Javalin
- [ ] Make sure the jetty-server and jetty-http vulnerabilities have been addressed
- [ ] Delete the direct dependency of the jetty bom from the app/build.gradle file

## Additional Context
Ref: 
Ticket #1437
 PR #1440 

Add any other context or screenshots about the work here.
![Image](https://github.com/user-attachments/assets/0e3c74ff-cd4b-4924-90eb-d85e0e3ffcdd)

**Comment by jorg3lopez** [comment]
It was decided to ignore the vulnerabilities from Jetty. This ticket will be closed as there is no changes to revert.
