### ISSUE TITLE
Triage 4xx Errors in Staging

### ISSUE THREAD

**Issue by saquino0827** [CDCgov/trusted-intermediary#1517]
# DevEx/OpEx

- Our 4xx alerts are being triggered. We suspect it's part of ReportStream's Healthcheck

## Tasks

- [x] Look into what is triggering our 4xx alerts in staging. - @halprin, @GilmoreA6, @JeremyIR 
- [x] Test fix in TI Internal. - @halprin, @GilmoreA6, @JeremyIR
- [x] Merge PR with final fix.

## Additional Context

Add any other context or screenshots about the work here.
