### ISSUE TITLE
Identify Personas for User Journeys

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#152]
# Research

Identifying personas for user journeys (for hospitals, for labs, other entities)

## Completion Criteria

- [ ] A list of personas have been shared with the team.

## Tasks
Potential players - Hospital staff
- [x] Nurse Clinician / Nurse
- [ ] Charge Nurse
- [ ] Lab Professional
- [ ] Pediatric or Neonatal Nurse Practitioner
- [ ] Administrator or Support Staff member
- [ ] Hospital NBS Coordinator
- [ ] Neonatologist
- [ ] Primary Care Provider

## Additional Context

Add any other context or screenshots about the work here.

**Comment by JohnNKing** [comment]
Deferring until we have a hospital partner.
