### ISSUE TITLE
CA Game Day Exercises Part III

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1521]
# DevEx/OpEx

To ensure we're ready to support unexpected issues in production, as a team we need to run through some sample scenarios.

Potential Exercises:

LIMS / EHR offline
TI or RS offline
Inter-service auth failure
Invalid message contents
Corrupt zip file via SFTP
Changed SFTP encryption key

## Completion Criteria 
- [ ] We've completed at least two exercises:
  - [ ]  **Description of surprise failure here**.

## Tasks (these need to be verified)
- [] Determine the scenarios
- [] Determine when this exercise will take place
  - [] Get support from the RS team
- [] Document an intro to the session
- [] Submit sample data for scenarios
- [] Staging configuration change to support one of the scenarios
- [] Conduct a blameless post-mortem
- [] Conduct a retro for the whole exercise
 

## Additional Context
Team has a number of new members since the previous CA Game Day Exercises
[#1132](https://github.com/CDCgov/trusted-intermediary/issues/1132).

Additionally, we can verify all of the updates made to our [incident management process](https://www.notion.so/flexion-cdc-ti/Incident-Management-0695bd694b1b42eaa2b6a55756aa7e13).

**Comment by JohnNKing** [comment]
The exercise was initiated today and resolved in short order.

**Comment by JohnNKing** [comment]
Based on action items from https://www.notion.so/flexion-cdc-ti/Post-mortem-Gameday-3-1365955365f58010b556e4000c23daa6:
- _How does ReportStream classify production support issues, incidents, etc?_
  - I've created #1577 (@brick-green, @GilmoreA6 )
- _Shorten/summarize process doc to be easier to consume in the heat of battle_ 
  - I suspect this aligns with the intent of #1352 (@csweet92, @jbiskie, @somesylvie)
