### ISSUE TITLE
Notify the engineering team when the `Automated Staging Test - Run integration tests` action fails

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#1528]
# DevEx/OpEx

We need the engineering team to be notified when the `Automated Staging Test - Run integration tests` action fails. The workflow is in `.github/workflows/automated-staging-test-run.yml`

## Tasks

- [x] Look into adding people to notify using `CODEOWNERS` file
- [x] Look into adding a Slack Webhook to use in the workflow and notify the `cdcti-alerts-nonprod` slack channel
- [x] Loo into sending an email on test failure in the workflow
- [x] Decided to go with the Slack Webhook. Need to ask someone with Flexion Slack admin access to create it

## Additional Context

https://flexion.slack.com/archives/C055XTF22B0/p1728079599129939
