### ISSUE TITLE
Rollback plan

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1530]
# Backlog Task

Create, document, and publish (in Notion) a Rollback plan. This needs to be accomplished before go live with CA. 

## Completion Criteria

- [ ] A documented procedure to recover from a failed release
- [ ] A copy is exported to SharePoint 
- [ ] Rollback plan has been tested and verified to work
- [ ] This plan should be reference in the incident management process

## Tasks

- [ ] What tasks need to be done to fulfill the completion criteria?

## Other Notes

-Rollback plan should encompass TI and SFTP ingestion service.  Should also include rollback a database migration if necessary.  

-The Rollback plan should have documentation of when fail forward versus rollback is best.

**Comment by GilmoreA6** [comment]
Starting draft rollback plan here: https://www.notion.so/flexion-cdc-ti/Rollback-Plan-draft-1355955365f5809c9b8fce92817ddc62

**Comment by GilmoreA6** [comment]
Restoring db from snapshot will be tested as part of #1537

**Comment by GilmoreA6** [comment]
A change was made to "/etor/databaseMigrations/metadata.yml" and applied to the internal db. When performing the "Rollback DB" action using options"./etor/databaseMigrations/root.yml" as the directory, an unexpected migration was rolled back. The changeset that was rolled back was from "/etor/databaseMigrations/azure.yml" instead of "/etor/databaseMigrations/metadata.yml".

![Image](https://github.com/user-attachments/assets/9ce96982-c1d9-45c8-9513-f13aa784f43b)

The issue is stemming from the fact that "runAlways: true" is in changeset 1 in azure.yml so it will always be the last changeset applied. Therefore it will always be the newest so we will have to account for it if we are rolling back from root.

##todo discuss with group whether rolling back from root matters
