### ISSUE TITLE
Review incident management plan

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1534]
# Backlog Task

The entire incident management plan should be reviewed from start to finish.  Make sure it is cohesive. There are still outstanding detail that need to beed determined regarding handoff to RS, but beside that all other details should be reviewed. 

## Completion Criteria

- [ ] All comments (aside from above RS comment) should be resolved
- [ ] A new export has been posted to SharePoint 
- [ ] The incident management process documentation is cohesive

## Tasks

- [ ] What tasks need to be done to fulfill the completion criteria?

## Other Notes

- Can be done with Claire and SMEs

**Comment by halprin** [comment]
Starting to take a look at this.

**Comment by csweet92** [comment]
@halprin As a part of this story could you also review the new incident process doc (https://www.notion.so/flexion-cdc-ti/Process-Doc-2-0-WIP-1275955365f5800081e8d73a91189d80)? The only thing missing is the RS handoff documentation
