### ISSUE TITLE
Make the automated test fail if any of the input or output files are not parsed correctly

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#1536]
# DevEx/OpEx

This could just mean that in `HapiHL7FileMatcher.mapMessageByControlId` we need to bubble up the exception instead of just logging an error and continuing

## Tasks

- [x] Bubble up exceptions, add context, and let automated test fail
- [x] Throw exception if failed to find matching input or output
- [x] Add custom exception `HapiHL7FileMatcherException`

## Additional Context

https://flexion.slack.com/archives/C055XTF22B0/p1727717357268009
