### ISSUE TITLE
Data retention policy

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1542]
# Backlog Task
Data retention policy is documented

## Completion Criteria

- [ ] Documentation has been published to Notion
- [ ] A copy of the documentation has been exported to SharePoint
- [ ] This should encompass both TI and SFTP ingest 

## Tasks

- [ ] What tasks need to be done to fulfill the completion criteria?

## Other Notes

- Any other notes to help clarify this task for the team
