### ISSUE TITLE
Dashboarding Requirements for LA

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1551]
# Design or Research

Understand, document and publish what the our partner (LA) would like to see with a visual dashboard.

## Acceptance Criteria
- [ ] What are the partners expecting?
- [ ] What does the APHL dashboard look like?
- [ ] Where should this dashboard live (RS, CDC.gov)?
- [ ] Will the dashboards contain any sensitive information (RS auth)?
- [ ] What data is wanted/needed in this dashboard?
- [ ] What research was done for AL regarding dashboards?
- [ ] Partner Metadata as an input to Dashboards?

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by scleary1cs** [comment]
What are the partners expecting?
What does the APHL dashboard look like?
Where should this dashboard live (RS, CDC.gov)?
Will the dashboards contain any sensitive information (RS auth)?
What data is wanted/needed in this dashboard?
What research was done for AL regarding dashboards?
Partner Metadata as an input to Dashboards?

**Comment by scleary1cs** [comment]
Spike will be created based on these requirements.
