### ISSUE TITLE
Refactor the rs.sh, ti.sh and epic.sh scripts in /scripts to reduce code duplication

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#1566]
# DevEx/OpEx

Refactor the rs.sh, ti.sh and epic.sh scripts in /scripts to reduce code duplication and make it more reusable for future endpoints that require JWT auth

## Tasks

- [x] Rename variables:
  - [x] `client` => `sender`
  - [x] `client_id` => `sender_org`
  - [x] `client_sender` => `sender_name`
- [x] Refactor `rs.sh`, `ti.sh` and `epic.sh` scripts to reduce code duplication

## Additional Context

https://flexion.slack.com/archives/C055XTF22B0/p1730473225668469
