### ISSUE TITLE
[SPIKE] Process to detect and notify staff of messages that failed to be delivered

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1572]
## Spike Goal
Define our process for detecting ETOR messages that arrive in ReportStream that are not sent out. Once detected, how should staff be notified.

## Timebox
Time allocated (2 FTE days)

## Tasks

- [x] Review current queries (see link in notes)
- [x] Identify options for notification from RS app insights
- [x] Create requirements document for RS

## Acceptance Criteria

- [x] Design document detailing the options for notification
- [x] SRD sent to RS

## Notes

For queries previously identified that may provide a way to do this, see: https://www.notion.so/flexion-cdc-ti/ETOR-Error-Scenarios-18b29090371b40c6b01408b1148f4158#6db88d06ddac4163a54ea6664ccee34c

**Comment by brick-green** [comment]
[Failure points](https://docs.google.com/document/d/1NGYP4XyZhnidKXnYLDcW-Cavs53OFksTvomBPLIfUM8/edit?tab=t.0)

**Comment by GilmoreA6** [comment]
starting notes here: https://www.notion.so/flexion-cdc-ti/ReportStream-Message-Observability-1505955365f580cfa85cce1edce26f6c

**Comment by GilmoreA6** [comment]
Meeting with RS on 12/6 - RS is amenable to the idea of allowing a separate action group to send specific alerts to Flexion slack alerts channel

**Comment by GilmoreA6** [comment]
Creating Product Requirements document as per RS request to send to RS DevOps Team and Arnej. This will be combined with a ticket on RS board to formalize getting permission to add a new action group

**Comment by GilmoreA6** [comment]
@brick-green @JohnNKing could you give the requirements google doc linked in a ticket a review?

**Comment by brick-green** [comment]
I don't have permissions to make comments on that google doc. What is the purpose of adding "ITEM_FILTER_FAILED" azure alerts?

**Comment by JohnNKing** [comment]
> [@brick-green](https://github.com/brick-green) [@JohnNKing](https://github.com/JohnNKing) could you give the requirements google doc linked in a ticket a review?

@GilmoreA6 The doc, especially the requirements section, looks great to me. I don't really have any comments or questions.

**Comment by GilmoreA6** [comment]
@brick-green I fixed the permission so anyone with the link can edit. As far as alerting on ITEM_FILTER_FAILED, currently we have no filters that are not jurisdictional filters so this alert *shouldn't* ever fire for us but I thought it was worth putting in there for future cases, but we could remove it.
