### ISSUE TITLE
Understand ReportStream Incident Classification

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1577]
# Backlog Task

Understand how ReportStream classifies production support issues, incidents, etc., so we can decide how/if we want to align with them and so we can communicate effectively with them. 

## Completion Criteria

- [ ] Our incident process has been updated to better align with how ReportStream classifies production incidents or issues.

## Tasks

- [x] Understand how RS defines incidents
- [x] Communicate with RS to understand how they classify incidents

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by jbiskie** [comment]
Notes from chat with @brick-green and @GilmoreA6:
- I only remember an incident being declared in the event that PHI was leaked otherwise everything was considered a production support issue
- The only other times we declared incidents were when RS was down entirely and unable to process any messages

**Comment by brick-green** [comment]
Tie in ticket #1572 to inform full picture of RS incidents and the responsibility of TI after azure alerts/events are accessible

**Comment by brick-green** [comment]
Reviewed and moving to done. I don't see any additional work let here.
