### ISSUE TITLE
Lucid.gov Migration

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1579]
# Backlog Task

Identify and move our shared lucidchart artifacts from our lucid [shared folder](https://lucid.app/documents#/documents?folder_id=309484051) to our lucid.gov [shared folder](https://lucidgov.app/documents#/teams/500606554?folder_id=502754423).

## Completion Criteria

- [ ] Artifacts to move have been identified and moved.
- [ ] Watermarks have been added to the old files on all tabs.
- [ ] All comments have been resolved

## Tasks

- [ ] Gain access to the lucid.gov shared folder for the team
- [ ] Complete [Lucid.gov Migration](https://docs.google.com/spreadsheets/d/1PRJBsjwLlLUqF43Ez-L6iXvI4ZDywevg0pH00ZT-G-U/edit?gid=0#gid=0) spreadsheet.

## Other Notes

- Any other notes to help clarify this task for the team
