### ISSUE TITLE
Reschedule Automated Tests to make sure they run after working hours

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#1582]
# DevEx/OpEx

They're currently scheduled to run around midnight UTC, but our teams' working hours are between Pacific Time and Eastern Time. We should reschedule the tasks to run closer to midnight PT/ET. We also need to make sure all tasks run in the same day, regardless of the time zone

## Tasks

- [x] Pick an appropriate time (e.g. 12am PT)
- [x]  Update the scheduled tasks in the github workflows
  - [x] `.github/workflows/automated-staging-test-run.yml`
  - [x] `.github/workflows/automated-staging-test-submit.yml`
- [x] Update the time zone in `rs-e2e/src/main/java/gov/hhs/cdc/trustedintermediary/rse2e/AzureBlobFileFetcher.java` 
- [x] Make sure the blob fetching, organization and cleanup for Automated Tests run as expected  (check `AzureBlobFileFetcher` and `AzureBlobOrganizer`)

## Additional Context

https://flexion.slack.com/archives/C055XTF22B0/p1731456428910039
