### ISSUE TITLE
Update RS REST Transport for Ochsner Epic

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/trusted-intermediary#1593]
We need to verify the requirements to connect with Ochsner's Epic. Ott previously had start a draft of changes to RS's REST transport here https://github.com/CDCgov/prime-reportstream/pull/13922. We need to validate which of those changes still need to be made.

## Completion Criteria

- [ ] We can send a message to Ochsner's Epic staging/test environment from ReportStream staging and it is successfully received

## Tasks

- [ ] Obtain documentation regarding Epic's REST endpoint for Ochsner
- [ ] Make any changes required to RS Rest Transport
- [ ] Change transport settings for Ochsner in RS staging to send to Ochsner staging/test env
- [ ] Confirm message is successfully received in Ochsner's staging/test env

## Other Notes

- (https://github.com/CDCgov/prime-reportstream/pull/13922) is a PR that Ott started back in April 2024 that contains changes that may be needed for Ochsner

**Comment by brick-green** [comment]
Blocked on completion of security questionnaire
