### ISSUE TITLE
CA: Document Account Unlock Process

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1611]
# Backlog Task

Document the process of unlocking out SFTP service account if it becomes locked (e.g. due to excessive logins)

## Completion Criteria

- [ ] We've documented the process for unlocking our CDPH SFTP account.
- [ ] We've documented which scenario(s) can cause our CDPH SFTP account to become locked.

## Tasks

- [ ] What tasks need to be done to fulfill the completion criteria?

## Other Notes

- Any other notes to help clarify this task for the team
