### ISSUE TITLE
PHL Interview Guide

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#162]
# Backlog Task

PHL Interview Guide

## Completion Criteria

- [ ] The guide is available for the team to read and use in interviews with PHLs

## Tasks

- [ ] Create an interview guide for future PHL interviews
- [x] Build questions for CDC/Utah staff interview
- [x] Build questions for AZ PHL interview

### Other notes

- Synthesize data we've collected so far to inform this interview guide
