### ISSUE TITLE
Refactor HapiHL7Message.getName to return more useful name

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#1621]
# DevEx/OpEx

It's currently returning the type of HL7 message, but we want a name that can be used as identifier. An identifier name could be the file name, MSH-10 or something else. We want to use a name that we can use to log a message that had an issue

## Tasks

- [x] Refactor to better isolate the Hapi HL7 library from the code
- [x] Remove `HapiHL7Message.getName` and add `HapiHL7Message.getIdentifier` to return MSH-10 
- [x] Use MSH-10 in the failure logs for the Automated Test

## Additional Context

Add any other context or screenshots about the work here.
