### ISSUE TITLE
Fill in mapping for OML/ORM

### ISSUE THREAD

**Issue by brick-green** [CDCgov/trusted-intermediary#1626]
# Backlog Task

Following the OML/ORM mapping work completed by RS there remains a number of fields that unmapped.

- PID-2 - Missing because PID-2 is "Backwards Compatible" field in 2.5.1

- PID.19 and PID.20 - are deprecated in the HL7v2.7 and NIST HL7v2.5.1 specs. Further, the HAPI v2.7 model has set both # fields to NULLDT.

- ORC-7 - Missing because ORC-7 is "Backwards Compatible" field in 2.5.1

- OBR-27- Missing because OBR-27 is "Backwards Compatible" field in 2.5.1

- SPM-35 - Missing because SPM-35 does not exist in 2.5.1

## Completion Criteria

- [ ] Above fields can be mapped into FHIR and back out to HL7 for OML
- [ ] Above fields can be mapped into FHIR and back out to HL7 for OML

## Tasks

- [ ] What tasks need to be done to fulfill the completion criteria?

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by JohnNKing** [comment]
ORC-7 not available in HL7 v2.7. May well be an issue with the other fields.

**Comment by basiliskus** [comment]
Need to check latest OML mapping in RS to confirm fields are missing

**Comment by GilmoreA6** [comment]
[output.txt](https://github.com/user-attachments/files/18381941/output.txt)

**Comment by basiliskus** [comment]
Differences based on last RS version and Gilmore's input OML above

- Missing segments:
  - GT1
- Missing fields
  - PID
    - PID-2
    - PID-12
    - PID-19
  - ORC
    - ORC-7
  - OBR
    - OBR-27
  - OBX (67704-7)
    - OBX-5.3.2
    - OBX-5.4
    - OBX-5.5
  - SPM
    - SPM-35
- A few empty fields (delimiters without values following)

**Comment by JohnNKing** [comment]
Thanks @basiliskus ! That matches what I'm seeing. I'll pull this back into the Refinement column for tomorrow -- specifically to ask the team about adding PID-12 to this scope. For the Feeding Type OBX (67704-7), I'll create a new story. It seems to be related to fields that repeat.
