### ISSUE TITLE
Test UCSD Production Connection

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/trusted-intermediary#1637]
# Story
As UCSD, so that I can review and provide patient care based on NBS findings, I need sample result messages sent by ReportStream to appear in my EHR production environment.

## Pre-conditions
- [x] production certificate has been created following steps at https://www.notion.so/flexion-cdc-ti/Epic-EHR-Onboarding-Steps-9a4cd71b2e4b49558013eda9df87427a#ab21d25b2f5248ef8d038780a5343ff0

## Acceptance Criteria
- [ ] An ORU message sent by ReportStream to the UCSD receiver appears in their production EHR environment.
- [x] Transmission uses TLS 1.2 or greater and a strong cipher

## Tasks
- [ ] Confirm successful authentication to Epic's OAuth endpoint for UCSD production
- [ ] Verify receipt of messages
- [ ] Verify result is filed correctly in the healthcare provider view of Epic
  - [ ] Verify micro/mu character appears correctly within the test result observations

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*
