### ISSUE TITLE
Document Shared Services for APHL Collaboration

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#164]
# Backlog Task

Contribute to shares services documentation within APHL's Confluence.

## Completion Criteria

- [x] We've completed our contributions to APHL's Confluence (**due to Kim by Thursday, 2/23**)

## Tasks

- [x] Review Requirements Gathering Doc (see https://aphlinformatics.atlassian.net/wiki/spaces/IR/pages/1819803983/Reference+Materials+-+Program+Management)
- [x] Document any steps or services that we think are missing from the MVP
- [x] Document any additional decisions that need to be made or that the group needs to come to agreement on
- [x] Document any applicable services that already exist
