### ISSUE TITLE
Update Local TI/RS Setup Scripts

### ISSUE THREAD

**Issue by saquino0827** [CDCgov/trusted-intermediary#1658]
# DevEx/OpEx

- Update our `scripts/README.md` and local `setup-reportstream.sh` to choose configurations based on what local instance is running for TI and RS (gradle vs docker).

## Tasks

- [x] Update `scripts/README.md` with ToC
- [x] Update `scripts/README.md` with more clarity
- [x] `scripts/README.md/setup/setup-reportstream.sh` to now pick `localhost:8080` or 'host.docker.internal:8080' based on if you have the **TI AND RS docker images** running locally
