### ISSUE TITLE
NBS Turnaround Time Metrics

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#168]
# Research

Quality Metrics Around hospital timeliness and quality Research for PHLs

1.  Are there challenges for PHLs with tracking hospital timeliness and quality?
2.  Could aggregated ADT data potentially solve challenges / pain points for PHLs (related to timeliness and quality tracking)?

14(?) states are tracking this type of information.
HIEs/QHINs could be a potential line of investigation for this.
Would we be able to get access to APHL's report card stats for per-PHL NBS turn-around time?

## Completion Criteria

- [ ] we are at least 80% confident that ADT data aggregation for PHLs would be viable and useful for PHLs in relation to hospital timeliness metric calculations
- [ ] we will know this is not viable if: a number of states/PHLs do not see any value in ADT as a solution

## Tasks

- [ ] Research reporting needs (hospital quality metric reporting) for a set of states (relating to data needs that could be a value add with demographic data)

**Comment by JohnNKing** [comment]
Discussed in 5/9 refinement -- needs work before it can be brought into refinement again

**Comment by JohnNKing** [comment]
Closing in favor of #322
