### ISSUE TITLE
Internal Incident Management Process

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#176]
# Backlog Task

Develop an internal incident response process.

## Completion Criteria
- [x] Our incident response process has been documented somewhere accessible to the team and the CDC.

## Tasks

- [x] Ask for incident management process from CMS QPP program. - @halprin 
- [x] Ask for incident management process from CMS MPSM program. - @halprin 
- [x] Brainstorm what we want in an incident management process. - @jcrichlake, @halprin
- [x] Map out incident process 
- [x] [Incident log template](https://www.notion.so/flexion-cdc-ti/Incident-Log-Template-68c8d06a94244e8782304238ff40c94f) - @tjohnson7021 
- [x] Move the Summary and Incident Timeline sections from the Post-mortem template to the Incident Log template.
- [x] Reach out to Manjula and Luther on a proposal for where to put our incident process in SharePoint. - @halprin 
- [x] Fill in the [Process](https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0?pvs=4) sections. - @halprin 
- [x] Fill in the [Resources](https://www.notion.so/flexion-cdc-ti/Resources-0a6c39d8932044f09aa6b0361ea0f247?pvs=4) sections.
- [x] Write Communication section.

**Comment by scleary1cs** [comment]
Look up CMS Partners, and QPP Program, MPSM Program as inspiration.

**Comment by halprin** [comment]
@jcrichlake and I did some brainstorming on what should be included in the incident management process.

- Common Azure Log Workspace search queries or query fragments.
- "So an incident happened and you were woken up, what do I do?"
  - Incident roles and their expectations.  E.g. the incident commander.
  - Expected communication to those outside our team.
    - There will be times that there are outages, and who do we tell that this is happening.
  - Schedule blameless postmortem.
- The concept of, "Your job is to get production back and running, not triaging and root-cause the issue.  That comes later."
- Do we need a product person on the rotation?
- Process for handing incidents over to ReportStream or at least looping in a ReportStream engineer.
- Have to goal of first awareness of an issue coming from an automated process.  Maybe we include this concept in the blameless postmortem so we ask ourselves we could automate the alert for next time.
- Do we come up with a severity for these incidents?
- The incident manager will spin-up a Zoom (or Gather).  Peter can make a dedicated Zoom meeting link.
- Blameless postmortem template.
- Dedicated incident Slack channel.
- Incident log template.
- No required rubber stamps.  We are able to do what we need to do.
- What happens if a code change is required to bring prod back, but a code changes  are required, but that requires another dev approval to merge the PR.  How do we get around that?
- List of helpful links.
- Runbooks if we have identified "common" failure scenarios.
  - The symptoms.
  - Ways to confirm that the incident is indeed due to this failure.
  - Ways to fix this failure.

**Comment by basiliskus** [comment]
May be useful to define different on-call schedules with behaviors set according to severity level (at BEDAP we had schedule groups for 9-to-5 vs 24/7 depending on severity). Also need to define escalation policies (e.g. what happens when the on-call person doesn't ack the incident in x minutes?)

**Comment by scleary1cs** [comment]
Miro brainstorming session can be found here: https://miro.com/app/board/uXjVNtisWTU=/
