### ISSUE TITLE
PagerDuty Setup

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#177]
# Backlog Task

Set up PagerDuty for the team. Presumably we can use the same account used by ReportStream and SimpleReport.

## Completion Criteria

- [ ] Everyone on the team who needs PagerDuty access has it.
- [ ] An on-call rotation has been established.
- [ ] A backup on-call rotation has been established.
- [ ] Escalation process is established, documented, and shared. 
- [ ] Length of rotation has been established.
- [ ] Establish, document and communicate norms (coverage hours, SLA).
- [ ] Times, vacations expectations, comp time is documented and shared.  

## Tasks

- [x] Ask RS about securing another license @scleary1cs 

## Context

- People to have access
  - Peter Kendall
  - Basilio Bogado
  - Bella Quintero
  - James Gilmore
  - James Herr
  - Jeff Crichlake
  - Joel Biskie
  - John Park
  - Jorge Lopez
  - Luis Pabon
  - Sam Aquino
  - Sylvie Schuresko
  - Tiffini Johnson

**Comment by scleary1cs** [comment]
https://www.pagerduty.com/pricing/incident-response/

**Comment by scleary1cs** [comment]
Mo will look as getting more (12) PagerDuty.

**Comment by scleary1cs** [comment]
13 additional seats

**Comment by scleary1cs** [comment]
We will need some form of admin rights @halprin

**Comment by scleary1cs** [comment]
Note from RS meeting 03/01:
Pager duty seats- Mo will follow up; has not heard anything back as of today. They have raised the question about whether or not the existing number of licenses is sufficient. Mo will follow up once he receives an update.

**Comment by JohnNKing** [comment]
We've been asked for who needs a PagerDuty account: https://flexion.slack.com/archives/C048S3GPSQG/p1710441931404389

**Comment by scleary1cs** [comment]
No change as of 03/29/2024 sync with RS.

**Comment by scleary1cs** [comment]
No change as of 04/26/2024 sync with RS.

**Comment by scleary1cs** [comment]
05/10/2024 - Mo was not on the RS sync call, but we reached out via the ETOR channel: 
 "
@Maurice Reeves
 Happy Friday, we are in the "ReportStream <> Intermediary Onboarding and Product Sync", would you happen to have any updates on the PagerDuty seats? Any blockers we can help with? Any forecast for completion"

Mo's reply:
"I don’t. I thought they were purchased and this should be done. Let me find out"

**Comment by scleary1cs** [comment]
I pinged Dinah about the seats but she’s been OOO so I expanded the email to include others about who the POC is who can hand out those sweet sweet accounts - Mo

**Comment by scleary1cs** [comment]
OCIO pushed back on funding.  Mo is filing a exception request.

**Comment by scleary1cs** [comment]
so….nobody let me know this, but OCIO has hit pause on the purchase of additional licenses because PagerDuty is not FedRAMP’d yet. They are going through the process but it’s not complete. I wasn’t aware of this, hence my confusion about it not having been resolved. I’m seeking an exception request since we’re already using the tool. Stay tuned! - Mo  05/05

**Comment by JohnNKing** [comment]
May need to investigate alternatives? (discussed during Sprint Planning)

**Comment by scleary1cs** [comment]
Another slack poke to Mo [here](https://flexion.slack.com/archives/C048S3GPSQG/p1726155800762949?thread_ts=1724855792.146139&cid=C048S3GPSQG).

**Comment by scleary1cs** [comment]
hey everyone, the invoices from PagerDuty have been submitted and I’m meeting with OMO today to get them paid, so that should mean we can add folks in short order after that. details and updates to follow

**Comment by scleary1cs** [comment]
Discussed with @halprin moving this story to Production Stage 4.

**Comment by JohnNKing** [comment]
Closing for now as PagerDuty support may be permanently blocked and we've implemented work-arounds for receiving notifications.
