### ISSUE TITLE
User Support Documentation

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#178]
# Backlog Task

Document: "Standard operating procedures (SOPs), user manuals, frequently asked questions (FAQ) documents and troubleshooting guidance" (RFQ page 15)

Due: 3/26

## Completion Criteria
 
- [x] FAQs documented and shared with the CDC.
- [x] Troubleshooting Guidance documented and shared with the CDC.
- [x] Build and deploy of documentation is automated
- [x] New sections that encompass everything a user would need are stubbed out in the documentation

## Tasks

- [x] Review similar documentation in ReportStream: https://reportstream.cdc.gov/resources @sfradkin 
- [x] Add FAQ section to documentation @sfradkin 
- [x] Add Troubleshooting guidance section to documentation @sfradkin 
- [x] Add any other helpful sections based on current ReportStream documentation @sfradkin 
- [x] Automate generation of documentation @sfradkin @JohnNKing 
- [x] Automate deployment of documentation to staging environment @sfradkin @JohnNKing 
- [x] Create terraform for documentation bucket @JohnNKing

## Notes

- Clarify the target audience for these documents (consumers of the service vs how to use our codebase).
- Where are we going to store these documents?
- What documents need to exist from a contract-transition perspective?
- High-level documentation about automated processes (e.g. deployments, security scanning)
- Document service capabilities for potential end-users (from a non-technical perspective)
- Tie together existing docs (API spec, ADRs, READMEs)
