### ISSUE TITLE
Identify Healthcare Organizational-Level Personas

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#185]
# Backlog Task

Some healthcare providers have been more successful in providing NBS ETOR solutions. What differs those from those who haven't? How might our solution meet a larger range of providers with varying needs and priorities?

## Completion Criteria

- [x] Document a list of factors that matter to healthcare providers for ETOR (e.g. 6-8 types for hospital or health systems, grouped by varying factors and why different solutions may or may not work for them)
- [x] Document a list of organization-level personas (e.g. with grouping of the factors identified above)

## Tasks

- [x] Review ReportStream's persona-based research documentation 
- [x] Document a list of potential factors @cjterdi @april-messer @MikeC-A6 @JohnNKing 
- [x] Validated list of factors
- [x] Review capabilities of Cerner's FHIR API. Is their bulk API needed to search for patients? (Answer: Likely no) Is test information for our use case available via their open API? (Answer: Some, but not all) - @MikeC-A6 @JohnNKing 
- [x] writeup of assumptions and knowledge @MikeC-A6 (please elaborate)
- [ ]  Share out findings with the CDC (e.g. how might this influence who it would be best to partner with)

## Other Notes

- Research board: https://miro.com/app/board/uXjVPmo6kxY=/
- Research targets: (1) Small/Mid Hospital / Cloud-based EHR / Has a FHIR API / Number of births. (2) Large Hospital / Customized EHR / Has own integration team / Number of births.
