### ISSUE TITLE
SonarCloud Quality Gates

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#187]
# Backlog Task

SonarCloud Quality Gates

## Completion Criteria

- [ ] The quality gates on the CDC-TI SonarCloud project are enabled and set to fail the build if not attained

## Tasks

- [ ] Evaluate default quality gate rules
- [ ] Modify quality gate rules
- [ ] Enable quality gate rules
- [ ] Ensure build fails if quality gate not attained

## Other Notes

- TBD

**Comment by sfradkin** [comment]
Closing this task because the work will be done in Story #79
