### ISSUE TITLE
Synthesis of PHL Interviews

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#189]
# Backlog Task

Synthesize our interviews with PHLs to date using affinity mapping to define gap, pain points, and similarities. Use this to prepare questions for upcoming interviews with PHLs.

## Completion Criteria

- [x] Documented similarities between labs we've interviewed
- [x] Document set of questions for UT and GA

## Tasks

- [x] Affinity mapping between the labs we've interviewed
- [x] Document potential interest in ETOR
- [x] Find out who we'll be meeting with (process vs technical) for GA PHL
- [x] Use synthesis to build questions for Utah PHL interview
- [x] Use synthesis to build questions for second GA PHL interview

## Other Notes

- Research board: https://miro.com/app/board/uXjVP4khwcg=/
