### ISSUE TITLE
CDC Dev Environment Created (Access to CDC Azure Environments)

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#194]
# Backlog Task

CDC Dev Environment Created (formerly Access to CDC Azure Environments)

## Completion Criteria

- [x] We have a dev environment
- [x] The team has account access to the dev environment

## Tasks

- [x] Collect initial permission levels. - @halprin
- [x] Send info to Josiah.
- [x] Cloud pre-consult with Peraton/GDIT
- [x] Meet with ITDG
- [x] Prepare for the ART. - @sfradkin 
  - [x] Answer Security and DevSecOps Questionnaire. - @halprin
  - [x] Prepare current state data flow diagram. - @halprin
  - [x] Prepare future state data flow diagram. - @halprin
  - [x] Highlight the areas in the Logical Architecture Alignment to the North Star Architecture. - @halprin 
  - [x] Prepare current state technical architecture diagram. - @halprin
  - [x] Prepare future state technical architecture diagram. - @halprin
  - [x] Prepare the Technical Implementation Approach. - @JohnNKing 
- [x] ART meeting scheduled.
- [x] Meet with the ART.
- [x] Create the task to have a cloud consult.
- [x] Have the cloud consult with Peraton/GDIT. (july 6)
- [x] Azure environments 
  - [x] Get plan back from Peraton/GDIT.
  - [x] Work with CDC Azure team on specifics - @halprin
  - [x] Send e-mail out to people about who pays for our environments. - @halprin 
  - [x] Get to the bottom of who pays for our environments.
  - [x] Give plan approval.
  - [x] Create CR to initiate build-out. - @halprin 
  - [x] Have onboarding meeting with CDC Azure team. - @halprin 
  - [x] Get implementation plan back from Alan MacDermut.
  - [x] File a CR (Alan MacDermut is doing this).
  - [x] Get our -SU accounts created. - @halprin 
  - [x] Build-out of dev environment completes.
  - [x] Make an invite for everyone to try to log into Azure Portal. - @halprin 
  - [x] @halprin logs into Azure Portal with -SU account and confirms they have the `Azure Contributor Light` role for the `csels-rsti-dev-moderate-rg` resource group in the `OCIO-DMZ-C1` subscription.
  - [x] @basiliskus logs into Azure Portal with -SU account and confirms they have the `Azure Contributor Light` role for the `csels-rsti-dev-moderate-rg` resource group in the `OCIO-DMZ-C1` subscription.
  - [x] @jorg3lopez logs into Azure Portal with -SU account and confirms they have read/write access to the `csels-rsti-dev-moderate-rg` resource group in the `OCIO-DMZ-C1` subscription.
  - [x] @tjohnson7021 logs into Azure Portal with -SU account and confirms they have the `Azure Contributor Light` role for the `csels-rsti-dev-moderate-rg` resource group in the `OCIO-DMZ-C1` subscription.
  - [x] @sfradkin logs into Azure Portal with -SU account and confirms they have the `Azure Contributor Light` role for the `csels-rsti-dev-moderate-rg` resource group in the `OCIO-DMZ-C1` subscription.
  - [x] @halprin logs into Azure Portal with normal account and confirms they have the `Reader` role for the `csels-rsti-dev-moderate-rg` resource group in the `OCIO-DMZ-C1` subscription.
  - [x] @basiliskus logs into Azure Portal with normal account and confirms they have the `Reader` role for the `csels-rsti-dev-moderate-rg` resource group in the `OCIO-DMZ-C1` subscription.
  - [x] @jorg3lopez logs into Azure Portal with normal account and confirms they have the `Reader` role for the `csels-rsti-dev-moderate-rg` resource group in the `OCIO-DMZ-C1` subscription.
  - [x] @tjohnson7021 logs into Azure Portal with normal account and confirms they have the `Reader` role for the `csels-rsti-dev-moderate-rg` resource group in the `OCIO-DMZ-C1` subscription.
  - [x] @sfradkin logs into Azure Portal with normal account and confirms they have the `Reader` role for the `csels-rsti-dev-moderate-rg` resource group in the `OCIO-DMZ-C1` subscription.
  - [x] Split out remaining tasks into separate backlog items. - @halprin 
- [x] ITDG Decision Memo
  - [x] Draft questions about ITDG - @halprin 
  - [x] Send our questions to our more direct group - @halprin
  - [x] Get answers to our ITDG Decision Memo questions
  - [x] APIM/Digital Marketplace
    - [x] Reach out to Sailaja Savanam. - @halprin
    - [x] Send architecture diagrams to Sailaja - @halprin 
  - [x] Enterprise Data Catalog (not needed as of 7/28/2023 given clarification from Jasmine and Melvin)
    - [x] Reach out to Melvin Crum. - @halprin
    - [x] Sent out reminders. - @halprin 
    - [x] Hear back and continue conversations
  - [x] Splunk
    - [x] Reach out to Boris Ning. - @halprin
    - [x] Sent out reminders. - @halprin 
    - [x] Read documentation - @halprin 

## Other Notes

We should push to deploy to all the tiers by the middle of August.

**Comment by halprin** [comment]
Had the pre-consultation on 3/16/2023.  Said we will be referred to the ART/ITDG board for review.

**Comment by halprin** [comment]
Reached out to Sae Kim (and CC @ JosiahSiegel) on whats needs to happen next.

**Comment by halprin** [comment]
Reached out to Mark Winarsky, who is our POC for the ART according to Sae Kim.

**Comment by halprin** [comment]
Went up to the ITDG Review Team.  Was referred to the ART.

**Comment by halprin** [comment]
[ART package](https://drive.google.com/drive/folders/1iU5pCuw056Oxvhr3cm5x9DSGUdhfOnSQ).

**Comment by halprin** [comment]
Reached out to Josiah and Jeremy about creating new help desk tickets for a "cloud consultation".

**Comment by halprin** [comment]
We created a new help desk ticket.  `RITM0159113`.

**Comment by halprin** [comment]
Had the Cloud Consultation.  It went much better this time.  They are working on a plan for us.  We'll then get to approve this plan and formally create a CR to start the build-out.

**Comment by halprin** [comment]
Build-out for the dev environment has a ticket number of `CHG0030431`.  Apparently our build-out needs to go in front of the Technical Review Board (TRB) first.  It's on their agenda for today.  It will advance to approvals which can take a day or two.  Overall, the ticket number has a completion date set between August 2 - August 16.

**Comment by halprin** [comment]
I have reduced the scope of this backlog item to the creation of the dev environment.  The following follow-on backlog items have been created for the other tasks.

- #496.
- #497.
- #498.
- #499.
- #500.

**Comment by halprin** [comment]
This [documentation](https://learn.microsoft.com/en-us/azure/role-based-access-control/check-access) can be used to find your role for a resource group.
