### ISSUE TITLE
Create Deployment Frequency Metric

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#198]
# Backlog Task

Create Deployment Frequency Metric

Deployment frequency is one of the DORA metrics and we should capture it for our team.  It's generally measured on production deployments, however, we should be able to measure deployment frequency on all deployment environments.

## Completion Criteria

- [x] The team, or stakeholders can view the number of deployments made to each tier:
  - in aggregate over a fixed period of time
  - as an average number of deployments per day over a fixed period of time
  - with the date and time a deployment was done

## Tasks

- [x] Review [devops-deployment-metrics](https://github.com/flexion/devops-deployment-metrics) repo and determine if we can use it to get the metrics needed
- [x] Make adjustments to [devops-deployment-metrics](https://github.com/flexion/devops-deployment-metrics) to meet our requirements
  - [x] Add deployment log record (include time, environment deployed to, and what was deployed)
- [x] Deploy the metric report and schedule its execution
  - [x] Make sure the output is accesible 
- [x] Add a readme section with instructions on how to access and read the metrics files 
  
## Other Notes

- Any other notes to help clarify this task for the team
- 

## Definition of Done
- [x] Threat model updated
- [x] Code refactored for clarity and no design/technical debt
- [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies.
- [x] Source code is merged to the main branch.
- [x] Unit test coverage of our code >= 90%
- [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer.
- [x] Build process updated
- [x] Feature toggles created and/or deleted.  Document the feature toggle.
- [x] Source code documentation created when the code is not self-documenting.
- [x] API documentation generated
- [x] Code quality checks passed
- [x] Security & privacy gates passed
- [x] Load tests passed
- [x] Documentation and diagrams created or updated
- [x] API(s) are versioned
- [x] Debug logging
