### ISSUE TITLE
Hospital FHIR Capability Research

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#203]
# Backlog Task

Understand potential partner hospital FHIR capabilities that are enablers to electronic orders.

## Completion Criteria
For potential partner hospitals EHRs:
- [x] Documented the NBS information available via FHIR
- [x] Documented a comparison of the information available via ADTs vs FHIR
- [x] Identified how we might acquire the specimen ID
- [x] We understand SMART on FHIR support
- [x] We understand how the deployment process for SMART on FHIR works

## Tasks

- [x] Analyze and document Banner Health Cerner FHIR API Capability Statement (@MikeC-A6)
- [x]  Analyze and document Atrium Health FHIR API Capability Statement
- [x]  Analyze and document Russel Medical Center FHIR API Capability Statement
- [x]  Research availability / implementation of CDS Hooks
- [x] Determine what next-of-kin data is available in the Patient Resource as compared to RelatedPerson

**Comment by MikeC-A6** [comment]
Research Documentation in Progress

**Comment by MikeC-A6** [comment]
**Meet with those who have experience with ECR Now (SMART on FHIR app store implications**) - would like to move this to a different story

**Comment by MikeC-A6** [comment]
@JohnNKing Research finding PPT is [here](https://docs.google.com/presentation/d/1HwvIBwXEdWev8MEBdYuMNYRZ_qNIcM6SdV4SbWYj_l0/edit#slide=id.g213f21d6abc_0_429)    - I'm stopping work on this but will defer to you re: accepting the story as complete

**Comment by JohnNKing** [comment]
Thanks @MikeC-A6 -- I'm reviewing now...

**Comment by JohnNKing** [comment]
@MikeC-A6 The slides look great! Regarding, the completion criteria: "Identified how we might acquire the specimen ID", are you thinking we'd likely need to make this an ask-on-entry question?

**Comment by MikeC-A6** [comment]
Yes - based on PHL feedback we got, this is almost always a AOE question within the EHR.  The hospital we interviewed said they document the specimen number, but we are assuming that this is done in notes and not within a structured field that could be accessed via a FHIR endpoint.  Shorter term solution would be data entry, while longer term solution may be a barcode scanning integration with the app.

**Comment by JohnNKing** [comment]
Thanks @MikeC-A6! The only other question I have is related to the SMART on FHIR deployment process AC. I've found many references to how this works from an authentication perspective and how the app can appear within the EHR interface, but I'm still unclear on where the app is hosted and how it's kept up to date.

**Comment by MikeC-A6** [comment]
“Cerner expects the majority of SMART apps to be provided to clients in a SaaS (software as a service) model. That is, the SMART app is hosted or managed by the SMART developer or provider. In this case, clients do not need to install any code or package in order to implement a particular SMART app.”    [Link](https://fhir.cerner.com/smart/)
