### ISSUE TITLE
Understand HL7 Barriers

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#223]
# Backlog Task

Understand the primary barriers to HL7 Version 2 accommodating necessary changes at the pace of change of our US healthcare system.

## Completion Criteria

- [x] Document the history, capabilities, and limitations of HL7v2.

## Tasks

- [x] Document examples of where HL7 has adapted
- [x] Document FHIR as something that has modularity and flexibility
- [x] Document legislation in support of FHIR

## Other Notes
- https://docs.google.com/document/d/1kgIqvDiIBqLBLcUKf_1uuBhs4bTmv8UkCtCKWLdWj5A/edit
