### ISSUE TITLE
NBS Results Research

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#234]
# Backlog Task

Get a better understanding of NBS results to inform upcoming interviews next week. Use this to identify gaps.

## Completion Criteria

- [x] We're prepared to ask GA about NBS results process.

## Tasks

- [x] Develop results-related questions for GA
- [x] Document our understanding of results workflow for GA per our desk research
