### ISSUE TITLE
SMART on FHIR Proof of Concept

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#239]
# Backlog Task

Demonstrate how a SMART on FHIR app could be used to complete an NBS order. The goal is to determine if this approach is technically viable for a future prototype. Whether we embark on that will depend prospective healthcare provider customers.

## Completion Criteria

Create a simple application that:
- [ ] Demonstrates sandbox EHR authentication & authorization via SMART
- [ ] Demonstrates how a SMART on FHIR app can provide an NBS order form
- [ ] Demonstrates how a FHIR query can populate some or all elements on the order form
- [ ] Demonstrates how a printable label could be generated

## Tasks
- [x] Experiment with the Logic Health FHIR sandbox
- [x] Get a test SMART on FHIR app working in the sandbox
- [x] Confirm that a print dialog can be triggered via JS
- [x] Confirm that CSS can be used to simplify the printed label
- [x] Create a basic NBS order webform
- [x] Populate the form name and DoB based upon the FHIR Patient query
- [ ] Document any outstanding questions

## Other Notes

- Any other notes to help clarify this task for the team
