### ISSUE TITLE
List Newborn Screening Orders

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#27]
# Story

## Sentence

As a Hospital,
In order to know what newborn screening test have been ordered,
I need to be able to list all orders that have been submitted.

## Acceptance Criteria
- [ ] Labs can list all ordered tests (a REST API is sufficient; no UI required)
- [ ] Listed test data must include: Patient Name, Test Type, and Date
- [ ] Order information must be transmitted securely (e.g. via TLS), except in local development environments

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the story here.

## Definition of Done

- [ ] _TBD._
