### ISSUE TITLE
Document Integration Options for HCOs

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#285]
# Backlog Task

Document the options for integrating with the TI service to help inform decision making by the providers and the CDC.

## Completion Criteria

- [x] Documented the list of integration options
~~- [ ] Documented a visual overview~~
- [x] Shared integration options with the CDC

## Tasks

- [x] Draft write-up
- [x] Draft email and send to Jasmine/Rebecca
- [x] Draft email and send to Jason/Rishi
- [x] Team review and edit

## Other Notes
- What should we include as options?
  - SMART on FHIR vs native EHR interface
  - HL7 vs FHIR (defer: vs custom formats)
  - Defer: Partial vs full orders
  - Defer: Order status?

**Decision**
1. Native EHR interface via HL7
2. SMART on FHIR

**Comment by MikeC-A6** [comment]
[Version 2 Draft  ](https://docs.google.com/document/d/1Hmf_OCBxN6p4GzQWMiIs41pQf6eMc4RPWJpNeUU3zzs/edit#)
