### ISSUE TITLE
Document Partner Attribute Impact on Effort

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#292]
# Backlog Task

As the CDC, so that I can evaluate the trade-offs of different solutions and partner selection options, I need to understand the impact of different partner attributes on the effort and timeline for ETOR implementation.

## Completion Criteria

- [x] Documented the list of potential partner attributes
- [x] Documented the level of effort / complexity for each potential solution
~~- [ ] Document the potential impact on delivery timeline~~
- [x] Share these documents with stakeholders

## Tasks

~~- [ ] Review https://aphlinformatics.atlassian.net/wiki/spaces/IR/pages/1914208261/Project+Approach+Document+Electronic+Test+Order+and+Result+Initial+Implementation+for+Newborn+Screening~~
~~- [ ] Document any high-impact assumptions we've discovered during the course of this effort.~~

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by JohnNKing** [comment]
Efforts documented in https://miro.com/app/board/uXjVMMyJhJE=/
