### ISSUE TITLE
Update AL & LA State Profiles

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#296]
# Backlog Task

Update the AL & LA state profiles to include research for potential partner hospitals.

## Completion Criteria

- [x] The state profiles have been updated with information for the three potential hospital partners provided by AL & LA.

## Tasks

- [x] Research potential partner hospitals and their persona type to update target details on one-pagers for AL & LA
- [x] Update one-pager and add to shared folder

**Comment by cjterdi** [comment]
These look great. I think the maps that show the decline in rural access to obstetrics from 1980 to 2016 in AL give an accurate snapshot of what's happening in health care. I also think the information you provided about the level of interoperability among hospital systems in LA is really interesting. Not sure what kind of impact that may have on NBS ETOR, but once we identify partner states that may be an area for more research...?
