### ISSUE TITLE
Newborn Screening Questions

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#30]
# Research

## Sentence
As the CDC TI team,
To begin initial research to inform the newborn screening lab order intermediary service,
We need a documented list of research questions to ask State Public Health Labs, USDS, and the CDC.

## Acceptance Criteria
- [x] Document a list of key questions

## Tasks
- [x] Develop questions - need more detailed tasks for how we are tackling this problem. Draft round of questions for Stakeholder meeting with Jasmine/Rishi: https://docs.google.com/document/d/1hRig7-Mb5LFIhLDveNsS0zHedRptMjxNLr6YxLQoz3k/edit
- [x] Created Research Scratchboard to organize questions for newborn screening and general discovery: https://miro.com/app/board/uXjVPMyq_HY=/

## Notes
- We need a problem definition
- We need to better understand the problem of communication between Healthcare Providers and Labs
- Are challenges greater for Providers or Labs?

## Examples
- What information do we need from our stakeholders?
- What are our assumptions regarding research?
- How do hospitals submit newborn screening orders today?
- How are the screening orders received from the hospitals?
- What types of newborn screening orders are there? Do the orders arrive together or individually?
- Can we get a demo of existing newborn screening?
- Are private labs involved at all?
- What are the high level workflows that hospitals have with private labs for other types of tests?
- Why is newborn screening performed?
- What similarities or differences are there to other types of lab orders?
- What are the sorts of illnesses that newborn screening will detect?
- When does newborn screening take place? Post-delivery?
- Why do some parents opt-out of the screening?
