### ISSUE TITLE
Documentation Automation Improvements

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#315]
# Backlog Task

Additional improvements for working on and automating documentation

## Completion Criteria

- [ ] A consistent URL is available to access the documentation on the Flexion staging environment
- [ ] A solution exists to allow for any developer to easily update and test documentation generation without having to install more tooling on their computer

## Tasks

- [ ] What tasks need to be done to fulfill the completion criteria?

## Other Notes

- Any other notes to help clarify this task for the team
