### ISSUE TITLE
Additional Deployment Frequency Metric Functionality

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#317]
# Backlog Task

Additional functionality to view details for each deployment as to what was deployed and where it was deployed to

## Completion Criteria

- [x] ability to view each deployment made, the environment it was deployed to, and what was deployed
- [x] Integrate updated `devops-deployment-metrics` into our workflows

## Tasks

- [x] Provide the ability to view our existing DORA metrics according to the environment it was deployed to

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by basiliskus** [comment]
Refactoring for `devops-deployment-metrics` is almost done. Including separation of metric outputs per environment. Only pending is refactoring for the Mean Time to Recover metric. Other metrics have been included in the refactoring
[PR 72](https://github.com/flexion/devops-deployment-metrics/pull/72/)

**Comment by basiliskus** [comment]
Refactoring of the `devops-deployment-metrics` repo in [PR 72](https://github.com/flexion/devops-deployment-metrics/pull/72/) has been completed, reviewed and merged. Tasks included:
- Added capability to separate metrics' outputs for different workflows. For this purpose, metrics output names are added per workflow. If multiple workflow have the same output name, they will be aggregated
- Refactored for separation of concerns and extensibility
- Fixed pre-commit hook script
- Changed env variable name: GITHUB_PASSWORD => GITHUB_TOKEN
- Created files for logging, configuration, common utilities and definitions
- Removed try/except code to let python handle exceptions
- Added test coverage
