### ISSUE TITLE
Partner PHL Integration Options

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#356]
# Backlog Task

For MN: Create a LOE matrix of integration options based on the actual constraints of EHR vendors, hospitals and the PHLs to understand the opportunities we can leverage.
This can be expanded and used to assess learnings from the pilot and future partner implementations.

## Completion Criteria

- [ ] For MN, create a baseline matrix of all potential integration options and technolog(ies) used. This information will complete/validate our assumptions work completed in [story #292](#292)

## Tasks
- [ ] Arrange further meetings and pathway for async questions - @JohnNKing 
- [ ] Identify potential integration options for MN
- [ ] Determine subsequent level of effort; to help ensure a realistic timeline
- [ ] Document MN outreach questions regarding technical requirements
  - [ ] Send these to Natalie for distribution
- [ ] Understand existing ETOR offering (if present) and how we might build off of it
- [ ] Understand PHL expectations and what they're envisioning for an ETOR solution
- [ ] Map data fields for MN to HL7 and FHIR (see Screening Card Data fields spreadsheet)
- [ ] Identify gaps in knowledge about how HL7 and/or FHIR messages are constructed, mapped, and converted (e.g. provenance)

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by JohnNKing** [comment]
Discussed during Sprint Planning -- moving back to needing refinement; perhaps we can make this more generic or apply to our first partner?

**Comment by JohnNKing** [comment]
Since replaced by other stories
