### ISSUE TITLE
Consistent URL for Documentation

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#370]
## Completion Criteria

- [ ] A consistent URL is available to access the documentation on the Flexion staging environment
- [ ] Automation process can update documentation files in an existing blob store
- [ ] Build process puts the generated documentation into the correct bucket for each tier

## Tasks

 - [ ] add terraform to create an Azure CDN and possibly use Azure DNS with a custom domain @sfradkin
- [ ]  modify command used in github action workflow to upload documentation files to use sync rather than upload-batch @sfradkin

**Comment by brick-green** [comment]
@sfradkin Is this still useful?
