### ISSUE TITLE
Newborn Screening Scalability

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#38]
# Story

## Sentence

As a Hospital,
To ensure that my newborn screening lab orders get to labs successfully, no matter how many orders I send during the day,
I need the application to continue to be responsive under high traffic.

## Acceptance Criteria
- [ ] Support continuous order submission volume of at least 25,000 requests per minute
- [ ] Support burst order submission volume of at least 250,000 per minute
- [ ] Maximum latency of one minute between order submission and when it can be listed
- [ ] Research: Validate that this volume is sufficient for the foreseeable future

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the story here.

## Definition of Done

- [ ] _TBD._
