### ISSUE TITLE
Review ReportStream

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#43]
## Sentence
As the CDC TI team,
So that we avoid duplication of effort,
I need to better understand how ReportStream works and how we might integrate with it.

## Acceptance Criteria
- [x] Document some options for integrating with ReportStream
- [x] Document some pros & cons for each ReportStream integration option
- [x] Document hypothesis and assumptions that will need to be tested related to use of ReportStream

## Tasks
- [x] Host a technical discussion with ReportStream tech leads
- [x] Schedule time with Cle. - @halprin 
- [x] Meet with Clé. - @halprin 
- [x] Clone and walk the RS repository. - @halprin 
- [x] Compile current and future ways to integrate with RS. - @halprin 
- [x] Document options and their pros and cons - @halprin
- [x] Share with Rishi.
- [x] Document how we would integrate with RS, what would need to change in RS, and what would need to be modularized/extracted/genericized.  The associated areas are... - @halprin 
  - Routing
  - AuthN/AuthZ
  - Using RS as the single front door for us.
  - FHIR/HL7 conversion
  - Any other possible reuse, it must be reused. 
- [x] Draft TI architecture diagram v2

## Additional context
- RFQ Task 1-1: Review existing user research, including in reference to the CDC ReportStream solution for lab data routing (https://reportstream.cdc.gov/)

**Comment by JohnNKing** [comment]
Review existing user research, including in reference to the CDC ReportStream solution for lab data  routing (https://reportstream.cdc.gov/)

**Comment by JohnNKing** [comment]
Document how

**Comment by JohnNKing** [comment]
- Need to determine how best to integrate with existing ReportStream
- Important to re-use existing connections (e.g. Hospitals, STLTs)
