### ISSUE TITLE
Discovery/Research Engagement Prep

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#463]
# Design or Research

To introduce the Flexion team and the importance of collaboration on the pilot, we need to explain the ‘what we’re doing and why’ of our engagement so that the PHL understands how we can work together.

## Completion Criteria

- [x] Draft team engagement plan to initiate ETOR implementation with a PHL partner

## Tasks
Create initial set of research documentation to validate and identify gaps/pain points/opportunities with the PHL team prior to in-person kickoff meeting
- [x] Create visual mapping of all stakeholder groups that relate to the design problem
- [x] Identify teams involved with NBS process at the PHL (ex., Sample receiving team, Followup team, Results team, IT roles, Informatics roles)
- [x] Create workflows associated with current NBS process to understand context and touch points 
     - [x] AL
     - [x] LA 
- [x] Create initial introduction/elevator pitch to introduce team (format tbd)
- [x] Collab with Rupal to identifying roles and responsibilities for collaboration (part of charter)

## Additional Context

Add any other context or screenshots about the work here.
