### ISSUE TITLE
Newborn Screening Test Order & Results Process

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#48]
# Story

## Sentence

As the CDC TI Team,
In order inform future research needs,
I need a deeper understanding of the newborn screening test order & results domain.

## Acceptance Criteria

- [x] Develop and document an understanding the Newborn Screening Domain
- [x] Document the workflow of newborn screening test order and results for at least two states (e.g. GA)
- [x] Document at least two of the national polices or laws related to newborn screening test order and results

## Tasks
- [x] Document high level understanding of Newborn screening
- [x] Document Georgia PHL current state process based on their website
- [x] Understand why adoption of even HL7 ETOR is so low @MikeC-A6 
- [x] Identify two screen states

**Comment by MikeC-A6** [comment]
Some research and high level workflow documented in Lucid [here](https://lucid.app/lucidchart/541da0c8-6832-4305-a3f0-3cddef7c3072/edit?viewport_loc=81%2C-93%2C1707%2C777%2CwVx3y.ybMG.r&invitationId=inv_7f084bbb-4424-4b6f-b245-2305cfc55101)
