### ISSUE TITLE
Create an OML Logical Model for IG

### ISSUE THREAD

**Issue by tjohnson7021** [CDCgov/trusted-intermediary#485]
Need to create an OML logical model for the Implementation Guide. 

This will represent output(?)

**Tasks:**

- [x] Create `logical-oml-021.fsh`
- [x] Update `logical-oml-021.fsh` with correct fields. 
- [x] Create separated fsh files for each segment type: MSH, EVN, PID, NK1, ORC, OBR, SPM, OBX
- [x] Add Provenance for history tracking - [Reference](https://github.com/IHE/ITI.PCF/blob/master/input/fsh/SLS.fsh)

**Questions:**

- [x] Do we want to separate the segments at this point? 

**References:**
[MN HL7 DBS Orders Specification.pdf](https://drive.google.com/file/d/1sSkT2e3_pFtffhyrKvaD9bNZkvxX-G4l/view)
[Screening Card Data fields](https://docs.google.com/spreadsheets/d/1yUZ5SnL5et3QYvu6p1Luk3AUSuOziCL-lRRI8uyYfn4/edit#gid=1336407508)
