### ISSUE TITLE
Create `.env` file to store project environment variables

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#487]
# DevEx/OpEx

An `.env` file will make it easier to use and manage environment variables needed in the project, in a local dev environment 

## Tasks

- [x] Create PR for `task/eng-create_local_env_file` branch
- [x] Consider not relying in third party library to read `.env` files if custom handling is straightforward --> did some research and it's not straightforward
- [x] Make sure the sample `.env.example` has entries for all currently used env vars
- [x] Dynamically create a sample `.env` to use in the tests
- [x] Add tests

**Comment by basiliskus** [comment]
We currently have a [draft PR](https://github.com/CDCgov/trusted-intermediary/pull/488) with work so far. Still pending, we need to find a good way to handle .env files for e2e test, unit test and app scopes. I moved .env files to resources folder, but we may move them elsewhere if more appropriate
