### ISSUE TITLE
CDC Staging Environment Created

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#497]
# Backlog Task

CDC Staging Environment Created

## Completion Criteria

- [x] We have a staging environment.
- [x] The team has account access to the staging environment.
- [x] A full deployment successfully completes of our staging environment into our CDC Staging environment.
- [x] The full deployment to the CDC Staging environment can happen programmatically as it does today to the Flexion Staging environment.
- [x] We no longer deploy to the Flexion Staging environment.

## Tasks

- [x] Create help desk ticket - @halprin 
- [x] Responded back with the resource group template filled out - @halprin 
- [x] Get update from the helpdesk team. - @halprin 
- [x] Responded to Jennifer. - @halprin 
- [x] Attend TRB meeting. - @halprin 
- [x] Wait for Staging environment. - @halprin 
- [x] Update the CDC Azure App Integration to support automated deployments to our staging environment.
- [x] Update our GitHub Action to deploy to the CDC domain.
- [x] Update our Terraform to move it's remote state to the CDC domain.
- [x] Update our Terraform to specify the CDC Azure App Integration.
- [x] Update our Terraform to remove the extra `2` from the name of resources.
- [x] Do our initial deploy.
- [x] Ensure our dev deploy isn't broken with the `2` removed from the resources. - @halprin 
- [x] Move our Staging secrets over to the newly deployed environment. - @halprin 
- [x] Ask ReportStream to update our `flexion.etor-service-receiver` ReST endpoints.
- [x] Flexion Staging environment is deleted.

## Other Notes

- The ticket for the Dev environment was `RITM0169671`.
- The ticket for the Staging environment is `RITM0205730`.
  - Updated ticket number for the Staging environment is `CHG0031606`.
- As of October 10, 2023, the current completion date is October 13, 2023.
- As of October 23, 2023, at the TRB meeting, the Azure team will start creation on Wednesday, October 25, 2023 and finish by Wednesday, November 1, 2023.

**Comment by halprin** [comment]
We are waiting for the staging environment to be created by the CDC Azure team.  They have a due date of November 1st, 2023.
