### ISSUE TITLE
Flexion Implementation and HCD Collaboration Plan

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#506]
# Design or Research

High level description of what design or research needs to be accomplished.

## Completion Criteria

- [ ] Document describing overall high level collaboration between Flexion and HCOs and PHLs
  - [ ] Why are we collaborating in this way?  And what mechanisms?  both for HCD and technical integration
  - [ ] communication, contact information, everything collaborative
  - [ ] create intro ppt from LA engagement Miro presentation
  - [ ] interviews
  - [ ] testing
  - [ ] ad-hoc communication about integration details
  - [ ] proactive risk management
  - [ ] 

## Tasks

- [ ] Something.

## Additional Context

- how will this information be delivered?  format, when?  need to understand what Deloitte is thinking here
- what will the audience be?
- is change management part of this?
-

**Comment by scleary1cs** [comment]
Closed as #861 takes over this effort.
