### ISSUE TITLE
Metadata Proposal

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#517]
# Design or Research

We need to do some research to define a proposal for shared metadata.  This is something that Rishi has asked both Flexion/RS and APHL to do.  Both orgs have different types of metadata and there is an open question as to exactly what metadata needs to be captured and for what purposes and for whom.

The anticipated user for the pilot for metadata is the system end user (PHL and HCO, e.g., nurse, PHL system admin, HCO EHR engineer), not RS/Flexion/internal CDC.

## Completion Criteria

- [x] We have a documented proposal that can be shared with APHL and Rishi to move forward the conversation about a single set of metadata requirements to start with for the intermediaries

## Tasks

- [x] Decide where we will put our proposal (Notion, APHL Confluence, Google Drive, Microsoft Teams?).
- [x] Decide on fields.
  - [x] Chat with David?
  - [x] Chat with California (Deloitte)?
- [x] Decide on a structure.

## Additional Context

- @rtarar suggests using [FHIR `AuditEvent` resource](https://hl7.org/fhir/R4/auditevent.html).
- [Intermediary Available Metadata](https://cdc.sharepoint.com/:x:/r/teams/OLSS_ETOR_ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BE5389796-4F4C-4383-A4E9-E1FC0CB059C7%7D&file=Intermediary%20Available%20Metadata.xlsx&action=default&mobileredirect=true).

### David Notes

- the results should be specified as the number of results sent back to the HCO that ordered electronically; need to scope this only to the HCOs that are sending electronic orders
- results without an order can be tracked
- do we really need 7, 8, or 9?  delivery of messages happens real time, within minutes.  consider that there could be issues internally within the intermediary where a message gets stuck, but is that something to worry about?
- consider splitting 10 into 2 items: content errors vs system related errors vs missing information
- for 10, count the number of orders that failed (there might be more error reasons than orders)
- for failures split out inbound orders from results
- define and document the types of errors

## Decided Metadata

After meeting with APHL and @rtarar, the shared metadata to be collected for MVP is outlined below.  Even further below is the proposal which is outdated.  It is included for provenance purposes.

### Metrics

1. Time of order ingestion into intermediary.
2. Time of order delivery to PHL.
3. Time of result ingestion into intermediary.
4. Time of result delivery to HCO.
5. A failure reason for the order (if there is a failure). The exact possible set of reasons are yet to be defined but will encompass content errors, missing information, or system errors.
6. A failure reason for the result (if there is a failure). The exact possible set of reasons are yet to be defined but will encompass content errors, missing information, or system errors.
7. Unique ID.
8. Sender name.
9. Receiver name.
10. A hash (sha1) of the payload.
11. File name (optional).

### Format

We will explore three different FHIR resources.  If none of them fit what we need, we can explore using a custom JSON payload.

- [`AuditEvent` resource](https://hl7.org/fhir/R4/auditevent.html).
- [`OperationOutcome` resource](https://hl7.org/fhir/R4/operationoutcome.html).
- [`Provenance` resource](https://hl7.org/fhir/R4/provenance.html).

## Proposal

This is our outdated proposal.  See above for the decided upon list.

###  Metrics

1. Number of electronic orders sent per day and per week for a given HCO.
2. Number of electronic results sent per day and per week for a given PHL that started from an electronic order.
3. Number of electronic results sent per day and per week for a given PHL that are unsolicited.
4. Number of electronic orders that failed per day and per week for a given HCO.
5. Number of electronic results that failed per day and per week for a given PHL.
6. Time of order ingestion into intermediary.
7. Time of order delivery to PHL.
8. Time of result ingestion into intermediary.
9. Time of result delivery to HCO.
10. Where the order is in the flow.  In intermediary or delivered.
11. Where is the result in the flow.  In intermediary or delivered.
12. A combination of the above two where we're given an over arching view of the entire flow.  Given an order number, what's the current step (order in intermediary, order delivered to PHL, result in intermediary, result delivered to HCO).
13. A failure reason for the order (if there is a failure).  The exact possible set of reasons are yet to be defined but will encompass content errors, missing information, or system errors.
14. A failure reason for the result (if there is a failure).  The exact possible set of reasons are yet to be defined but will encompass content errors, missing information, or system errors.

### Format

Our default choice will be the [FHIR `AuditEvent` resource](https://hl7.org/fhir/R4/auditevent.html).  This could change in the future if, for some reason, the agreed upon metrics cannot be represented in `AuditEvent`.
