### ISSUE TITLE
Research Plan for initial engagement with PHL

### ISSUE THREAD

**Issue by cjterdi** [CDCgov/trusted-intermediary#518]
We need to understand the needs of different users, define differences/priorities and impacts between process and integrations, and understand technical requirements needed to implement ETOR and what resource constraints they may have at the PHL.

## Completion Criteria

- [x] Draft research plan for initial interview with a PHL partner

## Tasks
Create initial plan to explain and recruit PHL team members to participate 
- [x] Create a draft scope of work outlining the requirements for PHL participants and expected outcomes
- [x] Official communication to invite participants (email?)
- [x] Confirm documentation for participants to review
     - [x] Process flow map
     - [x] Sample questions
- [ ]  Other?
