### ISSUE TITLE
Initial PHL Interview Synthesis

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#538]
# Design or Research

Confirm or inform current workflows and processes, understand roles and relationships, to create a comprehensive understanding of what impacts ETOR for Newborn Screening in order to identify issues and risks that may impact initial implementation.

## Tasks

- [x] Conduct initial group interview
- [x] Conduct initial 1:1 interviews
- [x] Share data and hypotheses gathered in synthesis of interviews to inform next steps @april-messer @mary-kuris
- [x] Create artifact with PHL team that accurately reflects current state @cjterdi: https://drive.google.com/file/d/1X_Bb3TTv44oYr8A0PaO0hcO3U_0Ywo3Y/view?usp=sharing

## Additional Context

Add any other context or screenshots about the work here.
