### ISSUE TITLE
Research Plan for initial engagement with Ochsner

### ISSUE THREAD

**Issue by cjterdi** [CDCgov/trusted-intermediary#543]
As Ochsner Health, so that the CDC is able to conduct effective user interview with our staff, I need the CDC to draft a research plan for our initial interviews.

## Completion Criteria
- [x] A draft research plan has been completed
- [x] We are ready to begin interviews

## Tasks
- [x] Draft research plan, including sample questions, for the initial interview with Ochsner: https://docs.google.com/document/d/1SwZTU5UEg5pgTXe16R4WkVaUprRgPMwp/edit
- [x] Draft process workflow template: https://miro.com/app/board/uXjVMaOm3vs=/?moveToWidget=3458764564932411816&cot=14

## For next story
- [ ] Recruit Hospital team members to participate 
- [ ] Document process flow for users involved with the collection of NBS data
- [ ] Document process flow for users involved with the validation of NBS data
- [ ] Document process flow for users involved with the management of NBS data
- [ ] Document the differences between process and integrations
- [ ] Document the priorities between process and integrations
- [ ] Document the impacts between process and integrations
- [ ] Document the technical requirements needed to implement ETOR for the hospital
- [ ] Document what resource constraints they may have at the hospital that may impact ETOR

**Comment by cjterdi** [comment]
Needs refinement
