### ISSUE TITLE
LA Kickoff

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#556]
# Design or Research

As LA OPH Lab, so that the CDC ETOR team is able to quickly move forward with supporting NBS ETOR, I need the team to prepare for and facilitate several kick-off sessions.

## Completion Criteria

- [x] Kick-off has taken place

## Tasks

- [x] Talk w/ Harry (Natus) to help onboard them to ReportStream @halprin 
- [x] Share draft of current process flow for LA OPH
- [x] Team session to review of current process flow for LA OPH
- [x] Review pre-read materials
  - [x] @halprin to review the E2E future data flow
- [x] Draft an agenda for session 5 (tech/hackathon)
- [x] @halprin to update the [kick-off slides](https://cdc.sharepoint.com/:p:/r/teams/OLSS_ETOR_ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B81013967-D653-4694-BE63-0B6081D4CFC2%7D&file=0.12%20LA%20Kickoff%20Welcome%20Slides_Session%201.pptx&action=edit&mobileredirect=true), especially Session 5.
- [x] Everyone update their parts of the [Kick-off Agenda Word document](https://cdc.sharepoint.com/:w:/r/teams/OLSS_ETOR_ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B4A756124-A3EC-45CE-8724-473E15F175C5%7D&file=0.12_ETOR%20Kickoff%20Agenda_Draft_092813.docx&action=default&mobileredirect=true&ovuser=9ce70869-60db-44fd-abe8-d2767077fc8f%2Cujg1%40cdc.gov&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyOC8yMzA4MDQwODYzNiIsIkhhc0ZlZGVyYXRlZFVzZXIiOnRydWV9).
  - [x] Session 5 - @halprin 
- [x] @halprin create ReportStream Postman collection and send to Harry. - @halprin 

## Additional Context

Use as a spike. After the kick-off, we'll need to document and plan subsequent work.

### Session 5 Agenda

Any of this can be shifted left and accomplished before session 5 if we want to; no need to wait.

#### Prerequisites

There are somethings that may take longer to produce or procure, so these items could be considered prerequisites since we don't want to be blocked for the limited time we have.  If you think you can do the following can be accomplished in the moment, then no need to do this beforehand.

1. The engineers (or whoever will be handling the private keys that may need to be communicated) have a [Keybase](https://keybase.io) account to share secrets securely.
2. Natus staging/test/dummy ReST endpoints are stood up for us to test against.

#### Agenda

1. Create baseline PHL organization in RS.
2. Onboard Harry to PHL organization.
3. Create baseline PHL sender and receiver in RS.
4. Figure out what the filters need to be for the sender and receiver.
5. Natus Receiver (orders)
   1. Get details on a (dummy?) Natus ReST endpoint.
   2. Figure out the public/private key creation and hook it into the Natus RS receiver.
   3. Send test HL7v2 ORM through our `simulated-hosptial` sender and see if it is received by the Natus ReST endpoint.
   4. Iterate on any errors and make it better.
6. Natus Sender (results)
   1. Give any additional details for ReportStream's staging ReST API (Postman collection?).
   2. Figure out the public/private key creation and hook it into the Natus RS sender.
   3. The intermediary can create a quick `results` endpoint to receive the sample `ORU`.
   4. Natus sends test HL7v2 ORU through their sender in RS staging.  See if the intermediary receives the sample.

**Comment by scleary1cs** [comment]
[CDC ETOR via ReportStream Intermediary Initial Implementation Agenda](https://cdc.sharepoint.com/:w:/r/teams/OLSS_ETOR_ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B4A756124-A3EC-45CE-8724-473E15F175C5%7D&file=0.12_ETOR%20Kickoff%20Agenda_Draft_092813.docx&action=default&mobileredirect=true)

**Comment by scleary1cs** [comment]
[Kick-Off Materials](https://aphlinformatics.atlassian.net/wiki/spaces/ERI/pages/2069889136/Kick-Off+Materials)
