### ISSUE TITLE
AL NBS Order Test Scenarios

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#559]
# Story
As a PHL or HCO, so that we're confident the various branches of our workflows will work under ETOR, develop a set of scenarios and sample data to be used for testing NBS orders.

## Pre-conditions
- Data gap analysis work completed for LA and AL

## Acceptance Criteria
- [ ] Test scenarios are documented
- [ ] Sample messages for each scenario have been created and shared with the team

## Tasks
- [x] Brainstorm scenarios (reach out to partners, find out if any test scenarios currently exist)
- [x] Build out additional scenarios
- [x] Get more sample orders for scenarios we've identified (received 2.5.1 OML samples; but we also need 2.3 ORM samples) 
- [x] Document sample messages stored in GitHub
- [x] Draft a new story for partner feedback on round-trip tests, which may include:
  - Result test scenarios: https://github.com/CDCgov/trusted-intermediary/issues/964
  - Round-trip testing (incl. getting feedback from HCOs and PHLs and revising based on feedback): https://github.com/CDCgov/trusted-intermediary/issues/965

### Research
- [ ] *Research work needed to complete the story*
- [ ] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [ ] *Engineering work needed to complete the story*
- [ ] Foundational: *Technical runway work to support this and future efforts*

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] Threat model updated
  - [ ] API documentation updated
  - [ ] Source code documentation created when the code is not self-documenting
- [ ] Code quality tasks completed
  - [ ] Logging added where useful
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- What edge cases should we consider or not? (e.g. maternal deaths, surrogate mothers)

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- Future work likely will be needed to adapt these scenarios per state partner.
- This isn't a final set of scenarios; we should expect more in the future

**Comment by scleary1cs** [comment]
See if NIST has any testing stories. - @dbgolson

**Comment by scleary1cs** [comment]
How can we create universal test scenarios (not state specific).

**Comment by dbgolson** [comment]
Attached are test case scenarios developed initially for Oregon ETOR by JMC and used in the APHL AIMS Intermediary project.  I think we should use those same test case scenarios. They may require some modification as they walk through message transformations that may or may not be relevant to our project. We, as a team may wish to review before this is posted to the project Confluence page.  [ETOR NBS Validation Template_JMC.xlsx]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdytpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--834da34f72bdea02b93428383dfc2e1066282050/ETOR%20NBS%20Validation%20Template_JMC.xlsx)

Excel Workbook is also saved on our Google Drive here - 

https://docs.google.com/spreadsheets/d/1jI6E2n0AkxCW-mrdmS1yNGt7NQ9bDROw/edit?usp=drive_link&ouid=102849307490663018252&rtpof=true&sd=true

**Comment by nvcllns** [comment]
Once Flexion/Agile 6/JMC assesses the existing list of scenarios for alignment with the RS architecture, please plan for the roster of scenarios to be finalized via the CDC Program Meeting forum - Dave, Manjula, and Luther all have PoV as well. (Again, post preliminary workshopping.)

**Comment by nvcllns** [comment]
Sharing CLIA validation template put together by APHL team (this one is specifically for Iowa) - check it out! 

[CLIA Validation Template Newborn Screening - Iowa.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM09uQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a09edbda6bb7a7254835b2eb933be0e178e518c/CLIA%20Validation%20Template%20Newborn%20Screening%20-%20Iowa.docx)

**Comment by dbgolson** [comment]
Attached are the test case scenarios (orders and results) which APHL AIMS is currently using.  I have saved the document with a "CDC-TI" suffix.  These scenarios should be the ones we work, ensuring that they capture the various test scenarios we expect and also are updated to reflect the various workflows and translations that take place along the CDC TI path.

[ETOR NBS Validation Template_CDC-TI.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmlxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2935b21f588edb247434c984618dcd9523265772/ETOR%20NBS%20Validation%20Template_CDC-TI.xlsx)

Excel Workbook is also saved on our Google Drive here -

https://docs.google.com/spreadsheets/d/10xxPKrQsfx6hi81KwvNCfedgEAf-xqnx/edit?usp=drive_link&ouid=102849307490663018252&rtpof=true&sd=true

**Comment by JohnNKing** [comment]
@JohnNKing to schedule a working session

**Comment by cjterdi** [comment]
[Presentation on onboarding and testing NBS for hospitals ](https://www.youtube.com/watch?v=LRL-K0HAjzA)

**Comment by cjterdi** [comment]
[Updated version of test-case scenarios:](https://docs.google.com/spreadsheets/d/10xxPKrQsfx6hi81KwvNCfedgEAf-xqnx/edit#gid=601423445)

**Comment by cjterdi** [comment]
For next sprint (3-19-24) we will work with Natus (Lisa) to test result messages:

1. Emily and Daniel will tweak a sample test order messages to comply with RS requirements for ORM 2.5
2. Dev team will submit order to RS/TI to convert to an OML for Lisa to test the LIMS and provide result messages for testing
3. Happy path and unhappy path test results TBD

**Comment by basiliskus** [comment]
Context on why NK1 address was added: https://github.com/CDCgov/trusted-intermediary/issues/491
