### ISSUE TITLE
Jetty Dependency Vulnerability

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#569]
# DevEx/OpEx

Jetty 11.0.15 has two vulnerabilities open against it. This is the version that Javalin 5.6.2 depends on.  Jetty 11.0.16 fixes these vulnerabilities.

- [CVE-2023-36478](https://security.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-5958847)
- [CVE-2023-40167](https://security.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-5902998)

Additional work will be tracked in #570.

## Tasks

- [x] Create a workaround to force our Jetty dependency. - @jorg3lopez 
- [x] Create an issue in the Javalin repository. - @halprin 
- [x] Create a PR in the Javalin repository that updates the dependency. - @halprin 
- [x] PR is merged. - @halprin 

## Additional Context

- [Workaround PR](https://github.com/CDCgov/trusted-intermediary/pull/566).
- [Javalin issue](https://github.com/javalin/javalin/issues/2017).
- [Javalin PR](https://github.com/javalin/javalin/pull/2018).
