### ISSUE TITLE
Update Jetty to Revert Jetty Vulnerability Workaround

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/trusted-intermediary#570]
# DevEx/OpEx

Javalin uses the Jetty server dependency as part of their code. Our current Javalin version (`5.6.2`) uses the  `jetty-http:11.0.15` which has been flagged by Snyk, to have a vulnerability. 

The [workaround](https://github.com/CDCgov/trusted-intermediary/pull/566/files) was to update this dependency to a version that did not have the vulnerability.  In order to do this, we added the `jetty-http:11.0.17` dependency directly to our `app/build.gradle` file.

Also, @halprin opened an [issue ](https://github.com/javalin/javalin/issues/2017)to notify the Javalin team of this vulnerability from Jetty. 

The ideal situation is to revert this workaround once the Javalin team releases an update that takes care of the vulnerability from Jetty.

## Tasks

- [x] Update Javalin, make sure the update uses `jetty-http:11.0.16` or above.
- [x] Delete `jetty-http:11.0.17` from `app/build.gradle` file
- [x] Check Snyk report from GitHub checks to ensure there are no vulnerabilities from the update
