### ISSUE TITLE
Define Key Naming Convention and Implement It

### ISSUE THREAD

**Issue by jcrichlake** [CDCgov/trusted-intermediary#584]
# DevEx/OpEx

We currently don't have a key naming convention and the keys we have in keybase don't match the names as listed in the Azure portal.  We need to determine a convention for naming our keys and make sure all keys throughout the repo, keybase, and Azure all have the same name to avoid confusion. 

## Tasks

- [x] Key naming convention is determined
- [x] Keys are updated to be aligned with the convention across all locations
- [x] The pending ADR here is updated https://github.com/CDCgov/trusted-intermediary/pull/583/files
