### ISSUE TITLE
Present interview synthesis findings to LA Lab

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#586]
# Backlog Task

The interview synthesis results need to be presented to the LA lab

## Completion Criteria

- [x] Findings are presented and comments/questions compiled

## Tasks

- [x] Rupal to schedule a meeting (Lab personnel, CDC, Natus, Ochsner(optional))
- [x] Present findings
- [x] Compile any feedback (no feedback received)

## Other Notes

-
