### ISSUE TITLE
Initial Hospital NBS Interview(s)

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#61]
## Objective

The team needs to better understand the intricacies of newborn screening for a particular hospital, so that our MVP is worth their time to integrate with.

## Acceptance Criteria
- [ ] Based upon feedback from the hospital, we've captured and/or updated stories to guide our MVP implementation.

## Tasks
- [ ] We've conducted one or more interviews with a state hospital.
- [ ] We've documented the needs and challenges of the hospital(s) for newborn screening.
- [ ] Backlog updated based on findings. @JohnNKing

**Comment by JohnNKing** [comment]
Is the same person doing newborn screening in the lab doing other tests? (Asked by Victoria; Sprint 1 Review; 10/31/2022)
