### ISSUE TITLE
AL PHL profile (for data gap analysis) - Orders 

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#618]
# Design or Research

As AL PHL, to ensure we'll receive all needed order data from an EHR, we need to understand how specimen card and LIMS fields relate to the data elements of an electronic order.

## Completion Criteria
- [x] Identified any fields that are missing from current message segments (as confirmed by the PHL)

## Tasks
- [x] Compared specimen card elements to LIMS fields to supposed OML and ORM fields
- [x] Requested PHL feedback on our analysis
- [x] Requested HCO feedback on our analysis
- [x] Capture missing fields in the spreadsheet: Background info [this miro](https://miro.com/app/board/uXjVMaOm3uE=/) table

## Additional Context

Identify fields in currently Make sure fields are included in our ORM/OML  
        * (insurance and medicare) we need to add
        * Are their other fields we have not yet included?
        * Are there other fields that should be required?
            * from Hospital perspective? 
            * For surveillance?
    * Build out a future “unhappy” state for different types of errors
        * No testing happens
            * Patient ID
            * Reject samples for No blood or a baby that is too old
        * 10 Key fields required from the sender that affect results
        * Unsatisfactory (including an expired lab 10 form) samples that may impact our resulting message
        * Remaining fields that are not critical for result calculations

## Notes

- MVP-REQ-12

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-12 - Each Intermediary will provide documentation for minimum data elements for successful transactions  (feeding into gap analysis doc for onboarding)

**Comment by scleary1cs** [comment]
Data Gap Analysis (Shawn):

Review of Oracle content - AL Data Gap Analysis 

(1) For data elements that are NOT currently provided by Oracle, is the element considered essential for downstream PHL processes? 
_Lines:
19: Infant's Age (This will be generated using date of collection/date of birth in Rapsody.) 
32: County (Each could be setup as an individual AOE)
40: Submitter Address (Each could be setup as an individual AOE)
Per Neelima - Yes to all three, but will confirm_ 

(2) Where "yes" - understand path forward between 

(2a) Oracle builds support for element as an AOE or via another mechanism, 
 _(Each could be setup as an individual AOE)_

(2b) understand if element is captured in STAR and can be interfaced to Oracle for inclusion in outbound payload,
_No answer_ 

(2c) understand if data element can be derived by either ReportStream or Flexion and included in outbound order sent to PHL
_Age (19) and Submitter Address (40) could be doable on our side, County (32) would be much more problematic_

Progress of ADPH on Gap Analysis (Excel version)
_Requested and accepted for Neelima and team to fill out BJ - BV on Orders tab_

For Lab/Natus - please take a look at column D on Orders tab and flag all required fields 
_Neelima will take a look_

**Comment by scleary1cs** [comment]
Confirm 19 from Oracle as Date/timestamp filetype.

**Comment by nvcllns** [comment]
Based on 12/12 RS ETOR Program Meeting - key points relevant to gap analysis: (1) ensure that as team learns of data elements that will be part of the electronic payload (even if not an element already on paper order card); add rows so that data element listing is comprehensive of all elements anticipated (e.g., a field that will be transmitted as part of order from EHR); (2) for order elements being requested from EHR - which are recommended to make "required" (hard stop) vs "recommended" (warning) by end-users at the point of data entry?

**Comment by JohnNKing** [comment]
Discussed today with @sfradkin and @scleary1cs. We feel the requirement (MVP-12) has been met based on work to date. Next week, we'll plan to split off subsequent work into new stories.

**Comment by JohnNKing** [comment]
The story split off to cover confirmation with the HCO is https://github.com/CDCgov/trusted-intermediary/issues/992

**Comment by JohnNKing** [comment]
As discussed during Sprint Planning, we've taken this profile work about as far as we can without HCO input. Future stories may be needed if we identify HCO needs that impact the PHL profile.
