### ISSUE TITLE
NBS Order Workflow Discovery

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#62]
## Objective

The team needs to better understand the intricacies of newborn screening for a particular State Public Health Lab (PHL), so that our MVP is worth their time to integrate with.

## Acceptance Criteria
- [x] Based upon feedback from the PHL, we've captured and/or updated stories to guide our MVP implementation.

## Tasks
- [x] Draft a research plan and share with the CDC for feedback - @cjterdi 
- [x] Continue GA PHL research - @cjterdi 
- [x] Learn more about JMC and their work on ETOR - @MikeC-A6 
- [x] Interview Rebecca regarding CDC and NBS labs
- [x] Review Deloitte spreadsheet - @MikeC-A6 
- [x] Receive further details about December travel
- [x] Meet with JMC
- [x] Reviewing CA workflow with Victoria
- [x] Outreach to NBS nurse (Cindy's contact)
- [x] NBS Portal desk research
- [x] Meet with JMC (ideal with former PHL staff)
- [x] Arranging First Public Health Lab interview
- [x] Initial meeting with APHL
- [x] NBS nurse interview - 12-19
- [x] Conduct one or more interviews with a state PHL - TX 12-15
- [x] SME follow-up discussions (e.g. JMC)
- [x] Story mapping sessions to update/improve backlog
- [x] Further interview with Rebecca regarding lab processes (weekly meeting scheduled starting Jan 4)
- [x] Documented the needs and challenges of the PHL for newborn screening
- [x] Revise product narrative based on story mapping @JohnNKing 
- [x] Backlog updated based on findings @JohnNKing 

Move to other stories:
- [ ] Better understand the capabilities of APHL AIMS as it relates to ETOR
