### ISSUE TITLE
For the MVP, there will be a minimum SLA established between each intermediary, the PHLs, and the HCOs.

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#620]
# Story
As a user of CDC ETOR Services, so that I understand how and when issues will be handled, I need a defined agreement outlining what the response times are to issues as they occur

## Acceptance Criteria
- [ ] SLA is written, approved, and implemented

## Tasks
- [x] SLA is drafted 
- [ ] Draft is Approved
- [ ] Index Analytics team is briefed on changes
- [ ] SLA is public facing on ReportStream website

### Research
- [ ] *Research work needed to complete the story*
- [ ] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [ ] *Engineering work needed to complete the story*
- [ ] Foundational: *Technical runway work to support this and future efforts*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*
- MVP-REQ-16

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-16 - For the MVP, there will be a minimum SLA established between each intermediary, the PHLs, and the HCOs

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-16 - For the MVP, there will be a minimum SLA established between each intermediary, the PHLs, and the HCOs

**Comment by nvcllns** [comment]
Preliminary alignment between two-owning CDC groups underway, working draft at: https://cdc-my.sharepoint.com/:w:/g/personal/uwx1_cdc_gov/ESXA2IqobH5HvjNA7W0dVGABgbIB2leXWCMh01DLjD4nrQ?e=4%3A5IglsO&fromShare=true&CID=887D0340-1A0C-4087-8338-7DACA1857EDB&wdLOR=c5138FA04-B90A-4979-BE90-BB658460342B

**Comment by scleary1cs** [comment]
@Adrian-Brewster can we work together on updating this story? Wanting to get this into Sprint 33.

**Comment by Adrian-Brewster** [comment]
The latest update on this is that after determining that the proposed draft SLA has stricter parameters than what the current SLA the Index analytics folks are operating off of, we need CDC approval and implementation of the shorter response times on the Index Analytics contract.  Natalie emailed Tim Best at CDC and has not received a response. Rebecca is going to take over this with hopes that a govie to govie poke will yield better results.

**Comment by scleary1cs** [comment]
Should this be considered blocked?

**Comment by scleary1cs** [comment]
As of 04/16: note from Rebecca on "Weekly CDC RS ETOR Program Meeting : 04/16/2024" call:

-"SLA update (Rebecca, Mo) - Currently in clearance"

**Comment by JohnNKing** [comment]
Discussed with others -- will close for now. We can always re-open or make a new story around SLAs if needed.
