### ISSUE TITLE
Status Badges for Our Repository README

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#626]
# DevEx/OpEx

Add status badges to our readme.  Examples include tests, CI/CD, code coverage, and other workflows.  We could also explore about adding DORA metric as a badge(s).

## Tasks

- [ ] Decide on which [badges](https://shields.io/badges) we want. 
  - [ ] Agreed on CI/CD and SonarCloud (update as needed) 
- [ ] Figure out if we need rate limiting for Shields.
- [ ] Figure out how often we need to update badges

## Additional Context

https://flexion.slack.com/archives/C055XTF22B0/p1683826148320749
