### ISSUE TITLE
Service Blueprint for LA

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#634]
**Design or Research**
As the Intermediary, so that we can understand system impacts and identify risks and opportunities, we need to create a visual overview of how the stakeholders deliver a service (NBS Screening) to a customer, across all channels and touch points. 

**Completion Criteria**
 - [x] Create Service Blueprint Draft for LA 
 (can be leveraged as a template for future implementations in other states)

**Tasks**

  - [x] LA OPH
    - [x] Analyze interviews with LAPHL
    - [x] Create PHL process and detail touch points
    - [x] Interview with Natus to understand LIMS workflow within PHL process
  - [ ] Oschner - 
    - [x] Analyze interview with Carolyne Butler 
    ~~- [ ] Create HCO process and detail touch points~~
  - [x] Create end-to-end data flow overlay
  - [x] Identify areas where ETOR may impact current processes
