### ISSUE TITLE
Results LRIv5 Transformation

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#639]
# Story
As UCSD, so that our EHR can ingest results messages from ReportStream, I need all but one of the  OBR segments removed.

## Pre-conditions
- This transform my apply to either all ORUs sent through the TI service or to just ORUs for CA (whichever is easier)

## Acceptance Criteria
- [x] The OBR for "54089-8" remains unchanged
- [x] All other OBR are removed from the outgoing HL7 ORU message
- [x] All OBXs appear under the sole remaining OBR
- [x] Numeric OBX IDs are sequential and unique

## Tasks
- [x] Assess the ability to use ReportStream's mapping capability to remove the OBRs
- [x] Assess how we could implemented this via the TI service by modifying the results FHIR message
- [x] Implement the easier of the two solutions 
- [x] Test end-to-end flow from initial HL7 to final HL7

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [ ] ~~Testing tasks completed~~
  - [ ] ~~Load tests passed~~ : to be resolved by #1121
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-07 - Each intermediary will support at least one format for inbound results

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-09 - Each intermediary will support at least one format for outbound results

**Comment by JohnNKing** [comment]
Remove or replace with results transformation stories

**Comment by JohnNKing** [comment]
Removing MVP-REQ-07 and MVP-REQ-09 as this story is not needed for basic results handling.

**Comment by dbgolson** [comment]
Itemized list of proposed changes to "flatten" the California DPH ORU results message to better conform to LRI (r5) are detailed in this document.

https://docs.google.com/spreadsheets/d/1TSSPRJdxVde6yG4RDOWYqb-ul4s7JEEv/edit?usp=sharing&ouid=102849307490663018252&rtpof=true&sd=true

**Comment by dbgolson** [comment]
Flattening CDPH's ORU results message to conform with LRI (r5) model:

- Retain x1 OBR segment identified by OBR-4.1 = '54089-8' which is the overarching order code
- Remove all other OBR segments
- Retain ALL OBX segments but number the Set IDs (OBX-2) sequentially now that they will all belong under x1 OBR segment
