### ISSUE TITLE
HL7 ORU => FHIR

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#640]
# Story
As a lab, so that ReportStream can receive NBS results in a format that my LIMS supports, I need ReportStream to accept HL7 NBS ORU messages.

## Pre-conditions
- The incoming ORU is a valid HL7 v2.5.1 message.

## Acceptance Criteria
- [x] An inbound HL7 2.5.1 ORU message can be received successfully by ReportStream.
- [x] A ReportStream receiver is sent the FHIR results message soon afterwards. 

## Tasks
- [x] Test RS HL7 to FHIR conversion locally, using CA's sample ORU (https://github.com/CDCgov/trusted-intermediary/blob/main/examples/hl7/CA/CA%20NBS%20ORU_R01%20Lab%20Result%20Message.txt)
  - [x] Request and test a sample LA ORU message
  - [x] If data is missing, generate a more comprehensive sample FHIR message
  - [x] Reorganize sample files in repo
- [x] Developer Local environment set up
- [x] ReportStream configuration for ETOR receiver and simulated lab sender
- [x] Decide on adding routing to TI now or wait until ETOR /results endpoint is available.
- [x] Decide where transformation will take place (HL7 => FHIR)
- [x] Create translation config in ReportStream
  - [x] Missing fields in fhir translation:
    - `PID.3`: Patient Identifier List
      - `PID.3-4`
    - `NK1.2`: Name
      - `NK1.2-7`
    - `ORC.21`: Ordering Facility Name
      - `ORC.21-10-2`: (is this subfield expected?)
      - `ORC.21-11` (not sure if really missing)
      - `ORC.21-15` (repeated elsewhere?)
      - `ORC.21-16`
      - `ORC.21-19`
    - `OBX.4`: Observation Sub-ID
      - `OBX.4-2` (not sure if really missing)
      - `OBX.4-3` (not sure if really missing)
      - `OBX.29`
- [x] Find out if ReportStream can accept `CE` and `TN` data types for HL7 2.5.1. How much effort would it take for RS to accept does types? 
  - RS doesn't accept `CE` in `OBX.2` because it is assuming `ORU_R01` is in version `2.7` instead of `2.5.1`, even though we're sending version `2.5.1`. This is known bug in RS but we don't know yet when it will be fixed
  - `TN` is not accepted because is not supported in `2.5.1`. `XTN` should be used instead 
- [x] _Now or Future: Consider how to handle integration/integrity tests based upon sample messages_
  - We didn't need to add sample message for integration test in this story because there was no change in the way RS translates  `ORU_R01` messages
- [x] _Future: Consider how we may do results transformations_
- [x] _Future: Consider how we can account for metadata_

### Research
- [ ] *Research work needed to complete the story*
- [ ] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [ ] *Engineering work needed to complete the story*
- [ ] Foundational: *Technical runway work to support this and future efforts*

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-07 - Each intermediary will support at least one format for inbound results
