### ISSUE TITLE
Update TI to handle RS locally in the .env file

### ISSUE THREAD

**Issue by jcrichlake** [CDCgov/trusted-intermediary#649]
# DevEx/OpEx

When running locally we need to programmatically specify whether we are using the report-stream local docker container and order sender OR the local File Sender that imitates report stream.  

## Tasks

- [ ] We could base this off of whether or not the REPORT_STREAM_URL_PREFIX is set to localhost or not. 
- [ ] Update EtorDomainRegistration to conditionally register based on the RS URL Prefix
- [ ] Default to using the localFileOrderSender.
- [ ] Put the variable in the env script(generate_env.sh) twice, one for local, one for RS (For commenting back and forth to easily flip between the 2 options)

**Comment by jcrichlake** [comment]
https://agilesix.slack.com/archives/C055XTF22B0/p1692394743649159

**Comment by tjohnson7021** [comment]
Working branch name `devex/task-649_update_TI_to_handle_RS_locally`
