### ISSUE TITLE
Fix failing DORA metrics weekly run on github

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#653]
# DevEx/OpEx

The DORA metrics weekly Github Action has been failing for the lasts few weeks. We need to find the cause and fix it. 

## Tasks

- [x] Find the cause for the Github Action failure @basiliskus 
- [x] Fix the issue so the weekly runs finish successfully @basiliskus 
- [x] Make sure the Github workflow for Metrics finishes successfully @basiliskus 

## Additional Context

[Here's a direct link to a failing metrics run](https://github.com/CDCgov/trusted-intermediary/actions/runs/6613107732/job/17960293535)

**Comment by basiliskus** [comment]
[Created a bug report for this issue in the devops-deployment-metrics repo](https://github.com/flexion/devops-deployment-metrics/issues/289)

**Comment by basiliskus** [comment]
[Submitted a PR with the fix and got it merged](https://github.com/flexion/devops-deployment-metrics/pull/291)
