### ISSUE TITLE
AL Kickoff

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#654]
# Design or Research

As AL OPH Lab, so that the CDC ETOR team is able to quickly move forward with supporting NBS ETOR, I need the team to prepare for and facilitate several kick-off sessions.

## Completion Criteria

- [x] Kick-off has taken place

## Tasks

- [x] Create and circulate draft current state workflow (via Confluence) for Alabama ahead of site visit (@april-messer, Mary, Cindy)
  - [x] Team session to review of current process flow for AL OPH
- [x] Propose HCD intro to session 1 or session 3 (intro ppt) @april-messer 
- [x] Review pre-read materials
- [x] Engineering.
  - [x] ReportStream Pre-work.
    - [x] Determine PHL organization name and sender/receiver names for RS. - @jcrichlake and @basiliskus 
    - [x] Determine HCO organization name and sender/receiver names for RS. - @jcrichlake and @basiliskus 
    - [x] Create diagram of these senders/receivers and how it flows with RS and the Intermediary. @basiliskus and @jcrichlake 
    - [x] Share diagram with Ott. - @basiliskus and @jcrichlake 
    - [x] PHL organization and sender/receiver are created in RS. -Ott
    - [x] HCO organization and sender/receiver are created in RS. - Ott 
    - [x] Confirm with Ott that hey can attend both technical sessions.
  - [x] Session 6 - PHL.
    - [x] Determine agenda.  Probably similar to LA's session 5 agenda.  Update agenda document.
    - [x] Determine participants.  Update agenda document.
    - [x] Determine pre-read materials.  Update agenda document.
    - [x] Determine what homework and who needs to accomplish it beforehand.
    - [x] Send e-mail to participants.  Mention any homework and who needs to accomplish it.
    - [x] Update kick-off slides.
  - [x] Session 7 - HCO. - @halprin 
    - [x] Determine agenda.  Update agenda document.
    - [x] Determine participants.  Update agenda document.
    - [x] Determine pre-read materials.  Update agenda document.
    - [x] Determine what homework and who needs to accomplish it beforehand.
    - [x] Send e-mail to participants.  Mention any homework and who needs to accomplish it.
    - [x] Update kick-off slides.
- [x] Everyone update their parts of the [Kick-off Agenda Word document](https://cdc.sharepoint.com/:w:/r/teams/OLSS_ETOR_ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B8F746A35-C186-4888-90C2-B92CA75F7BDB%7D&file=Alabama%20On-Site%20Kickoff%20Agenda_Nov15_16.docx&nav=eyJjIjo2NzcxODUzMjB9&action=default&mobileredirect=true).

## Additional Context

Use as a spike. After the kick-off, we'll need to document and plan subsequent work.

**Comment by jcrichlake** [comment]
Posting link of chart that was shared with Ott
https://lucid.app/lucidchart/invitations/accept/inv_ed559a21-e827-4d41-9d52-7c64f99eb935

**Comment by halprin** [comment]
Session 6 Pre-read materials:
- Natus IGs for LOI and LRI.
- [RS Programmer's Guide](https://reportstream.cdc.gov/assets/pdf/ReportStream-Programmers-Guide-v4.1.pdf)
- https://cdctistagingdocs2.z13.web.core.windows.net/toc.html
- End-to-end data flow.  E.g. the diagram reviewed in session 4.
- [Intermediary-specific IG](https://cdctistagingdocs2.z13.web.core.windows.net/toc.html).

**Comment by halprin** [comment]
Session 6 agenda:

Orders:
1. Need to determine whether AL will use a ReST receiver or SFTP receiver.
2. What is the domain name/port of the receiver.  Sub folder or URL we need to use?
3. Determine credentials for this receiver.
4. Update RS receiver.
5. 

Results (if we get stuck with orders):
1. asdf
