### ISSUE TITLE
Epic Demo Access to ReportStream

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#655]
# Backlog Task

Assist Epic in gaining access to ReportStream.

## Completion Criteria

- [x] Epic sender & receiver existing in RS

## Tasks

- [x] Onboard Epic to ReportStream
  - [x] Decide what Epic's organization name will be.
  - [x] Ask Ott to create the organization with a sender of `etor-nbs-orders` and a receiver of `etor-nbs-results`.
  - [x] Organization and sender/receiver created in RS.

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by JohnNKing** [comment]
See https://github.com/CDCgov/prime-reportstream/issues/13001
