### ISSUE TITLE
EHR Order Acknowledgement Technical Constraints

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#663]
# Design or Research

After transmitting an order, what can an EHR receive and what must it receive?

# Completion Criteria
- [ ] Understand what’s needed to stop Epic and Cerner from re-transmitting an order
- [ ] Understand what’s needed for Epic and Cerner to indicate the order was sent successfully.
- [ ] Understand the synchronous ways to provide acknowledgements (and negative acknowledgements) to Epic and Cerner.
- [ ] Understand the asynchronous ways to provide acknowledgements (and negative acknowledgements) to Epic and Cerner.

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the work here.
