### ISSUE TITLE
Determine app service plan and setup auto scaling 

### ISSUE THREAD

**Issue by jcrichlake** [CDCgov/trusted-intermediary#665]
# DevEx/OpEx

We are currently only using the basic app service plan for Azure (Basic B1) It's limited and prevents us from utilizing  autoscaling, staging slots, zone redundancy, vNet integration, and using as much memory,

## Tasks

- [ ] Post findings from Arthur Morrow, he is a member of the cost optimization squad.
- [ ] Select a service plan for the various environments and update the terraform scripts 
- [ ] Setup auto scaling as part of this change. This will require usage data, most likely from report stream. We will also most likely want to have an understanding on what budgetary constraints if any we may have for this from the CDC side.

**Comment by jcrichlake** [comment]
https://slack.com/archives/C055XTF22B0/p1699312818201649

**Comment by scleary1cs** [comment]
Closing as this story is a duplicate of completed story Auto-Scaling our containers #784.
