### ISSUE TITLE
Create Azure Operational Metrics

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#671]
# DevEx/OpEx
We need to be able to monitor the health of the Intermediary system before things become catastrophic.  Monitoring will not include alerting.  

(Some) metrics we are interested in tracking:
- CPU utilization (for apps)
- Memory utilization (for apps)
- Database load
- Autoscaling (number of scaled instances for both apps) 
- HTTP response codes (lots of 500 or 400 codes)
- Execution time for the polling function
**Note: the above list is not exhaustive** 

Create a notion page for documentation or add to the incident response documentation page (resources section). 

This includes both the TI ETOR and SFTP Ingest services.

## Tasks

- [x] Brainstorm if there are additional metrics needed
- [x] Make a dashboard so we can view this information in the Azure portal.
- [x] rename analytics to error logs, instances count to additional instances counts, and more error logs to the top
- [x] Create a dashboard in staging if we defer the terraform into a follow up card.
- [x] Add Production Azure Dashboard Settings to their respective repositories. 

## Additional Context
Note: Infrastructure health monitoring; autoscaling, etc.
