### ISSUE TITLE
Update Onboarding Documentation Research

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#673]
# Design or Research

We need clear NBS use-case specific documentation to streamline onboarding for new partners.

# Completion Criteria

- [x] Understand the similarities and differences between onboarding to ReportStream as a sender vs the Intermediary service as sender & receiver.
- [x] Stories have been created to capture subsequent documentation improvements.

## Tasks

- [x] Understand what documentation already exists
- [x] Determine how to incorporate existing documentation to what we'll be generating
- [x] Determine what type of documentation is required for a new partner PHL or HCO
- [x] Draft proposal of how to augment or diverge from ReportStream documentation
- [x] Draft new stories for future documentation work (based on the proposal)

## Additional Context
- [We have an internal technical draft document for RS onboarding guide](https://docs.google.com/document/d/1m0fPEimrePqXu9Lvu140k7DTrXiyGBwQS59pB-vj_I8/edit?usp=sharing)

**Comment by JohnNKing** [comment]
Related to this story, RS folks would like a better idea of technical support needs for our initial customers -- to help with their capacity planning. (e.g. Lab outbound results, Hospital inbound results, staging => production)

**Comment by nvcllns** [comment]
@scleary1cs or @JohnNKing, I believe this is the right story aligned with topic of wide agreement on today's (11/29) SCRUM, but please redirect me if not! Flagging that written documentation that describes requirements of using RS API (as indicated today, it's not simply the existing RS programmer's guide) will be needed ahead of conversations with California Dept. of Public Health and their target HCO, University of California San Diego. I understand documentation will need to be iterative, but they need a sufficient level of detail at this point to determine "yes - we could connect now" vs "no - additional internal dev needed prior to attempting connection." Sara or I can share other take-aways from the CDPH exploratory call, notes/actions at: https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

Existing specs/tech docs received from CDPH at: https://cdc.sharepoint.com/teams/OLSS_ETOR_ReportStream/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FOLSS%5FETOR%5FReportStream%2FShared%20Documents%2FGeneral%2FETOR%20for%20Newborn%20Screening%2F4%2E%20ReportStream%20Initial%20Implementation%20Coordination%2FCalifornia%2FTechnical%20Documentation&p=true&ga=1

**Comment by Adrian-Brewster** [comment]
Need to update the ReportStream Onboarding Form to include ETOR; Newborn Screening under data type

**Comment by Adrian-Brewster** [comment]
Need to add information for PHLs under Getting Started as a Public Health Agency

**Comment by JohnNKing** [comment]
New stories:
- Need to update the ReportStream Onboarding Form to include ETOR; Newborn Screening under data type
- Need to add information for PHLs under Getting Started as a Public Health Agency
- Need to include ETOR specific workflow in API guide (post initial implementation; does RS want one exhaustive document for all use cases OR separate guides per use case?)
- Need to update onboarding guide or link ETOR onboarding guide (post initial implementation)
