### ISSUE TITLE
AL Service Blueprint

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#684]
**Design or Research**
So that we can communicate ReportSteam ETOR capabilities to our partners effectively (as well as identifying risks and opportunities), we need to create a visual overview of how customers will be able to interact with the intermediary service and how that relates to their processes.

**Completion Criteria**
 - [x] Created and shared the Service Blueprint Draft for AL

**Tasks**
 - [x] Update blueprint based on use of SFTP (for both HCO and PHL) [due 2/15]
    - [x] Also update based on how this will impact error handling
 - [x] Determine how we'll share the blueprint with our customers

**Comment by scleary1cs** [comment]
Reference email "RE: Weekly CDC RS ETOR Program Meeting" - Natalie V. Collins - Nov 21, 2023, 3:05 PM.
For Visio attachment.

**Comment by scleary1cs** [comment]
https://lucid.app/lucidchart/a0aa4f31-3280-4548-9021-b0928ef2c96d/edit?viewport_loc=-888%2C1401%2C4971%2C2175%2CtFtjoHb8YMYT9&invitationId=inv_f1969d2c-5cb5-4ba1-a4a5-c39423e79a12

**Comment by scleary1cs** [comment]
What is the impact of the CA ACK pasthrough to Alabama's desire to have ACK functionality.

**Comment by scleary1cs** [comment]
https://miro.com/app/board/uXjVNbQYtbU=/?share_link_id=170619526977

**Comment by scleary1cs** [comment]
Morgan shared a new workflow on the SME session on 03/07.

**Comment by scleary1cs** [comment]
https://aphlinformatics.atlassian.net/wiki/spaces/ERI/pages/2104068402/Alabama+Documentation+Master+List#AL-Service-Blueprint

**Comment by JohnNKing** [comment]
The service blueprint was previously shared with AL PHL. Our team did an overview of it during the SME call last week. A deep dive is pending (likely during a future SME meeting).

**Comment by JohnNKing** [comment]
New story spun off to cover results: https://github.com/CDCgov/trusted-intermediary/issues/961
