### ISSUE TITLE
Investigate Hospital to Lab Connections

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#70]
## Objective
The team needs to better understand the intricacies of how hospitals and labs transmit electronic orders and results, so that using our MVP will be practical and valuable.

## Tasks
- [ ] Document several examples of connections between Providers and Labs.
- [ ] Document why or why not they're already connected.
- [ ] Learn why some healthcare providers do not utilize ETOR when their lab supports it.
- [ ] Learn if it's costly to set up new EHR connections to labs.
- [ ] Learn if existing connections can instead be setup via ADT
- [x] Learn more about direct secure messaging @JohnNKing
