### ISSUE TITLE
Lab Order Failure Research

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#713]
# Design or Research

To inform the scope and priority of upcoming validation, notification, and acknowledgement stories -- we need to understand the ability of our lab partners to monitor or receive notification of failed orders (e.g. those caused by missing order elements). 

## Completion Criteria
- [x] For LA, determine the minimal effort means of notifying the lab that an order has failed.
- [x] For LA, identify options and preferences for post-MVP notifications.
- [x] For AL, determine the minimal effort means of notifying the lab that an order has failed.
- [x] For AL, identify options and preferences for post-MVP notifications.
- [x] Create a plan and update stories to deliver bare bones notifications for the MVP.

## Tasks
- [x] LA Service Blueprint revisions made and shared with CDC
- [x] Decide on approach and include in service blueprint for LA 
- [x] Identify any security constraints that may limit what can be part of the notification.

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by JohnNKing** [comment]
Discussed during cross collab on 12/11

**Comment by JohnNKing** [comment]
Follow-up with APHL regarding their handling of failure scenarios. Look to more constant approaches post-MVP.

**Comment by JohnNKing** [comment]
MVP Solution: email notifications containing metadata, as called out on the LA service blueprint

Long-term: HL7 ACKs for failures, perhaps dashboard for we defined use cases (e.g. failure/success ratio)
