### ISSUE TITLE
ReportStream Integration Spike

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#72]
## Objective
The team needs to go through the ReportStream Core onboarding process and experiment with routing capabilities, so that we can assess what needs to be done in order to use ReportStream to transmit newborn screen orders.

## Acceptance Criteria
- [ ] We can send a test result to ReportStream Core
- [ ] We've experimented with using ReportStream Core to send a newborn screening order
- [ ] We can receive a test result from ReportStream Core

## Tasks

**Comment by JohnNKing** [comment]
Mentioned as next step for us by Rishi in 2022-11-01 ETOR Architecture Review
