### ISSUE TITLE
Initial Production Deploy and its Approval

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#721]
# Backlog Task

Aquire any approvals we need for our initial deployment to our production environment and then do the production deployment.

## Completion Criteria

- [x] Approval for a production deploy is given.
- [x] Our intermediary is deployed to production.

## Tasks

- [x] Given permission.
- [x] Give GitHub Deployer appropriate permission to deploy to prod environment.
- [x] Create any required Azure bucket's for remote Terraform state.
- [x] Deploy to production.
- [x] Set secrets.

## Other Notes

We are unsure whether we need to get permission from our ISSOs for our initial deployment to production.  
So, we rather be safe than sorry and get permission.  The permission we are seeking is to deploy our application into the production environment _but_ not to process PII or PHI just yet.  Just fake/test data for now.  There's #175 for seeking permission to start handling PHI and PII in our production environment.  With that said, we should reach out to the correct ISSOs, ask for permission, and if given, deploy to production.  If they require us to get approval to handle PHI and PII before any deployment to production occurs, then this backlog item should be scrapped and #175 should be prioritized.

@sfradkin talked with Mo and others about this process.  Looks like we are cleared to deploy to production, but will still need approval to handle PHI and PII.

**Comment by scleary1cs** [comment]
Combine with #175?

**Comment by scleary1cs** [comment]
Combine with #175?

**Comment by halprin** [comment]
Uploaded the secrets.  Only secret that isn't filled in is the `organization-report-stream-public-key-prd`.  That will require ReportStream to onboard us as a receiver in their production and for them to generate public key for us there.
