### ISSUE TITLE
Receiving Orders

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#76]
# Story

As a Hospital, so that my newborn screening order can reach a lab, I need the TI service to be able to receive the order.

## Pre-conditions
- Only a single, fake hospital is supported.
- The order is a mock order.

## Acceptance Criteria
- Orders must be transmitted securely in non-development environments.
- The hospital receives confirmation that the order was successfully received.

## Tasks
- [x] ADRs.
  - [x] Java
  - [x] Gradle - @halprin 
  - [x] Groovy and Spock for testing - @halprin 
  - [x] OeSA - @halprin 
- [x] Basic Linting
- [x] End-to-end tests - @halprin
- [x] CD to at least a Flexion Azure environment - @JohnNKing
  - [x] Terraform - @JohnNKing 
- [x] OeSA application context - @halprin @jorg3lopez 
- [x] OeSA dependency injection - @halprin @jorg3lopez @tjohnson7021 
- [x] Code coverage check for at least 90%. - @halprin 
- [x] Add domain plugin architecture - @halprin
- [x] Add domain endpoint
- [x] SBOM generation - @tjohnson7021 
- [x] Learn more about FHIR - @halprin
- [x] Logging framework - @jorg3lopez 
- [x] Containerize application with docker @jorg3lopez 
  - [x] Docker image @jorg3lopez 
  - [x] Docker-compose @jorg3lopez 
- [x] Ingest an "order" like JSON object for the request. @jorg3lopez 
- [x] Output some kind of acceptance JSON object for the response. @jorg3lopez 

### Engineering
- [x] Threat model updated - @jorg3lopez 
- [x] Code refactored for clarity and no design/technical debt
- [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies.
- [x] Source code is merged to the main branch.
- [x] Unit test coverage of our code >= 90%
- [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer.
- [x] Build process updated
- [x] Feature toggles created and/or deleted.  Document the feature toggle.
- [x] Source code documentation created when the code is not self-documenting. - @tjohnson7021 
- [x] API documentation generated
- [x] Code quality checks passed
- [x] Security & privacy gates passed
- [x] Load tests passed - @tjohnson7021 
- [x] Documentation and diagrams created or updated - @jorg3lopez 
- [x] API(s) are versioned
- [x] Debug logging - @jorg3lopez

**Comment by JohnNKing** [comment]
# Story

As a Hospital, so that my newborn screening order can reach a lab, I need the TI service to be able to receive the order.

## Pre-conditions
- Only a single, fake hospital is supported.

## Acceptance Criteria (Post-conditions)
- Orders must be transmitted securely in non-development environments.
- The hospital receives confirmation that the order was successfully received.

## Tasks

- [ ] 

## Definition of Done

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-44 - Each intermediary will implement data encryption measures for both data-at-rest and data-in-transit
