### ISSUE TITLE
File Organization 

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#774]
# DevEx/OpEx

Create a folder structure that is aligned in Notion and Google Drive

## Tasks
- [ ] Set up the main folder structure in Google Drive, including subfolders for each department (Product, Customer Experience, Engineering, Research).
- [ ] Create a separate folder for externally shared documents with edit permissions, to be used by team members as needed.
- [ ] Rename files in accordance with the template provided in the Miro board for organizational purposes.
- [ ] Reconcile the existing documents and files in Notion with the folder structure in Google Drive, ensuring they match each other.
- [ ] Complete the build-out of  "About Me" section for onboarding new team members.
- [ ] Populate the "Product" section in Notion with relevant documents and resources.
- [ ] Populate the "Customer Experience" section in Notion with relevant documents and resources.
- [ ] Populate the "Engineering" section in Notion with relevant documents and resources.
- [ ] Populate the "Research" section in Notion with relevant documents and resources.
- [ ] Develop a plan to maintain the organization and structure of Notion and G-Drive going forward.

**Comment by april-messer** [comment]
work in progress on miro board 'team organization' for reference
