### ISSUE TITLE
Team Intro Presentation

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#776]
# DevEx/OpEx

As a team member, I want to create a Team Intro Presentation to explain our process and the intermediary's functionality, in order to provide a clear understanding of our work and attract potential collaborators.
.

## Tasks
- [ ]Research: Gather information about the intermediary's functionality and flexion process.
- [ ]Content Creation: Develop a simple and engaging introductory section for the presentation. Potential Chapters:
     1. Introduction to CDC Intermediary Services
     2. Introduction to Newborn Screening via CDC Intermediary
     3. Evergreen Service Blueprint walkthrough
     4. Getting Started (Steps for onboarding)
     5. Engineering Guide Walkthrough
     6. What makes a passable message?
     7. Steps for connecting via the various transports
     8. What if I can’t connect via REST 
     9. How can I validate message structure/content?
     10. Using the ReportStream Message validator tool
- [ ]Animation: Create an animated sequence inspired by the Astroboy movie to visually demonstrate how the intermediary works.
- [ ]Recording: Record short sections of the presentation to be included in a YouTube video.
- [ ]Editing: Edit the recorded sections and combine them with the animated sequence to create a cohesive presentation.
- [ ]Review and Feedback: Share the presentation with the team for feedback and incorporate any necessary changes.
- [ ]Finalize: Make final adjustments, refine the presentation, and prepare it for delivery as a deliverable.
- [ ]Delivery: Share the Team Intro Presentation with relevant stakeholders.
- [ ]Documentation: Document the process and update any necessary documentation to reflect the creation of the Team Intro Presentation.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by scleary1cs** [comment]
- [ ]Research: Gather information about the intermediary's functionality and flexion process.
- [ ]Content Creation: Develop a simple and engaging introductory section for the presentation. Potential Chapters:
     1. Introduction to CDC Intermediary Services
     2. Introduction to Newborn Screening via CDC Intermediary
     3. Evergreen Service Blueprint walkthrough
     4. Getting Started (Steps for onboarding)
     5. Engineering Guide Walkthrough
     6. What makes a passable message?
     7. Steps for connecting via the various transports
     8. What if I can’t connect via REST 
     9. How can I validate message structure/content?
     10. Using the ReportStream Message validator tool
- [ ]Animation: Create an animated sequence inspired by the Astroboy movie to visually demonstrate how the intermediary works.
- [ ]Recording: Record short sections of the presentation to be included in a YouTube video.
- [ ]Editing: Edit the recorded sections and combine them with the animated sequence to create a cohesive presentation.
- [ ]Review and Feedback: Share the presentation with the team for feedback and incorporate any necessary changes.
- [ ]Finalize: Make final adjustments, refine the presentation, and prepare it for delivery as a deliverable.
- [ ]Delivery: Share the Team Intro Presentation with relevant stakeholders.
- [ ]Documentation: Document the process and update any necessary documentation to reflect the creation of the Team Intro Presentation.

**Comment by scleary1cs** [comment]
CDC-ReportStream-Intermediary-Demo-2023-08-10:
https://drive.google.com/file/d/1k7JZ3j2A6nkdRADfaHIkiZNSZbrCaiaW/view?usp=drive_link

**Comment by scleary1cs** [comment]
LA Kickoff in Miro:
https://miro.com/app/board/uXjVMpo61Ys=/?share_link_id=179526034010

**Comment by scleary1cs** [comment]
Demo Script:
https://docs.google.com/document/d/1QESxFgfRYT-iwaitZ9fQcKKIagRdvrpLoBWMzHZZcCk/edit#heading=h.ilxd8l842vk2
