### ISSUE TITLE
Results Research

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#777]
# Design or Research

Consolidate and document results handling sample messages from all resources per state.

## Tasks
- [ ] NBS not generic
- [ ] 2.5.1 only (not 2.3)
- [ ] Epic version vs natus version - compare differences per state
- [ ] Oracle/Cerner version vs natus version - compare differences per state
- [ ] Data types and LOINC codes (what is the impact)

## Additional Context

Add any other context or screenshots about the work here.

**Comment by eaugustini** [comment]
Link to backwards compatibility data types research: https://docs.google.com/spreadsheets/d/1KwuWj6tEAnyv2hIpDisQKaL5gO45aIwo/edit?usp=drive_link&ouid=107331543436937534358&rtpof=true&sd=true

**Comment by JohnNKing** [comment]
I'm planning to raise data type support with the ReportStream folks tomorrow during our architecture sync

**Comment by JohnNKing** [comment]
Determine level of effort to support CE datatype in ReportStream. Also, perhaps, TN (though that one is deprecated)

**Comment by JohnNKing** [comment]
@JohnNKing 
1. Add TN support to 2.3 story
2. Create new story covering data lose identified in spreadsheet

**Comment by JohnNKing** [comment]
1. Added TN to AC of https://github.com/CDCgov/trusted-intermediary/issues/658
2. Created: https://github.com/CDCgov/trusted-intermediary/issues/905
