### ISSUE TITLE
Auto-Scaling our containers 

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#784]
# Backlog Task

Make sure our application can scale up the number containers and scale down the number of containers based on need.

## Completion Criteria

- [x] Scale up heuristic is implemented 
- [x] Scale down heuristic is implemented 
- [x] In Staging and Production, we need to have a minimum of two containers

## Tasks
- [x] To allow for auto-scaling, we need to change our app service plan off of the Basic tier
- [x] Turn on multi-zone availability, set minimum # of instances to 3  
- [x] Identify heuristic we want to use for our solution
- [x] Make sure we have margin between our scale up and scale down metrics.  For example avoid the following scenario: Scale up when average CPU is 50 percent and scale down when average CPU is 25 percent.  This leads to scaling instance back and forth once we initially scale.
- [x] Establish a floor of 3 instances
- [x] Add logic to differentiate options between local/internal vs staging/prod 

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by scleary1cs** [comment]
Upgrade from free tier service plan.
