### ISSUE TITLE
Put our application inside of a private VNET

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#786]
# Backlog Task

Put our application inside of a private VNET

## Completion Criteria

- [x] RS can still call the ETOR service
- [x] The ETOR service can still call report stream
- [x] We can no longer call our deployed instances from the public internet
- [x] Relevant Azure infrastructure exists inside the same private VNET for the ETOR service 

## Tasks

- [x] Add existing cdc vnet to terraform
- [x] Add private DNS zone
- [x] And DNS link for vnet to DNS
- [x] Push changes to DEV branch and have them deploy
- [x] Validate changes in DEV
- [x] Codify our recent changes in Terraform (default DNS on VNET, don't assign route table, and don't assign security group)
- [x] In Terraform create a new security group with the same settings as the existing security group, but only allow 5432 from inside the VNET, assign to database subnet.
  - [x] Figure out how to have the security group rules set to merge together.  Currently any deploy of the dev branch scrubs any manually added security group rules.  
- [x] In Terraform create a new security group with the same settings as the existing security group, but only allow 80 and 443 from inside the VNET (not from the Internet), assign to app subnet.
- [x] Investigate how we can allow RS to call our API.  Private endpoint?  Peering VNET?
- [x] Investigate how we can run Liquibase against our database.  VPN/SSH tunnel?  Bastion/VM?  For a moment, we make the database available on the Internet?
- [x] Document all the things we've learned about setting up and running a VPN
- [x] Update Github Action for rollback to include VPN and no longer rely upon the liquibase GitHub action
- [x] Add private DNS Resolver and needed endpoints into the terraform
- [x] Ensure our Internal and PR environments will continue to deploy.  We chose to not do all this VNET stuff for them.
- [x] Re-fix the db_rollback.yml to choose the certificates by environment
- [x] Propagate changes into environments above dev in the cdc space
  - [x] Create new VPN root certificates for each environment.  Store in Keybase.
  - [x] Create new VPN certificate and private key for GitHub action.  Store in Keybase.
  - [x] Scrape VPN settings from `stg` after initial deploy.  Add to environment secrets.
  - [x] Scrape VPN settings from `prd` after initial deploy.  Add to environment secrets.
- [x] Update threat model? @halprin 
- [x] Make a new Root certificate that aren't a developers,  do this for Dev, Staging, and Prod
  - [x] Upload certs to keybase 
- [x] Schedule meeting with dev team to go over changes and ensure everyone has the set up they need, especially for any sort of debugging/production support?

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by scleary1cs** [comment]
Static IP vs DNS Name?

**Comment by jcrichlake** [comment]
In regards to the item around re-establishing the connection to report stream there are some decisions/ permissions that are pending.  

1. I believe previously we were calling report stream over the public internet and also allowing them to call us the same way.  The intermediary is no longer public due to being moved to a vnet, the question becomes do we make a call back out to the web or do we try and establish a private connection the RS resources inside of Azure.  
   
I think we want to keep the calls private if at all possible. BUT I don't think any other developer sans (maybe) Peter has access to the ReportStream resources in the CDC Azure space. 

We also may need to discuss this with the ReportStream team as we'd be opening up part of their private network to establish communications in the private cloud spaces

**Comment by scleary1cs** [comment]
What documentation is needed for this story to be considered complete?

**Comment by jcrichlake** [comment]
@scleary1cs 

- [ ]  Add what we can to inside the repo
    - [ ]  Private DNS Resolvers in terraform
    - [ ]  [VPN script](https://github.com/andrewgdotcom/openvpn-mac-dns/blob/master/etc/openvpn/update-resolv-conf) for github
    - [ ]  [VPN script](https://github.com/andrewgdotcom/openvpn-mac-dns/blob/master/etc/openvpn/update-resolv-conf) for devs
    - [ ]  Additional gateways?
- Document the certificate creation process ([followed this link](https://learn.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-certificates-point-to-site-linux))
    - Update onboarding documentation for openssl/strongswan
- Update onboarding docs for certs needed for each environment
- Document for actually connecting using the vpn
- Update database readme in repo to account for new steps for connecting

**Comment by jcrichlake** [comment]
Update threat model?
