### ISSUE TITLE
Baptist / Oracle Access to ReportStream

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#788]
# Backlog Task

Assist Baptist, via Oracle RLN, in gaining access to ReportStream.

## Completion Criteria

- [x] Baptist sender & receiver exists in RS

## Tasks

- [x] Request new sender & receiver from ReportStream
- [x] Organization and sender/receiver created in RS.
- [x] Shared key shared with Oracle securly
- [x] Sample curl command shared
