### ISSUE TITLE
CA CDPH Engagement Prep

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#801]
# Discovery

Compile information from meetings held with CDPH for cross collab team to conduct an assessment of capabilities, to understand what information and documentation we are missing or need to be ready to engage as soon as we are able.

## Tasks
Notion/G-drive
- [ ]  links to CA confluence site (when available)
- [ ]  links/repository of documents and questions that have been shared so far
Miro
- [ ]  Miro board for further research and collaboration 
- [ ]  schedule team meeting to discuss

## Additional Context

Add any other context or screenshots about the work here.
[Miro board for research: ](https://miro.com/app/board/uXjVMaOm3vI=/?share_link_id=828703736105)

[Data Gap spreadsheet: ](https://docs.google.com/spreadsheets/d/1w03qjifcNnSyAFxai36KVrzIk3sQlzyUczv05ofC5R0/edit#gid=162892000)
