### ISSUE TITLE
AL: PHL Results Staging Connectivity

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#829]
# Story
As ADPH, so that NBS findings can be distributed to AL hospitals connected to ReportStream, I need ReportStream staging to be able to collect results messages.

## Pre-conditions
- Out of scope: production connectivity
- ReportStream/TI already supports SFTP ingestion of results messages
- We need the URL(s) for their SFTP server
- How should we connect (User/Pass+Keys, User+Keys)?
- What are our connecting credentials? 
- What is the expected Polling schedule?
- We've manually connected the SFTP server
- Public/Private key generated by us

## Acceptance Criteria
- [ ] A sample ORU message placed in the test SFTP directory is collected and ingested by ReportStream staging.
- [ ] Results messages are transmitted securely.

## Tasks
- [ ] Help the PHL to overcome SFTP connectivity issues
- [ ] Test result collection via SFTP
- [ ] Testing staging connectivity via SFTP
- [ ] Test end-to-end flow

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
AL no longer an initial implementation partner.
