### ISSUE TITLE
CA: CDPH Results Production Connectivity

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#833]
# Story
As CDPH, so that NBS findings can be distributed to CA hospitals connected to ReportStream, I need ReportStream to be able to collect results messages in production.

## Pre-conditions
- ReportStream/TI already supports SFTP ingestion of results messages

## Acceptance Criteria
- [x] A sample ORU message placed in the SFTP directory is collected and ingested by ReportStream production.
- [x] Results messages are transmitted securely.

## Tasks
- [x] Receive production SFTP credentials using a secure connection
- [x] Verify removal of files from SFTP after collection
- [x] Verify ReportStream production receipt of messages

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
@sfradkin heads up, we closed this story during sprint planning.  Just wanted you to have a reporting heads up, in case it changes your reporting.
