### ISSUE TITLE
CA: CDPH Results Staging Connectivity

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#834]
# Story
As CDPH, so that NBS findings can be distributed to CA hospitals connected to ReportStream, I need ReportStream staging to be able to collect results messages.

## Pre-conditions
- Out of scope: production connectivity
- ReportStream/TI already supports SFTP ingestion of results messages

## Acceptance Criteria
- [x] A sample ORU message placed in the test SFTP directory is collected and ingested by ReportStream staging.
- [x] Results messages are transmitted securely.

## Tasks
- [x] Receive test SFTP credentials using a secure connection 
- [x] Test collection via SFTP
- [x] Test decryption and decompression of message files
- [x] Ask of CDPH if TN data type (post discharge provider telephone number), instead be sent as ST, TX, or XTN (learned on 8/7 that related OBX not sent)
- [x] Register public key for SFTP
- [x] Test removal of files after collection
- [x] Configure a sender for CDPH (or is this for the SFTP ingest service?)
- [x] Testing staging connectivity for SFTP ingest via REST
- [x] Test end-to-end flow

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
Blocked pending CDPH access and SFTP ingest work

**Comment by JohnNKing** [comment]
To confirm:
* Can TN data type (post discharge provider telephone number), instead be sent as ST, TX, or XTN?

**Comment by JohnNKing** [comment]
> To confirm:
> 
> * Can TN data type (post discharge provider telephone number), instead be sent as ST, TX, or XTN?

We found that TN would not be sent in actual results messages. (We tested and confirmed that's true even if the order includes a post discharge provider telephone number [as an ST data type, IIRC]). The TN we saw was just an erroneous artifact of the results generator web tool.

**Comment by JohnNKing** [comment]
@JohnNKing To follow up with Stream 1; presumably this can be closed

**Comment by JohnNKing** [comment]
@scleary1cs Was this one discussed during Stream 1 planning? Do you know if this can indeed be closed out?

**Comment by scleary1cs** [comment]
I believe this can be closed @JohnNKing
