### ISSUE TITLE
ReportStream ORM Conversion Tests

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#841]
# DevEx/OpEx

Implement tests in ReportStream to avoid ORM conversion failures in the future. See: https://github.com/CDCgov/trusted-intermediary/issues/815

Discussed during Engineering Block on 2/2/2024

## Tasks
- [ ] Add TI-Staging tests to alert us if something breaks
- [ ] Pact testing
    - [ ] Add RS GitHub checks
    - [ ] Discuss Pact testing with RS
- [ ] Something. Something. Something. Something.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by JohnNKing** [comment]
My understanding is ReportStream has ORM conversion tests, but they the expected output was updated incorrectly. Replacing this effort with https://github.com/CDCgov/trusted-intermediary/issues/1255.
