### ISSUE TITLE
Onboarding Journey Documentation

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#861]
# Story
As a partner hospital or lab, in order to better understand the onboarding process, I need a visual representation of how the onboarding process works and where I'm at within it.

## Pre-conditions
- Post MVP partner onboarding will rely on the same mechanisms as used by initial partners (i.e. newly discovered partner requirements need not be considered in scope of this story)

## Acceptance Criteria
- [x] We have two separate workflow diagrams that outline the user journey, one for HCOs and one for PHLs, for onboarding to RS ETOR.
- [x] We've created a process for capturing onboarding activities within the backlog (which aligns to the visual representation in the AC above).

## Tasks

- [ ] share out miro board with team
- [ ] collab session
- [ ] other tasks?

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by Adrian-Brewster** [comment]
I will pick this back up this sprint
