### ISSUE TITLE
Upgrade Hapi FHIR libraries to V7

### ISSUE THREAD

**Issue by jcrichlake** [CDCgov/trusted-intermediary#875]
# DevEx/OpEx

V7 of the Hapi FHIR libraries was just released.  Sadly there are no changelogs to go with these major version upgrades.  This item is to perform the upgrade locally and run tests

implementation 'ca.uhn.hapi.fhir:hapi-fhir-validation-resources-r4:7.0.0'
api 'ca.uhn.hapi.fhir:hapi-fhir-structures-r4:7.0.0
implementation 'ca.uhn.hapi.fhir:hapi-fhir-caching-caffeine:7.0.0'
api 'ca.uhn.hapi.fhir:hapi-fhir-base:7.0.0'

## Tasks

- [x] Upgrade the 4 libraries above in the project to version 7
- [x] Run manual tests against the various endpoints locally, validate the results went through
- [x] Run e2e tests, validate
- [x] Run unit tests, validate
- [x] Run load tests, validate

## Additional Context

Add any other context or screenshots about the work here.
