### ISSUE TITLE
Decision Log

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#876]
# Backlog Task

Decision Log

## Completion Criteria

- [ ] We know what form the decision log will be in
- [ ] We have documented a short process for determining what things need to be in the decision log
- [ ] Decision log is created

## Tasks

- [ ] What tasks need to be done to fulfill the completion criteria?

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by nvcllns** [comment]
**Suggestion:** Mobilize on @Adrian-Brewster 's idea to leverage Smartsheets (now that licenses have been granted from CDC to Flexion team...or are immediately on the horizon.) Mobilize to create a full RAID log that is the single source of truth for the full program, use reports/dashboards so site users could 'view' their respective content. 

[https://cdc.sharepoint.com/:x:/r/teams/OLSS_ETOR_ReportStream/Shared%20Documents/General/ETOR%20for%20Newborn%20Screening/3.%20ReportStream%20Implementation%20Support%20(Technical%20Assistance)/Phase%200/0.24%20RAID%20(Risk%20Issue)%20Log/ETOR%20ReportStream%20Program_RAID%20Log.xlsx?d=wc911bdb902cc416fbc4f3dccdbc275b5&csf=1&web=1&e=aD4fvc]
