### ISSUE TITLE
Epic Test Integration

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#896]
# Story
As Epic, so that LA and other Epic customers can send NBS orders and receive results, I need bidirectional ReST communication established with ReportStream.

## Pre-conditions
- Epic has been onboarded as a ReportStream sender and receiver

## Acceptance Criteria
- [x] Sample ORM orders submitted by Epic can be delivered to our simulated lab receiver in ReportStream.
- [x] Sample ORU results can be sent through ReportStream and arrive in Epic's demo environment.

## Tasks
- [x] Arrange weekly meetings w/ Oracle and RS
- [x] Epic able to send test ORM 2.5.1 messages
- [x] Epic able to received ORU 2.5.1 messages (Epic middleware dependency discussed on 4/15; that's likely what's currently preventing this from working)
- [x] Share UCSD results findings - @JohnNKing 
- [x] Epic able to file/ingest test results message
- [ ] ~~ReportStream able to authenticate via OAuth2~~

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*
