### ISSUE TITLE
CA Data Gap Analysis - Results

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#955]
# Story
As CA HCO, to ensure we'll receive all needed results data to an EHR, we need to relate the ReportStream results information to what will be received by the EHR.

## Pre-conditions
- none

## Acceptance Criteria
- [x] Message profiles are now finalized
- [x] Publish list of transformation requirements for Intermediary
- [x] Get approvals
- [x] Create explicit stories for Intermediary transformation requirements

## Tasks
- [x] Identify and document which transformations may be needed for other CA hospitals.
- [x] Discuss feasibility of using ORC field to update MSH
- [x] Draft side-by-side comparison of sender & receiver profiles
- [x] Finalize side-by-side comparison of sender & receiver profiles
- [x] Identify/highlight differences (gaps)
- [x] Confirm gap solutions (3 possible actions)
  - [x] 1. Sender will update configurations/message mappings to align with receiver profile
  - [x] 2. Receiver will update message processing to align with sender profile
  - [x] 3. Intermediary will transform/translate messages mid-stream to alleviate burden on sender & receiver
- [x] Update message profiles (if sender or receiver are making changes to accommodate)

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
Potential 3 distinct categories for transformations:
1. Unique UCSD transformation needs
2. Potential transformation needs for other CA HCOs
3. Transformations needed for LRIv5 (i.e. flattening)

**Comment by JohnNKing** [comment]
Receiving facility MSH header may need to be conditional -- as there are two separate facilities within UCSD. (FYI @jorg3lopez )

**Comment by JohnNKing** [comment]
To be discussed during team collab later today

**Comment by JohnNKing** [comment]
Calling complete based on the transformation work being done, and decoupling from the open vocabulary items impacting the profile work.
