### ISSUE TITLE
AL HCO Results Profile

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#957]
# Story
As AL HCO, to ensure we'll receive all needed results data to an EHR, we need to relate the ReportStream results information to what will be received by the EHR.

## Pre-conditions
- none

## Acceptance Criteria
- [x]  Approved message profile

## Tasks
- [x] Obtain publish message profile (if available)
- [x] Obtain sample messages
- [x] Document data elements of interest
  - [x] Optionality
  - [x] Cardinality
  - [x] Vocabulary requirements
- [x] Requested HCO feedback on our analysis
- [x] Confirm baseline profile requirements with Sender

### Research
- [ ] *Research work needed to complete the story*
- [ ] Foundational: *High-level research that will support this and future efforts*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by cjterdi** [comment]
Blocked: Test order analysis still in progress

**Comment by JohnNKing** [comment]
Partly blocked waiting on PLT codes

**Comment by JScott-JMC** [comment]
Still waiting to close out HCO feedback on the current data/vocabulary profile draft.  Final closure will likely come in concert with the initial round-trip test cycle.

**Comment by JScott-JMC** [comment]
Knowledge transfer is complete for handover of the AL engagement to the DETOR team.  This story can be closed.

@JohnNKing

**Comment by scleary1cs** [comment]
Moved to done.
