### ISSUE TITLE
AL Service Blueprint: Results Flow

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#961]
# Design or Research

Improve the AL Service Blueprint to include the results data flow.

## Completion Criteria

- [x] The AL service blueprint includes results handling and accurately represents what AL PHL, Baptist, & Oracle requires.

## Tasks

- [x] We've updated the service blueprint to show the results flow
- [x] Review current version of the blueprint
- [x] Update based on ACK flow
- [x] We've walked through the updated blueprint with AL PHL, Baptist, & Oracle and addressed any questions
- [x] Static copy exported, uploaded to Confluence, and shared with CDC and partners
- [x] Update based on PHL feedback (e.g. ACK/NAK flow)
- [x] Note this as Future State in the diagram
- [x] Export diagram and update Confluence
- [x] Once more request PHL feedback
- [ ] ~~Once more request Oracle feedback~~

## Additional Context

Add any other context or screenshots about the work here.

**Comment by JohnNKing** [comment]
Discussing during Team Collab later today
