### ISSUE TITLE
Inbound OML Accepted by ReportStream

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#962]
# Backlog Task

Add foundational support inbound OML for ReportStream so that we can unblock integration testing with Oracle.

## Completion Criteria

- [x] OML_O21 messages sent to ReportStream no longer result in an error

## Tasks
- [x] Add OML_O21 to the list of that messages are tested against
- [x] Add unit tests
- [x] Add integration tests
- [x] Merge PR https://github.com/CDCgov/prime-reportstream/pull/13766

## Other Notes
n/a
