### ISSUE TITLE
CA Kickoff

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#963]
# Discovery

As CDPH Lab, so that the CDC ETOR team is able to quickly move forward with supporting NBS ETOR, I need the team to prepare for and facilitate several kick-off sessions.

## Completion Criteria

- [x] Reviewed the site profile
  - [x] Generated a set of follow-up technical questions (e.g. ciphers, encryption reqs)
- [x] Kick-off has taken place
- [x] Reviewed onboarding guide (starting from just a template)
- [x] Reviewed onboarding flow (starting from just a template)
- [x] Introduced service blueprint
- [x] Introduced data gap analysis
- [x] Discussed current state workflow
- [x] Determine topics for initial SME sessions
- [x] Key contacts determined
- [x] Meeting cadence established

## Tasks
- [x] Internal knowledge share meeting to bring team up to speed on CA
- [x] Determine what topics and sessions will be a part of the kick-off
- [x] Identify who will be attending the kick-off from our team

**_(Updates needed; below is copied from the AL Kickoff)_**
- [ ] Create and circulate draft current state workflow (via Confluence) for California ahead of site visit 
  - [ ] Team session to review of current process flow for CDPH
- [ ] Propose HCD intro to session 1 or session 3 (intro ppt)
- [ ] Review pre-read materials
- [ ] Engineering.
  - [ ] ReportStream Pre-work.
    - [ ] Determine PHL organization name and sender/receiver names for RS.
    - [ ] Determine HCO organization name and sender/receiver names for RS.
    - [ ] Create diagram of these senders/receivers and how it flows with RS and the Intermediary.
    - [ ] Share diagram with Ott.
    - [ ] PHL organization and sender/receiver are created in RS. -Ott
    - [ ] HCO organization and sender/receiver are created in RS. - Ott 
    - [ ] Confirm with Ott that hey can attend both technical sessions.
  - [ ] Session 6 - PHL.
    - [ ] Determine agenda.  Probably similar to LA's session 5 agenda.  Update agenda document.
    - [ ] Determine participants.  Update agenda document.
    - [ ] Determine pre-read materials.  Update agenda document.
    - [ ] Determine what homework and who needs to accomplish it beforehand.
    - [ ] Send e-mail to participants.  Mention any homework and who needs to accomplish it.
    - [ ] Update kick-off slides.
  - [ ] Session 7 - HCO.
    - [ ] Determine agenda.  Update agenda document.
    - [ ] Determine participants.  Update agenda document.
    - [ ] Determine pre-read materials.  Update agenda document.
    - [ ] Determine what homework and who needs to accomplish it beforehand.
    - [ ] Send e-mail to participants.  Mention any homework and who needs to accomplish it.
    - [ ] Update kick-off slides.

## Additional Context

Use as a spike. After the kick-off, we'll need to document and plan subsequent work.

**Comment by scleary1cs** [comment]
https://aphlinformatics.atlassian.net/wiki/spaces/ERI/pages/2165997854/California+Documentation+Master+List

**Comment by scleary1cs** [comment]
https://drive.google.com/file/d/1ANhon8xp9Xm8pb8xGOv3HMU4_PLuVvSz/view

**Comment by JohnNKing** [comment]
Thoughts on this story? Should this be closed out? (@Adrian-Brewster)

**Comment by scleary1cs** [comment]
https://aphlinformatics.atlassian.net/wiki/spaces/ERI/pages/2165997710/California+Site+Implementation+Team+Contact+List
