### ISSUE TITLE
AL NBS Result Test Scenarios

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#964]
# Story
As a PHL or HCO, so that we're confident the various branches of our workflows will work under ETOR, develop a set of scenarios and sample data to be used for testing NBS results.

## Pre-conditions
- AL NBS Order tests scenarios created

## Acceptance Criteria
- [x] Test scenarios are documented
- [x] Sample messages for each scenario have been created and shared with the team

## Tasks
- [x] Brainstorm scenarios (reach out to partners, find out if any test scenarios currently exist)
- [x] Build out additional scenarios
- [x] Get more sample results for scenarios we've identified 
- [x] Document sample messages stored in GitHub

### Research
- [x] *Research work needed to complete the story*
- [x] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [x] *Engineering work needed to complete the story*
- [x] Foundational: *Technical runway work to support this and future efforts*

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- What edge cases should we consider or not? (e.g. maternal deaths, surrogate mothers)

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- Future work likely will be needed to adapt these scenarios per state partner.
- This isn't a final set of scenarios; we should expect more in the future

**Comment by scleary1cs** [comment]
https://docs.google.com/spreadsheets/d/10xxPKrQsfx6hi81KwvNCfedgEAf-xqnx/edit#gid=791322348
