### ISSUE TITLE
Alabama: ReportStream to Oracle

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#966]
# Backlog Task

Perform integration testing for results flowing from ReportStream to Oracle RLN.

## Completion Criteria

- [ ] ReportStream staging is able to send sample results messages to Oracle RLN.
- [ ] Oracle RLN successfully receives the sample result messages.

## Tasks

- [x] Developer guide received from Oracle
- [x] Received credentials from Oracle
- [x] Developer IP added to Oracle whitelist
- [x] Test result messages submitted successfully via Postman
- [x] Test result messages do not result in an HTTP error
- [x] ReportStream staging is whitelisted
  - [x] Arrange meeting to solve issue with range of IPs used by RS (CIDR block) - @JohnNKing 
- [ ] ReportStream staging configured to send results to Oracle
- [ ] Staging testing completed

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by JohnNKing** [comment]
Blocked waiting in being added to IP whitelist

**Comment by JohnNKing** [comment]
Confirmed network connectivity to Oracle RLN staging and production; authentication and results submission previously confirmed in staging / non-prod.

**Comment by JohnNKing** [comment]
Note: Access to non-prod RLN is still constrained by IP allow rules

**Comment by JohnNKing** [comment]
Same status as https://github.com/CDCgov/trusted-intermediary/issues/830

**Comment by Adrian-Brewster** [comment]
Given the testing that took place last week, should this be considered complete? @JohnNKing

**Comment by JohnNKing** [comment]
Closing as this is no longer relevant. There is ongoing follow-up with Oracle to confirm the sample results were received, but we suspect that they were.
