### ISSUE TITLE
Use an Official CDC Snyk Organization

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#975]
# DevEx/OpEx

Today we use @halprin's personal Snyk organization to do SCA (dependency vulnerability) scanning or our repository.  This isn't a maintainable solution.  @halprin's shouldn't be using their personal organization for an official CDC project.  Move our repository to be scanned by a more official Snyk organization.

## Tasks

- [x] ~~Discover if there is already a more official CDC Snyk organization.~~ There isn't. 
- [x] Coordinate with Boris on creating one
- [x] Migrate Snyk accounts
  - [x] Add users
  - [x] Setup scanning
  - [x] Ensure alerts match
 - [x] Teardown halprin 

## Additional Context

We may need to engage Boris at the CDC.  He may know.

**Comment by pluckyswan** [comment]
I've sent an email to Boris asking if an official account exists and if not the steps required to get one up.
