### ISSUE TITLE
Sender/Receiver Metadata HL7 Format

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#990]
# Story
As a hospital or lab, so I know the original sender/receiver of the message I need metadata to include the sending/receiving facilities in the HL7 message.

## Pre-conditions
- NA

## Acceptance Criteria
- [x] The sender in the metadata uses data from the message itself.
- [x] The receiver in the metadata uses data from the message itself.

## Tasks
- [x] Create a new branch "story-990/sender-receiver-metadata"

### Research
- [x] *Research work needed to complete the story*
- [x] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [x] Work for `PartnerMetaData.java`
  - [x] Remove `sender` param
  - [x] Remove `receiver` param
  - [x] Fix any unit test that fails due to the changes
- [x] Work for `PartnerMetadataOrchestrator.java`
  - [x] Remove sender and all its occurrences from PartnerMetaData.
  - [x] Remove receiver and all its occurrences from PartnerMetaData.
  - [x] Replace history endpoint with the above values
- [x] Update test cases in PartnerMetadataOrchestratorTest
- [x] Work for `HapiPartnerMetadataConverter.java`
  - [x] Make appropriate changes to reflect the work from `PartnerMetaData`
  - [x] Verify all unit tests pass
- [x] work in PostgresDaoTest
  - [x] Make appropriate changes to reflect the work from `PartnerMetaData`
  - [x] Verify all unit tests pass
- [x] Work for Database
  - [x] delete `sender` and `receiver` colunms
  - [x] Test metadata gets recorded

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
Found duplicate: https://github.com/CDCgov/trusted-intermediary/issues/869

**Comment by jorg3lopez** [comment]
Load test is broken, so we couldn't run the test. 

ref: #1044
