### ISSUE TITLE
LA HCO Order Profile

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#991]
# Story
As LA HCO, to ensure we'll send all the data needed by the LIMS, we need to understand how specimen card and EHR fields relate to the data elements of an electronic order.

## Pre-conditions
- [ ]

## Acceptance Criteria
- [ ]  Approved message profile

## Tasks
- [x] Obtain publish message profile (if available)
- [x] Obtain sample messages
- [x] Document data elements of interest
  - [x] Optionality
  - [x] Cardinality
  - [x] Vocabulary requirements
- [ ] Requested HCO feedback on our analysis
- [ ] Confirm baseline profile requirements with Sender

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
https://docs.google.com/spreadsheets/d/1DHMO0x8CzMwMgrz5C9T21kPGw-mcCm9r/edit?usp=drive_link&ouid=102849307490663018252&rtpof=true&sd=true

New LA Results Gap Analysis link.
