### ISSUE TITLE
AL PHL Results Profile

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#994]
# Story
As AL PHL, to ensure we'll sending all needed results data to an EHR, we need to relate the LIMS results information to what will be sent out to ReportStream.

## Pre-conditions
- none

## Acceptance Criteria
- [x] Identified what are the fields required

## Tasks
- [x] Confirm vocabulary documentation with code assignments with PHL
- [x] Obtain publish message profile (if available)
- [x] Obtain sample messages
- [x] Document data elements of interest
  - [x] Optionality
  - [x] Cardinality
  - [x] Vocabulary requirements
- [x] Confirm baseline profile requirements with Receiver

### Research
- [x] PHL workflow current state analysis

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
@JohnNKing To collab to make these profile stories, with an overarching data gap story or epic
