### ISSUE TITLE
LA PHL Results Profile

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#996]
# Story
As LA PHL, to ensure we'll sending all needed results data to an EHR, we need to relate the LIMS results information to what will be sent out to ReportStream.

## Pre-conditions
- none

## Acceptance Criteria
- [x]  Approved message profile

## Tasks
- [x] Obtain publish message profile (if available)
- [x] Obtain sample messages
- [x] Document data elements of interest
  - [x] Optionality
  - [x] Cardinality
  - [x] Vocabulary requirements
- [x] Requested PHL feedback on our analysis
- [x] Confirm baseline profile requirements with Sender

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by cjterdi** [comment]
Per Jason: Waiting for export of vocabulary configuration (results for each test and code mapping) from LA PHL

**Comment by cjterdi** [comment]
Blocked: waiting on HCO contribution

**Comment by Adrian-Brewster** [comment]
Most of the way completed. Should be able to finalize this sprint.
